// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

type AddressService struct {
	config *ClientConfig
}

func (s *AddressService) Retrieve(req *AddressRetrieveRequest) (*AddressRetrieveResponse, error) {
	req.method = "GET"
	req.path = "/addresses"
	return send[*AddressRetrieveResponse](req, s.config)
}

func (s *AddressService) Update(req *AddressUpdateRequest) (*AddressUpdateResponse, error) {
	req.method = "POST"
	req.path = "/addresses"
	req.isIdempotent = true
	return send[*AddressUpdateResponse](req, s.config)
}
