// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type AlertService struct {
	config *ClientConfig
}

func (s *AlertService) Create(req *AlertCreateRequest) (*AlertCreateResponse, error) {
	req.method = "POST"
	req.path = "/alerts"
	req.isIdempotent = true
	return send[*AlertCreateResponse](req, s.config)
}

func (s *AlertService) Retrieve(id string) (*AlertRetrieveResponse, error) {
	req := &BlankRequest{}
	req.method = "GET"
	req.path = fmt.Sprintf("/alerts/%v", url.PathEscape(id))
	return send[*AlertRetrieveResponse](req, s.config)
}

func (s *AlertService) List(req *AlertListRequest) (*AlertListResponse, error) {
	req.method = "GET"
	req.path = "/alerts"
	req.isListRequest = true
	return send[*AlertListResponse](req, s.config)
}

func (s *AlertService) Update(id string, req *AlertUpdateRequest) (*AlertUpdateResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/alerts/%v", url.PathEscape(id))
	req.isIdempotent = true
	return send[*AlertUpdateResponse](req, s.config)
}

func (s *AlertService) Delete(id string) (*AlertDeleteResponse, error) {
	req := &BlankRequest{}
	req.method = "POST"
	req.path = fmt.Sprintf("/alerts/%v/delete", url.PathEscape(id))
	req.isIdempotent = true
	return send[*AlertDeleteResponse](req, s.config)
}

func (s *AlertService) ApplicationAlertsForSubscription(id string, req *AlertApplicationAlertsForSubscriptionRequest) (*AlertApplicationAlertsForSubscriptionResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/subscriptions/%v/applicable_alerts", url.PathEscape(id))
	req.isListRequest = true
	return send[*AlertApplicationAlertsForSubscriptionResponse](req, s.config)
}
