// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type AlertStatusType string

const (
	AlertStatusTypeEnabled  AlertStatusType = "enabled"
	AlertStatusTypeDisabled AlertStatusType = "disabled"
)

type AlertFilterConditionField string

const (
	AlertFilterConditionFieldPlanPriceId AlertFilterConditionField = "plan_price_id"
)

type AlertFilterConditionOperator string

const (
	AlertFilterConditionOperatorEquals    AlertFilterConditionOperator = "equals"
	AlertFilterConditionOperatorNotEquals AlertFilterConditionOperator = "not_equals"
)

type Alert struct {
	Id               string          `json:"id"`
	Type             Type            `json:"type"`
	Name             string          `json:"name"`
	Description      string          `json:"description"`
	MeteredFeatureId string          `json:"metered_feature_id"`
	SubscriptionId   string          `json:"subscription_id"`
	Status           AlertStatusType `json:"status"`
	Meta             string          `json:"meta"`
	CreatedAt        int64           `json:"created_at"`
	UpdatedAt        int64           `json:"updated_at"`
	Object           string          `json:"object"`
}

type AlertCreateRequest struct {
	Type             Type                          `json:"type"`
	Name             string                        `json:"name"`
	Description      string                        `json:"description,omitempty"`
	MeteredFeatureId string                        `json:"metered_feature_id"`
	SubscriptionId   string                        `json:"subscription_id,omitempty"`
	Threshold        *AlertCreateThreshold         `json:"threshold,omitempty"`
	Meta             string                        `json:"meta,omitempty"`
	FilterConditions []*AlertCreateFilterCondition `json:"filter_conditions,omitempty"`
	apiRequest       `json:"-" form:"-"`
}

func (r *AlertCreateRequest) payload() any { return r }

type AlertCreateThreshold struct {
	Mode  Mode     `json:"mode"`
	Value *float64 `json:"value"`
}

type AlertCreateFilterCondition struct {
	Field    FilterConditionField    `json:"field,omitempty"`
	Operator FilterConditionOperator `json:"operator,omitempty"`
	Value    string                  `json:"value,omitempty"`
}

type AlertListRequest struct {
	Limit          *int32        `json:"limit,omitempty"`
	Offset         string        `json:"offset,omitempty"`
	Id             *StringFilter `json:"id,omitempty"`
	Type           *EnumFilter   `json:"type,omitempty"`
	SubscriptionId *StringFilter `json:"subscription_id,omitempty"`
	Status         *EnumFilter   `json:"status,omitempty"`
	apiRequest     `json:"-" form:"-"`
}

func (r *AlertListRequest) payload() any { return r }

type AlertUpdateRequest struct {
	Threshold  *AlertUpdateThreshold `json:"threshold,omitempty"`
	Status     AlertStatusType       `json:"status,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *AlertUpdateRequest) payload() any { return r }

type AlertUpdateThreshold struct {
	Mode  Mode     `json:"mode,omitempty"`
	Value *float64 `json:"value,omitempty"`
}

type AlertApplicationAlertsForSubscriptionRequest struct {
	Limit      *int32      `json:"limit,omitempty"`
	Offset     string      `json:"offset,omitempty"`
	Status     *EnumFilter `json:"status,omitempty"`
	Type       *EnumFilter `json:"type,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *AlertApplicationAlertsForSubscriptionRequest) payload() any { return r }

type AlertCreateResponse struct {
	Alert *Alert `json:"alert,omitempty"`
	apiResponse
}

type AlertRetrieveResponse struct {
	Alert *Alert `json:"alert,omitempty"`
	apiResponse
}

type AlertListAlertResponse struct {
	Alert *Alert `json:"alert,omitempty"`
}

type AlertListResponse struct {
	List       []*AlertListAlertResponse `json:"list,omitempty"`
	NextOffset string                    `json:"next_offset,omitempty"`
	apiResponse
}

type AlertUpdateResponse struct {
	Alert *Alert `json:"alert,omitempty"`
	apiResponse
}

type AlertDeleteResponse struct {
	Alert *Alert `json:"alert,omitempty"`
	apiResponse
}

type AlertApplicationAlertsForSubscriptionAlertResponse struct {
	Alert *Alert `json:"alert,omitempty"`
}

type AlertApplicationAlertsForSubscriptionResponse struct {
	List       []*AlertApplicationAlertsForSubscriptionAlertResponse `json:"list,omitempty"`
	NextOffset string                                                `json:"next_offset,omitempty"`
	apiResponse
}
