// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type AlertStatusService struct {
	config *ClientConfig
}

func (s *AlertStatusService) AlertStatusesForSubscription(id string, req *AlertStatusAlertStatusesForSubscriptionRequest) (*AlertStatusAlertStatusesForSubscriptionResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/subscriptions/%v/alert_statuses", url.PathEscape(id))
	req.isListRequest = true
	return send[*AlertStatusAlertStatusesForSubscriptionResponse](req, s.config)
}

func (s *AlertStatusService) AlertStatusesForAlert(id string, req *AlertStatusAlertStatusesForAlertRequest) (*AlertStatusAlertStatusesForAlertResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/alerts/%v/alert_statuses", url.PathEscape(id))
	req.isListRequest = true
	return send[*AlertStatusAlertStatusesForAlertResponse](req, s.config)
}
