// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type AlertStatus struct {
	AlertId          string      `json:"alert_id"`
	SubscriptionId   string      `json:"subscription_id"`
	AlarmStatus      AlarmStatus `json:"alarm_status"`
	AlarmTriggeredAt int64       `json:"alarm_triggered_at"`
	Object           string      `json:"object"`
}

type AlertStatusAlertStatusesForSubscriptionRequest struct {
	Limit       *int32        `json:"limit,omitempty"`
	Offset      string        `json:"offset,omitempty"`
	AlarmStatus *EnumFilter   `json:"alarm_status,omitempty"`
	AlertId     *StringFilter `json:"alert_id,omitempty"`
	apiRequest  `json:"-" form:"-"`
}

func (r *AlertStatusAlertStatusesForSubscriptionRequest) payload() any { return r }

type AlertStatusAlertStatusesForAlertRequest struct {
	Limit       *int32      `json:"limit,omitempty"`
	Offset      string      `json:"offset,omitempty"`
	AlarmStatus *EnumFilter `json:"alarm_status,omitempty"`
	apiRequest  `json:"-" form:"-"`
}

func (r *AlertStatusAlertStatusesForAlertRequest) payload() any { return r }

type AlertStatusAlertStatusesForSubscriptionAlertStatusResponse struct {
	AlertStatus *AlertStatus `json:"alert_status,omitempty"`
}

type AlertStatusAlertStatusesForSubscriptionResponse struct {
	List       []*AlertStatusAlertStatusesForSubscriptionAlertStatusResponse `json:"list,omitempty"`
	NextOffset string                                                        `json:"next_offset,omitempty"`
	apiResponse
}

type AlertStatusAlertStatusesForAlertAlertStatusResponse struct {
	AlertStatus *AlertStatus `json:"alert_status,omitempty"`
}

type AlertStatusAlertStatusesForAlertResponse struct {
	List       []*AlertStatusAlertStatusesForAlertAlertStatusResponse `json:"list,omitempty"`
	NextOffset string                                                 `json:"next_offset,omitempty"`
	apiResponse
}
