// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type AppliedBusinessRuleEntityType string

const (
	AppliedBusinessRuleEntityTypeCpqQuote AppliedBusinessRuleEntityType = "cpq_quote"
)

type AppliedBusinessRule struct {
	Handle        string                        `json:"handle"`
	EntityType    AppliedBusinessRuleEntityType `json:"entity_type"`
	EntityId      int64                         `json:"entity_id"`
	EntityVersion int32                         `json:"entity_version"`
	RuleId        string                        `json:"rule_id"`
	Version       int32                         `json:"version"`
	CreatedAt     int64                         `json:"created_at"`
	ModifiedAt    int64                         `json:"modified_at"`
	Object        string                        `json:"object"`
}
