// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

import (
	"encoding/json"
)

type ApplyRule struct {
	Evaluate             bool             `json:"evaluate"`
	RuleId               string           `json:"rule_id"`
	RulesetId            string           `json:"ruleset_id"`
	SkipFailedRules      bool             `json:"skip_failed_rules"`
	StructuredExpression json.RawMessage  `json:"structured_expression"`
	Context              json.RawMessage  `json:"context"`
	Rules                []*ApplyRuleRule `json:"rules"`
	Object               string           `json:"object"`
}

type ApplyRuleRule struct {
	Id               string          `json:"id"`
	Version          int32           `json:"version"`
	Name             string          `json:"name"`
	Description      string          `json:"description"`
	EvaluationResult bool            `json:"evaluation_result"`
	ErrorMessage     string          `json:"error_message"`
	Actions          json.RawMessage `json:"actions"`
	Object           string          `json:"object"`
}
