// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type AsyncResponseListListStatus string

const (
	AsyncResponseListListStatusSuccess AsyncResponseListListStatus = "success"
	AsyncResponseListListStatusFailed  AsyncResponseListListStatus = "failed"
)

type AsyncResponseList struct {
	List   []*AsyncResponse `json:"list"`
	Object string           `json:"object"`
}
