// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

import (
	"encoding/json"
)

type AsyncResponseStatus string

const (
	AsyncResponseStatusSuccess AsyncResponseStatus = "success"
	AsyncResponseStatusFailed  AsyncResponseStatus = "failed"
)

type AsyncResponse struct {
	ApiVersion  string                        `json:"api_version"`
	CreatedAt   int64                         `json:"created_at"`
	CompletedAt int64                         `json:"completed_at"`
	Status      AsyncResponseStatus           `json:"status"`
	Request     *AsyncResponseRequestAsyncApi `json:"request"`
	ErrorDetail *AsyncResponseError           `json:"error_detail"`
	Result      json.RawMessage               `json:"result"`
	Object      string                        `json:"object"`
}

type AsyncResponseRequestAsyncApi struct {
	Id             string `json:"id"`
	Resource       string `json:"resource"`
	OperationType  string `json:"operation_type"`
	Method         string `json:"method"`
	Uri            string `json:"uri"`
	IdempotencyKey string `json:"idempotency_key"`
	Object         string `json:"object"`
}

type AsyncResponseError struct {
	Message        string `json:"message"`
	Type           string `json:"type"`
	ApiErrorCode   string `json:"api_error_code"`
	ErrorCode      string `json:"error_code"`
	ErrorMsg       string `json:"error_msg"`
	HttpStatusCode string `json:"http_status_code"`
	Object         string `json:"object"`
}
