// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

import (
	"encoding/json"
)

type BusinessRule struct {
	Id                   string          `json:"id"`
	Name                 string          `json:"name"`
	Description          string          `json:"description"`
	LatestVersion        int32           `json:"latest_version"`
	Active               bool            `json:"active"`
	ReleasedAt           int64           `json:"released_at"`
	ReleasedBy           string          `json:"released_by"`
	UpdatedAt            int64           `json:"updated_at"`
	UpdatedBy            string          `json:"updated_by"`
	CreatedBy            string          `json:"created_by"`
	CreatedAt            int64           `json:"created_at"`
	Tags                 json.RawMessage `json:"tags"`
	StructuredExpression json.RawMessage `json:"structured_expression"`
	ActionsOnSuccess     json.RawMessage `json:"actions_on_success"`
	ResourceVersion      int64           `json:"resource_version"`
	Object               string          `json:"object"`
}

type BusinessRuleCreateRequest struct {
	Id                   string                 `json:"id,omitempty"`
	Name                 string                 `json:"name"`
	Description          string                 `json:"description,omitempty"`
	Tags                 []interface{}          `json:"tags,omitempty"`
	StructuredExpression map[string]interface{} `json:"structured_expression"`
	ActionsOnSuccess     []interface{}          `json:"actions_on_success,omitempty"`
	apiRequest           `json:"-" form:"-"`
}

func (r *BusinessRuleCreateRequest) payload() any { return r }

type BusinessRuleDeleteRequest struct {
	Id         string `json:"-" form:"-"`
	apiRequest `json:"-" form:"-"`
}

func (r *BusinessRuleDeleteRequest) payload() any { return r }

type BusinessRuleUpdateDraftRequest struct {
	Name                 string                 `json:"name"`
	Description          string                 `json:"description,omitempty"`
	Tags                 []interface{}          `json:"tags,omitempty"`
	StructuredExpression map[string]interface{} `json:"structured_expression"`
	ActionsOnSuccess     []interface{}          `json:"actions_on_success,omitempty"`
	apiRequest           `json:"-" form:"-"`
}

func (r *BusinessRuleUpdateDraftRequest) payload() any { return r }

type BusinessRuleListRequest struct {
	Limit      *int32         `json:"limit,omitempty"`
	Offset     string         `json:"offset,omitempty"`
	Draft      *BooleanFilter `json:"draft,omitempty"`
	Active     *BooleanFilter `json:"active,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *BusinessRuleListRequest) payload() any { return r }

type BusinessRuleRetrieveRequest struct {
	Id         string `json:"-" form:"-"`
	apiRequest `json:"-" form:"-"`
}

func (r *BusinessRuleRetrieveRequest) payload() any { return r }

type BusinessRuleRetrieveDraftRequest struct {
	Id         string `json:"-" form:"-"`
	apiRequest `json:"-" form:"-"`
}

func (r *BusinessRuleRetrieveDraftRequest) payload() any { return r }

type BusinessRuleDeleteDraftRequest struct {
	Id         string `json:"-" form:"-"`
	apiRequest `json:"-" form:"-"`
}

func (r *BusinessRuleDeleteDraftRequest) payload() any { return r }

type BusinessRuleActivateRuleRequest struct {
	Id         string `json:"-" form:"-"`
	apiRequest `json:"-" form:"-"`
}

func (r *BusinessRuleActivateRuleRequest) payload() any { return r }

type BusinessRuleDeactivateRuleRequest struct {
	Id         string `json:"-" form:"-"`
	apiRequest `json:"-" form:"-"`
}

func (r *BusinessRuleDeactivateRuleRequest) payload() any { return r }

type BusinessRuleReleaseRuleRequest struct {
	Id         string `json:"-" form:"-"`
	apiRequest `json:"-" form:"-"`
}

func (r *BusinessRuleReleaseRuleRequest) payload() any { return r }

type BusinessRuleApplyRulesRequest struct {
	Evaluate             *bool                  `json:"evaluate,omitempty"`
	RuleId               string                 `json:"rule_id,omitempty"`
	RulesetId            string                 `json:"ruleset_id,omitempty"`
	SkipFailedRules      *bool                  `json:"skip_failed_rules,omitempty"`
	StructuredExpression map[string]interface{} `json:"structured_expression,omitempty"`
	Context              map[string]interface{} `json:"context,omitempty"`
	apiRequest           `json:"-" form:"-"`
}

func (r *BusinessRuleApplyRulesRequest) payload() any { return r }

type BusinessRuleCreateResponse struct {
	BusinessRule *BusinessRule `json:"business_rule,omitempty"`
	apiResponse
}

type BusinessRuleDeleteResponse struct {
	BusinessRule *BusinessRule `json:"business_rule,omitempty"`
	apiResponse
}

type BusinessRuleUpdateDraftResponse struct {
	BusinessRule *BusinessRule `json:"business_rule,omitempty"`
	apiResponse
}

type BusinessRuleListBusinessRuleResponse struct {
	BusinessRule *BusinessRule `json:"business_rule,omitempty"`
}

type BusinessRuleListResponse struct {
	List       []*BusinessRuleListBusinessRuleResponse `json:"list,omitempty"`
	NextOffset string                                  `json:"next_offset,omitempty"`
	apiResponse
}

type BusinessRuleRetrieveResponse struct {
	BusinessRule *BusinessRule `json:"business_rule,omitempty"`
	apiResponse
}

type BusinessRuleRetrieveDraftResponse struct {
	BusinessRule *BusinessRule `json:"business_rule,omitempty"`
	apiResponse
}

type BusinessRuleDeleteDraftResponse struct {
	BusinessRule *BusinessRule `json:"business_rule,omitempty"`
	apiResponse
}

type BusinessRuleActivateRuleResponse struct {
	BusinessRule *BusinessRule `json:"business_rule,omitempty"`
	apiResponse
}

type BusinessRuleDeactivateRuleResponse struct {
	BusinessRule *BusinessRule `json:"business_rule,omitempty"`
	apiResponse
}

type BusinessRuleReleaseRuleResponse struct {
	BusinessRule *BusinessRule `json:"business_rule,omitempty"`
	apiResponse
}

type BusinessRuleApplyRulesResponse struct {
	ApplyRule ApplyRule `json:"apply_rule,omitempty"`
	apiResponse
}
