// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

type BusinessEntityService struct {
	config *ClientConfig
}

func (s *BusinessEntityService) CreateTransfers(req *BusinessEntityCreateTransfersRequest) (*BusinessEntityCreateTransfersResponse, error) {
	req.method = "POST"
	req.path = "/business_entities/transfers"
	req.isIdempotent = true
	req.telemetryResource = "businessEntity"
	req.telemetryOperation = "createTransfers"

	return send[*BusinessEntityCreateTransfersResponse](req, s.config)
}

func (s *BusinessEntityService) GetTransfers(req *BusinessEntityGetTransfersRequest) (*BusinessEntityGetTransfersResponse, error) {
	req.method = "GET"
	req.path = "/business_entities/transfers"
	req.isListRequest = true
	req.telemetryResource = "businessEntity"
	req.telemetryOperation = "getTransfers"

	return send[*BusinessEntityGetTransfersResponse](req, s.config)
}
