// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

import (
	"encoding/json"
)

type BusinessRulesetExecuteMode string

const (
	BusinessRulesetExecuteModeStopOnFirstTrue  BusinessRulesetExecuteMode = "stop_on_first_true"
	BusinessRulesetExecuteModeStopOnFirstFalse BusinessRulesetExecuteMode = "stop_on_first_false"
	BusinessRulesetExecuteModeExecuteAll       BusinessRulesetExecuteMode = "execute_all"
	BusinessRulesetExecuteModeExecuteAllTrue   BusinessRulesetExecuteMode = "execute_all_true"
)

type BusinessRuleset struct {
	Id              string                     `json:"id"`
	Name            string                     `json:"name"`
	Description     string                     `json:"description"`
	Active          bool                       `json:"active"`
	ExecuteMode     BusinessRulesetExecuteMode `json:"execute_mode"`
	UpdatedAt       int64                      `json:"updated_at"`
	UpdatedBy       string                     `json:"updated_by"`
	CreatedBy       string                     `json:"created_by"`
	CreatedAt       int64                      `json:"created_at"`
	Rules           json.RawMessage            `json:"rules"`
	ResourceVersion int64                      `json:"resource_version"`
	Object          string                     `json:"object"`
}

type BusinessRulesetCreateRequest struct {
	Id          string                     `json:"id,omitempty"`
	Name        string                     `json:"name"`
	Description string                     `json:"description,omitempty"`
	ExecuteMode BusinessRulesetExecuteMode `json:"execute_mode,omitempty"`
	Rules       []interface{}              `json:"rules,omitempty"`
	apiRequest  `json:"-" form:"-"`
}

func (r *BusinessRulesetCreateRequest) payload() any { return r }

type BusinessRulesetUpdateRequest struct {
	Name        string                     `json:"name"`
	Description string                     `json:"description,omitempty"`
	ExecuteMode BusinessRulesetExecuteMode `json:"execute_mode,omitempty"`
	Rules       []interface{}              `json:"rules,omitempty"`
	apiRequest  `json:"-" form:"-"`
}

func (r *BusinessRulesetUpdateRequest) payload() any { return r }

type BusinessRulesetDeleteRequest struct {
	Id         string `json:"-" form:"-"`
	apiRequest `json:"-" form:"-"`
}

func (r *BusinessRulesetDeleteRequest) payload() any { return r }

type BusinessRulesetActivateRequest struct {
	Id         string `json:"-" form:"-"`
	apiRequest `json:"-" form:"-"`
}

func (r *BusinessRulesetActivateRequest) payload() any { return r }

type BusinessRulesetDeactivateRequest struct {
	Id         string `json:"-" form:"-"`
	apiRequest `json:"-" form:"-"`
}

func (r *BusinessRulesetDeactivateRequest) payload() any { return r }

type BusinessRulesetAddRulesRequest struct {
	Rules      []interface{} `json:"rules,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *BusinessRulesetAddRulesRequest) payload() any { return r }

type BusinessRulesetRemoveRulesRequest struct {
	Rules      []interface{} `json:"rules,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *BusinessRulesetRemoveRulesRequest) payload() any { return r }

type BusinessRulesetListRulesRequest struct {
	Limit      *int32         `json:"limit,omitempty"`
	Offset     string         `json:"offset,omitempty"`
	Active     *BooleanFilter `json:"active,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *BusinessRulesetListRulesRequest) payload() any { return r }

type BusinessRulesetListRequest struct {
	Limit      *int32         `json:"limit,omitempty"`
	Offset     string         `json:"offset,omitempty"`
	Active     *BooleanFilter `json:"active,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *BusinessRulesetListRequest) payload() any { return r }

type BusinessRulesetRetrieveRequest struct {
	Id         string `json:"-" form:"-"`
	apiRequest `json:"-" form:"-"`
}

func (r *BusinessRulesetRetrieveRequest) payload() any { return r }

type BusinessRulesetCreateResponse struct {
	BusinessRuleset *BusinessRuleset `json:"business_ruleset,omitempty"`
	apiResponse
}

type BusinessRulesetUpdateResponse struct {
	BusinessRuleset *BusinessRuleset `json:"business_ruleset,omitempty"`
	apiResponse
}

type BusinessRulesetDeleteResponse struct {
	BusinessRuleset *BusinessRuleset `json:"business_ruleset,omitempty"`
	apiResponse
}

type BusinessRulesetActivateResponse struct {
	BusinessRuleset *BusinessRuleset `json:"business_ruleset,omitempty"`
	apiResponse
}

type BusinessRulesetDeactivateResponse struct {
	BusinessRuleset *BusinessRuleset `json:"business_ruleset,omitempty"`
	apiResponse
}

type BusinessRulesetAddRulesResponse struct {
	BusinessRuleset *BusinessRuleset `json:"business_ruleset,omitempty"`
	apiResponse
}

type BusinessRulesetRemoveRulesResponse struct {
	BusinessRuleset *BusinessRuleset `json:"business_ruleset,omitempty"`
	apiResponse
}

type BusinessRulesetListRulesResponse struct {
	BusinessRulesetRule BusinessRulesetRule `json:"business_ruleset_rule,omitempty"`
	apiResponse
}

type BusinessRulesetListBusinessRulesetResponse struct {
	BusinessRuleset *BusinessRuleset `json:"business_ruleset,omitempty"`
}

type BusinessRulesetListResponse struct {
	List       []*BusinessRulesetListBusinessRulesetResponse `json:"list,omitempty"`
	NextOffset string                                        `json:"next_offset,omitempty"`
	apiResponse
}

type BusinessRulesetRetrieveResponse struct {
	BusinessRuleset *BusinessRuleset `json:"business_ruleset,omitempty"`
	apiResponse
}
