// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type BusinessRulesetService struct {
	config *ClientConfig
}

func (s *BusinessRulesetService) Create(req *BusinessRulesetCreateRequest) (*BusinessRulesetCreateResponse, error) {
	req.method = "POST"
	req.path = "/business_rulesets"
	req.isIdempotent = true
	req.telemetryResource = "businessRuleset"
	req.telemetryOperation = "create"

	return send[*BusinessRulesetCreateResponse](req, s.config)
}

func (s *BusinessRulesetService) Update(id string, req *BusinessRulesetUpdateRequest) (*BusinessRulesetUpdateResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/business_rulesets/%v", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "businessRuleset"
	req.telemetryOperation = "update"

	return send[*BusinessRulesetUpdateResponse](req, s.config)
}

func (s *BusinessRulesetService) Delete(req *BusinessRulesetDeleteRequest) (*BusinessRulesetDeleteResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/business_rulesets/%v/delete", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "businessRuleset"
	req.telemetryOperation = "delete"

	return send[*BusinessRulesetDeleteResponse](req, s.config)
}

func (s *BusinessRulesetService) Activate(req *BusinessRulesetActivateRequest) (*BusinessRulesetActivateResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/business_rulesets/%v/activate", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "businessRuleset"
	req.telemetryOperation = "activate"

	return send[*BusinessRulesetActivateResponse](req, s.config)
}

func (s *BusinessRulesetService) Deactivate(req *BusinessRulesetDeactivateRequest) (*BusinessRulesetDeactivateResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/business_rulesets/%v/deactivate", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "businessRuleset"
	req.telemetryOperation = "deactivate"

	return send[*BusinessRulesetDeactivateResponse](req, s.config)
}

func (s *BusinessRulesetService) AddRules(id string, req *BusinessRulesetAddRulesRequest) (*BusinessRulesetAddRulesResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/business_rulesets/%v/add_rules", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "businessRuleset"
	req.telemetryOperation = "addRules"

	return send[*BusinessRulesetAddRulesResponse](req, s.config)
}

func (s *BusinessRulesetService) RemoveRules(id string, req *BusinessRulesetRemoveRulesRequest) (*BusinessRulesetRemoveRulesResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/business_rulesets/%v/remove_rules", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "businessRuleset"
	req.telemetryOperation = "removeRules"

	return send[*BusinessRulesetRemoveRulesResponse](req, s.config)
}

func (s *BusinessRulesetService) ListRules(id string, req *BusinessRulesetListRulesRequest) (*BusinessRulesetListRulesResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/business_rulesets/%v/rules", url.PathEscape(id))
	req.telemetryResource = "businessRuleset"
	req.telemetryOperation = "listRules"

	return send[*BusinessRulesetListRulesResponse](req, s.config)
}

func (s *BusinessRulesetService) List(req *BusinessRulesetListRequest) (*BusinessRulesetListResponse, error) {
	req.method = "GET"
	req.path = "/business_rulesets"
	req.isListRequest = true
	req.telemetryResource = "businessRuleset"
	req.telemetryOperation = "list"

	return send[*BusinessRulesetListResponse](req, s.config)
}

func (s *BusinessRulesetService) Retrieve(req *BusinessRulesetRetrieveRequest) (*BusinessRulesetRetrieveResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/business_rulesets/%v", url.PathEscape(req.Id))
	req.telemetryResource = "businessRuleset"
	req.telemetryOperation = "retrieve"

	return send[*BusinessRulesetRetrieveResponse](req, s.config)
}
