// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type CardService struct {
	config *ClientConfig
}

func (s *CardService) Retrieve(req *CardRetrieveRequest) (*CardRetrieveResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/cards/%v", url.PathEscape(req.Id))
	req.telemetryResource = "card"
	req.telemetryOperation = "retrieve"

	return send[*CardRetrieveResponse](req, s.config)
}

func (s *CardService) UpdateCardForCustomer(id string, req *CardUpdateCardForCustomerRequest) (*CardUpdateCardForCustomerResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/customers/%v/credit_card", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "card"
	req.telemetryOperation = "updateCardForCustomer"

	return send[*CardUpdateCardForCustomerResponse](req, s.config)
}

func (s *CardService) SwitchGatewayForCustomer(id string, req *CardSwitchGatewayForCustomerRequest) (*CardSwitchGatewayForCustomerResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/customers/%v/switch_gateway", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "card"
	req.telemetryOperation = "switchGatewayForCustomer"

	return send[*CardSwitchGatewayForCustomerResponse](req, s.config)
}

func (s *CardService) CopyCardForCustomer(id string, req *CardCopyCardForCustomerRequest) (*CardCopyCardForCustomerResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/customers/%v/copy_card", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "card"
	req.telemetryOperation = "copyCardForCustomer"

	return send[*CardCopyCardForCustomerResponse](req, s.config)
}

func (s *CardService) DeleteCardForCustomer(req *CardDeleteCardForCustomerRequest) (*CardDeleteCardForCustomerResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/customers/%v/delete_card", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "card"
	req.telemetryOperation = "deleteCardForCustomer"

	return send[*CardDeleteCardForCustomerResponse](req, s.config)
}
