// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type ColumnDefinitionDataType string

const (
	ColumnDefinitionDataTypeNumber ColumnDefinitionDataType = "number"
	ColumnDefinitionDataTypeString ColumnDefinitionDataType = "string"
)

type ColumnDefinition struct {
	ColumnName string                   `json:"column_name"`
	DataType   ColumnDefinitionDataType `json:"data_type"`
	Object     string                   `json:"object"`
}
