// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type CommentType string

const (
	CommentTypeUser   CommentType = "user"
	CommentTypeSystem CommentType = "system"
)

type Comment struct {
	Id               string      `json:"id"`
	EntityType       EntityType  `json:"entity_type"`
	AddedBy          string      `json:"added_by"`
	Notes            string      `json:"notes"`
	CreatedAt        int64       `json:"created_at"`
	Type             CommentType `json:"type"`
	EntityId         string      `json:"entity_id"`
	BusinessEntityId string      `json:"business_entity_id"`
	Object           string      `json:"object"`
}

type CommentCreateRequest struct {
	EntityType EntityType `json:"entity_type"`
	EntityId   string     `json:"entity_id"`
	Notes      string     `json:"notes"`
	AddedBy    string     `json:"added_by,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *CommentCreateRequest) payload() any { return r }

type CommentListRequest struct {
	Limit      *int32           `json:"limit,omitempty"`
	Offset     string           `json:"offset,omitempty"`
	EntityType EntityType       `json:"entity_type,omitempty"`
	EntityId   string           `json:"entity_id,omitempty"`
	CreatedAt  *TimestampFilter `json:"created_at,omitempty"`
	SortBy     *SortFilter      `json:"sort_by,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *CommentListRequest) payload() any { return r }

type CommentCreateResponse struct {
	Comment *Comment `json:"comment,omitempty"`
	apiResponse
}

type CommentRetrieveResponse struct {
	Comment *Comment `json:"comment,omitempty"`
	apiResponse
}

type CommentListCommentResponse struct {
	Comment *Comment `json:"comment,omitempty"`
}

type CommentListResponse struct {
	List       []*CommentListCommentResponse `json:"list,omitempty"`
	NextOffset string                        `json:"next_offset,omitempty"`
	apiResponse
}

type CommentDeleteResponse struct {
	Comment *Comment `json:"comment,omitempty"`
	apiResponse
}
