// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type CommentService struct {
	config *ClientConfig
}

func (s *CommentService) Create(req *CommentCreateRequest) (*CommentCreateResponse, error) {
	req.method = "POST"
	req.path = "/comments"
	req.isIdempotent = true
	req.telemetryResource = "comment"
	req.telemetryOperation = "create"

	return send[*CommentCreateResponse](req, s.config)
}

func (s *CommentService) Retrieve(req *CommentRetrieveRequest) (*CommentRetrieveResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/comments/%v", url.PathEscape(req.Id))
	req.telemetryResource = "comment"
	req.telemetryOperation = "retrieve"

	return send[*CommentRetrieveResponse](req, s.config)
}

func (s *CommentService) List(req *CommentListRequest) (*CommentListResponse, error) {
	req.method = "GET"
	req.path = "/comments"
	req.isListRequest = true
	req.telemetryResource = "comment"
	req.telemetryOperation = "list"

	return send[*CommentListResponse](req, s.config)
}

func (s *CommentService) Delete(req *CommentDeleteRequest) (*CommentDeleteResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/comments/%v/delete", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "comment"
	req.telemetryOperation = "delete"

	return send[*CommentDeleteResponse](req, s.config)
}
