// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type Configuration struct {
	Domain                      string                      `json:"domain"`
	ProductCatalogVersion       ProductCatalogVersion       `json:"product_catalog_version"`
	ChargebeeResponseSchemaType ChargebeeResponseSchemaType `json:"chargebee_response_schema_type"`
	Object                      string                      `json:"object"`
}

type ConfigurationListResponse struct {
	Configurations []*Configuration `json:"configurations,omitempty"`
	apiResponse
}
