// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

type ConfigurationService struct {
	config *ClientConfig
}

func (s *ConfigurationService) List() (*ConfigurationListResponse, error) {
	req := &BlankRequest{}
	req.method = "GET"
	req.path = "/configurations"
	return send[*ConfigurationListResponse](req, s.config)
}
