// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type CouponService struct {
	config *ClientConfig
}

func (s *CouponService) Create(req *CouponCreateRequest) (*CouponCreateResponse, error) {
	req.method = "POST"
	req.path = "/coupons"
	req.isIdempotent = true
	return send[*CouponCreateResponse](req, s.config)
}

func (s *CouponService) CreateForItems(req *CouponCreateForItemsRequest) (*CouponCreateForItemsResponse, error) {
	req.method = "POST"
	req.path = "/coupons/create_for_items"
	req.isIdempotent = true
	return send[*CouponCreateForItemsResponse](req, s.config)
}

func (s *CouponService) UpdateForItems(id string, req *CouponUpdateForItemsRequest) (*CouponUpdateForItemsResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/coupons/%v/update_for_items", url.PathEscape(id))
	req.isIdempotent = true
	return send[*CouponUpdateForItemsResponse](req, s.config)
}

func (s *CouponService) List(req *CouponListRequest) (*CouponListResponse, error) {
	req.method = "GET"
	req.path = "/coupons"
	req.isListRequest = true
	return send[*CouponListResponse](req, s.config)
}

func (s *CouponService) Retrieve(id string) (*CouponRetrieveResponse, error) {
	req := &BlankRequest{}
	req.method = "GET"
	req.path = fmt.Sprintf("/coupons/%v", url.PathEscape(id))
	return send[*CouponRetrieveResponse](req, s.config)
}

func (s *CouponService) Update(id string, req *CouponUpdateRequest) (*CouponUpdateResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/coupons/%v", url.PathEscape(id))
	req.isIdempotent = true
	return send[*CouponUpdateResponse](req, s.config)
}

func (s *CouponService) Delete(id string) (*CouponDeleteResponse, error) {
	req := &BlankRequest{}
	req.method = "POST"
	req.path = fmt.Sprintf("/coupons/%v/delete", url.PathEscape(id))
	req.isIdempotent = true
	return send[*CouponDeleteResponse](req, s.config)
}

func (s *CouponService) Copy(req *CouponCopyRequest) (*CouponCopyResponse, error) {
	req.method = "POST"
	req.path = "/coupons/copy"
	req.isIdempotent = true
	return send[*CouponCopyResponse](req, s.config)
}

func (s *CouponService) Unarchive(id string) (*CouponUnarchiveResponse, error) {
	req := &BlankRequest{}
	req.method = "POST"
	req.path = fmt.Sprintf("/coupons/%v/unarchive", url.PathEscape(id))
	req.isIdempotent = true
	return send[*CouponUnarchiveResponse](req, s.config)
}
