// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type CouponSetService struct {
	config *ClientConfig
}

func (s *CouponSetService) Create(req *CouponSetCreateRequest) (*CouponSetCreateResponse, error) {
	req.method = "POST"
	req.path = "/coupon_sets"
	req.isIdempotent = true
	return send[*CouponSetCreateResponse](req, s.config)
}

func (s *CouponSetService) AddCouponCodes(id string, req *CouponSetAddCouponCodesRequest) (*CouponSetAddCouponCodesResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/coupon_sets/%v/add_coupon_codes", url.PathEscape(id))
	req.isIdempotent = true
	return send[*CouponSetAddCouponCodesResponse](req, s.config)
}

func (s *CouponSetService) List(req *CouponSetListRequest) (*CouponSetListResponse, error) {
	req.method = "GET"
	req.path = "/coupon_sets"
	req.isListRequest = true
	return send[*CouponSetListResponse](req, s.config)
}

func (s *CouponSetService) Retrieve(id string) (*CouponSetRetrieveResponse, error) {
	req := &BlankRequest{}
	req.method = "GET"
	req.path = fmt.Sprintf("/coupon_sets/%v", url.PathEscape(id))
	return send[*CouponSetRetrieveResponse](req, s.config)
}

func (s *CouponSetService) Update(id string, req *CouponSetUpdateRequest) (*CouponSetUpdateResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/coupon_sets/%v/update", url.PathEscape(id))
	req.isIdempotent = true
	return send[*CouponSetUpdateResponse](req, s.config)
}

func (s *CouponSetService) Delete(id string) (*CouponSetDeleteResponse, error) {
	req := &BlankRequest{}
	req.method = "POST"
	req.path = fmt.Sprintf("/coupon_sets/%v/delete", url.PathEscape(id))
	req.isIdempotent = true
	return send[*CouponSetDeleteResponse](req, s.config)
}

func (s *CouponSetService) DeleteUnusedCouponCodes(id string) (*CouponSetDeleteUnusedCouponCodesResponse, error) {
	req := &BlankRequest{}
	req.method = "POST"
	req.path = fmt.Sprintf("/coupon_sets/%v/delete_unused_coupon_codes", url.PathEscape(id))
	req.isIdempotent = true
	return send[*CouponSetDeleteUnusedCouponCodesResponse](req, s.config)
}
