// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type CreditUnitService struct {
	config *ClientConfig
}

func (s *CreditUnitService) List(req *CreditUnitListRequest) (*CreditUnitListResponse, error) {
	req.method = "GET"
	req.path = "/credit_units"
	req.isListRequest = true
	req.telemetryResource = "creditUnit"
	req.telemetryOperation = "list"

	return send[*CreditUnitListResponse](req, s.config)
}

func (s *CreditUnitService) Create(req *CreditUnitCreateRequest) (*CreditUnitCreateResponse, error) {
	req.method = "POST"
	req.path = "/credit_units"
	req.isIdempotent = true
	req.telemetryResource = "creditUnit"
	req.telemetryOperation = "create"

	return send[*CreditUnitCreateResponse](req, s.config)
}

func (s *CreditUnitService) Update(id string, req *CreditUnitUpdateRequest) (*CreditUnitUpdateResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/credit_units/%v", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "creditUnit"
	req.telemetryOperation = "update"

	return send[*CreditUnitUpdateResponse](req, s.config)
}

func (s *CreditUnitService) Archive(req *CreditUnitArchiveRequest) (*CreditUnitArchiveResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/credit_units/%v/archive_command", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "creditUnit"
	req.telemetryOperation = "archive"

	return send[*CreditUnitArchiveResponse](req, s.config)
}

func (s *CreditUnitService) Reactivate(req *CreditUnitReactivateRequest) (*CreditUnitReactivateResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/credit_units/%v/reactivate_command", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "creditUnit"
	req.telemetryOperation = "reactivate"

	return send[*CreditUnitReactivateResponse](req, s.config)
}
