// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type CustomerEntitlement struct {
	CustomerId     string `json:"customer_id"`
	SubscriptionId string `json:"subscription_id"`
	FeatureId      string `json:"feature_id"`
	Value          string `json:"value"`
	Name           string `json:"name"`
	IsEnabled      bool   `json:"is_enabled"`
	Object         string `json:"object"`
}

type CustomerEntitlementEntitlementsForCustomerRequest struct {
	Limit                   *int32 `json:"limit,omitempty"`
	Offset                  string `json:"offset,omitempty"`
	ConsolidateEntitlements *bool  `json:"consolidate_entitlements,omitempty"`
	apiRequest              `json:"-" form:"-"`
}

func (r *CustomerEntitlementEntitlementsForCustomerRequest) payload() any { return r }

type CustomerEntitlementEntitlementsForCustomerCustomerEntitlementResponse struct {
	CustomerEntitlement *CustomerEntitlement `json:"customer_entitlement,omitempty"`
}

type CustomerEntitlementEntitlementsForCustomerResponse struct {
	List       []*CustomerEntitlementEntitlementsForCustomerCustomerEntitlementResponse `json:"list,omitempty"`
	NextOffset string                                                                   `json:"next_offset,omitempty"`
	apiResponse
}
