// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type CustomDataSchemaStatus string

const (
	CustomDataSchemaStatusActive   CustomDataSchemaStatus = "active"
	CustomDataSchemaStatusArchived CustomDataSchemaStatus = "archived"
)

type CustomDataSchema struct {
	Id               string                 `json:"id"`
	DisplayName      string                 `json:"display_name"`
	EntityType       EntityType             `json:"entity_type"`
	SchemaDefinition string                 `json:"schema_definition"`
	Status           CustomDataSchemaStatus `json:"status"`
	CreatedAt        int64                  `json:"created_at"`
	ModifiedAt       int64                  `json:"modified_at"`
	UpdatedAt        int64                  `json:"updated_at"`
	Object           string                 `json:"object"`
}
