// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type DisputeStatus string

const (
	DisputeStatusInitiated      DisputeStatus = "initiated"
	DisputeStatusFundsWithdrawn DisputeStatus = "funds_withdrawn"
	DisputeStatusInReview       DisputeStatus = "in_review"
	DisputeStatusCancelled      DisputeStatus = "cancelled"
	DisputeStatusLost           DisputeStatus = "lost"
	DisputeStatusWon            DisputeStatus = "won"
)

type DisputeType string

const (
	DisputeTypeChargeback DisputeType = "chargeback"
	DisputeTypeInquiry    DisputeType = "inquiry"
)

type Dispute struct {
	Id               string        `json:"id"`
	CustomerId       string        `json:"customer_id"`
	TransactionId    string        `json:"transaction_id"`
	GatewayAccountId string        `json:"gateway_account_id"`
	IdAtGateway      string        `json:"id_at_gateway"`
	CurrencyCode     string        `json:"currency_code"`
	Amount           int64         `json:"amount"`
	Reason           string        `json:"reason"`
	Status           DisputeStatus `json:"status"`
	Type             DisputeType   `json:"type"`
	IsPartialDispute bool          `json:"is_partial_dispute"`
	CreatedAt        int64         `json:"created_at"`
	ResourceVersion  int64         `json:"resource_version"`
	UpdatedAt        int64         `json:"updated_at"`
	Object           string        `json:"object"`
}

type DisputeRetrieveRequest struct {
	Id         string `json:"-" form:"-"`
	apiRequest `json:"-" form:"-"`
}

func (r *DisputeRetrieveRequest) payload() any { return r }

type DisputeListRequest struct {
	Limit         *int32           `json:"limit,omitempty"`
	Offset        string           `json:"offset,omitempty"`
	Id            *StringFilter    `json:"id,omitempty"`
	Status        *EnumFilter      `json:"status,omitempty"`
	Type          *EnumFilter      `json:"type,omitempty"`
	CustomerId    *StringFilter    `json:"customer_id,omitempty"`
	TransactionId *StringFilter    `json:"transaction_id,omitempty"`
	Amount        *NumberFilter    `json:"amount,omitempty"`
	CreatedAt     *TimestampFilter `json:"created_at,omitempty"`
	apiRequest    `json:"-" form:"-"`
}

func (r *DisputeListRequest) payload() any { return r }

type DisputeRetrieveResponse struct {
	Dispute *Dispute `json:"dispute,omitempty"`
	apiResponse
}

type DisputeListDisputeResponse struct {
	Dispute *Dispute `json:"dispute,omitempty"`
}

type DisputeListResponse struct {
	List       []*DisputeListDisputeResponse `json:"list,omitempty"`
	NextOffset string                        `json:"next_offset,omitempty"`
	apiResponse
}
