// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

import (
	"encoding/json"
)

type EinvoiceStatus string

const (
	EinvoiceStatusScheduled              EinvoiceStatus = "scheduled"
	EinvoiceStatusSkipped                EinvoiceStatus = "skipped"
	EinvoiceStatusInProgress             EinvoiceStatus = "in_progress"
	EinvoiceStatusSuccess                EinvoiceStatus = "success"
	EinvoiceStatusFailed                 EinvoiceStatus = "failed"
	EinvoiceStatusRegistered             EinvoiceStatus = "registered"
	EinvoiceStatusAccepted               EinvoiceStatus = "accepted"
	EinvoiceStatusRejected               EinvoiceStatus = "rejected"
	EinvoiceStatusMessageAcknowledgement EinvoiceStatus = "message_acknowledgement"
	EinvoiceStatusInProcess              EinvoiceStatus = "in_process"
	EinvoiceStatusUnderQuery             EinvoiceStatus = "under_query"
	EinvoiceStatusConditionallyAccepted  EinvoiceStatus = "conditionally_accepted"
	EinvoiceStatusPaid                   EinvoiceStatus = "paid"
)

type Einvoice struct {
	Id                 string          `json:"id"`
	ReferenceId        string          `json:"reference_id"`
	ReferenceNumber    string          `json:"reference_number"`
	Status             EinvoiceStatus  `json:"status"`
	Message            string          `json:"message"`
	ProviderReferences json.RawMessage `json:"provider_references"`
	Object             string          `json:"object"`
}
