// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type EinvoiceService struct {
	config *ClientConfig
}

func (s *EinvoiceService) Retrieve(req *EinvoiceRetrieveRequest) (*EinvoiceRetrieveResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/einvoices/%v", url.PathEscape(req.Id))
	req.telemetryResource = "einvoice"
	req.telemetryOperation = "retrieve"

	return send[*EinvoiceRetrieveResponse](req, s.config)
}

func (s *EinvoiceService) ListEinvoices(req *EinvoiceListEinvoicesRequest) (*EinvoiceListEinvoicesResponse, error) {
	req.method = "GET"
	req.path = "/einvoices"
	req.isListRequest = true
	req.telemetryResource = "einvoice"
	req.telemetryOperation = "listEinvoices"

	return send[*EinvoiceListEinvoicesResponse](req, s.config)
}
