// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type EmailLogService struct {
	config *ClientConfig
}

func (s *EmailLogService) EmailLogsForCustomer(id string, req *EmailLogEmailLogsForCustomerRequest) (*EmailLogEmailLogsForCustomerResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/customers/%v/email_logs", url.PathEscape(id))
	req.isListRequest = true
	req.telemetryResource = "emailLog"
	req.telemetryOperation = "emailLogsForCustomer"

	return send[*EmailLogEmailLogsForCustomerResponse](req, s.config)
}
