// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type EmailLog struct {
	Id           string `json:"id"`
	TemplateName string `json:"template_name"`
	FromAddress  string `json:"from_address"`
	ToAddress    string `json:"to_address"`
	Subject      string `json:"subject"`
	Status       Status `json:"status"`
	CustomerId   string `json:"customer_id"`
	ErrorMessage string `json:"error_message"`
	Object       string `json:"object"`
}
