// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type EntitlementOverrideScheduleStatus string

const (
	EntitlementOverrideScheduleStatusActivated EntitlementOverrideScheduleStatus = "activated"
	EntitlementOverrideScheduleStatusScheduled EntitlementOverrideScheduleStatus = "scheduled"
	EntitlementOverrideScheduleStatusFailed    EntitlementOverrideScheduleStatus = "failed"
)

type EntitlementOverride struct {
	Id             string `json:"id"`
	SubscriptionId string `json:"subscription_id"`
	EntityId       string `json:"entity_id"`
	EntityType     string `json:"entity_type"`
	FeatureId      string `json:"feature_id"`
	FeatureName    string `json:"feature_name"`
	Value          string `json:"value"`
	Name           string `json:"name"`
	ExpiresAt      int64  `json:"expires_at"`
	EffectiveFrom  int64  `json:"effective_from"`
	IsEnabled      bool   `json:"is_enabled"`
	//Deprecated: this field is deprecated
	ScheduleStatus EntitlementOverrideScheduleStatus `json:"schedule_status"`
	Object         string                            `json:"object"`
}

type EntitlementOverrideAddEntitlementOverrideForSubscriptionRequest struct {
	Action               Action                                                                         `json:"action,omitempty"`
	EntitlementOverrides []*EntitlementOverrideAddEntitlementOverrideForSubscriptionEntitlementOverride `json:"entitlement_overrides,omitempty"`
	apiRequest           `json:"-" form:"-"`
}

func (r *EntitlementOverrideAddEntitlementOverrideForSubscriptionRequest) payload() any { return r }

type EntitlementOverrideAddEntitlementOverrideForSubscriptionEntitlementOverride struct {
	FeatureId     string     `json:"feature_id"`
	EntityId      string     `json:"entity_id,omitempty"`
	EntityType    EntityType `json:"entity_type,omitempty"`
	Value         string     `json:"value,omitempty"`
	ExpiresAt     *int64     `json:"expires_at,omitempty"`
	EffectiveFrom *int64     `json:"effective_from,omitempty"`
	IsEnabled     *bool      `json:"is_enabled,omitempty"`
}

type EntitlementOverrideListEntitlementOverrideForSubscriptionRequest struct {
	Limit      *int32 `json:"limit,omitempty"`
	Offset     string `json:"offset,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *EntitlementOverrideListEntitlementOverrideForSubscriptionRequest) payload() any { return r }

type EntitlementOverrideAddEntitlementOverrideForSubscriptionEntitlementOverrideResponse struct {
	EntitlementOverride *EntitlementOverride `json:"entitlement_override,omitempty"`
}

type EntitlementOverrideAddEntitlementOverrideForSubscriptionResponse struct {
	List []*EntitlementOverrideAddEntitlementOverrideForSubscriptionEntitlementOverrideResponse `json:"list,omitempty"`
	apiResponse
}

type EntitlementOverrideListEntitlementOverrideForSubscriptionEntitlementOverrideResponse struct {
	EntitlementOverride *EntitlementOverride `json:"entitlement_override,omitempty"`
}

type EntitlementOverrideListEntitlementOverrideForSubscriptionResponse struct {
	List       []*EntitlementOverrideListEntitlementOverrideForSubscriptionEntitlementOverrideResponse `json:"list,omitempty"`
	NextOffset string                                                                                  `json:"next_offset,omitempty"`
	apiResponse
}
