// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type EntitlementOverrideService struct {
	config *ClientConfig
}

func (s *EntitlementOverrideService) AddEntitlementOverrideForSubscription(id string, req *EntitlementOverrideAddEntitlementOverrideForSubscriptionRequest) (*EntitlementOverrideAddEntitlementOverrideForSubscriptionResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/subscriptions/%v/entitlement_overrides", url.PathEscape(id))
	req.isIdempotent = true
	return send[*EntitlementOverrideAddEntitlementOverrideForSubscriptionResponse](req, s.config)
}

func (s *EntitlementOverrideService) ListEntitlementOverrideForSubscription(id string, req *EntitlementOverrideListEntitlementOverrideForSubscriptionRequest) (*EntitlementOverrideListEntitlementOverrideForSubscriptionResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/subscriptions/%v/entitlement_overrides", url.PathEscape(id))
	req.isListRequest = true
	return send[*EntitlementOverrideListEntitlementOverrideForSubscriptionResponse](req, s.config)
}
