// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

type EntitlementService struct {
	config *ClientConfig
}

func (s *EntitlementService) List(req *EntitlementListRequest) (*EntitlementListResponse, error) {
	req.method = "GET"
	req.path = "/entitlements"
	req.isListRequest = true
	return send[*EntitlementListResponse](req, s.config)
}

func (s *EntitlementService) Create(req *EntitlementCreateRequest) (*EntitlementCreateResponse, error) {
	req.method = "POST"
	req.path = "/entitlements"
	req.isIdempotent = true
	return send[*EntitlementCreateResponse](req, s.config)
}
