// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type EventService struct {
	config *ClientConfig
}

func (s *EventService) List(req *EventListRequest) (*EventListResponse, error) {
	req.method = "GET"
	req.path = "/events"
	req.isListRequest = true
	req.telemetryResource = "event"
	req.telemetryOperation = "list"

	return send[*EventListResponse](req, s.config)
}

func (s *EventService) Retrieve(req *EventRetrieveRequest) (*EventRetrieveResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/events/%v", url.PathEscape(req.Id))
	req.telemetryResource = "event"
	req.telemetryOperation = "retrieve"

	return send[*EventRetrieveResponse](req, s.config)
}
