// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"errors"
	"fmt"
	"net/url"
	"time"
)

type ExportService struct {
	config *ClientConfig
}

func (s *ExportService) Retrieve(req *ExportRetrieveRequest) (*ExportRetrieveResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/exports/%v", url.PathEscape(req.Id))
	req.telemetryResource = "export"
	req.telemetryOperation = "retrieve"

	return send[*ExportRetrieveResponse](req, s.config)
}

func (s *ExportService) RevenueRecognition(req *ExportRevenueRecognitionRequest) (*ExportRevenueRecognitionResponse, error) {
	req.method = "POST"
	req.path = "/exports/revenue_recognition"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "revenueRecognition"

	return send[*ExportRevenueRecognitionResponse](req, s.config)
}

func (s *ExportService) DeferredRevenue(req *ExportDeferredRevenueRequest) (*ExportDeferredRevenueResponse, error) {
	req.method = "POST"
	req.path = "/exports/deferred_revenue"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "deferredRevenue"

	return send[*ExportDeferredRevenueResponse](req, s.config)
}

func (s *ExportService) Plans(req *ExportPlansRequest) (*ExportPlansResponse, error) {
	req.method = "POST"
	req.path = "/exports/plans"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "plans"

	return send[*ExportPlansResponse](req, s.config)
}

func (s *ExportService) Addons(req *ExportAddonsRequest) (*ExportAddonsResponse, error) {
	req.method = "POST"
	req.path = "/exports/addons"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "addons"

	return send[*ExportAddonsResponse](req, s.config)
}

func (s *ExportService) Coupons(req *ExportCouponsRequest) (*ExportCouponsResponse, error) {
	req.method = "POST"
	req.path = "/exports/coupons"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "coupons"

	return send[*ExportCouponsResponse](req, s.config)
}

func (s *ExportService) Customers(req *ExportCustomersRequest) (*ExportCustomersResponse, error) {
	req.method = "POST"
	req.path = "/exports/customers"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "customers"

	return send[*ExportCustomersResponse](req, s.config)
}

func (s *ExportService) Subscriptions(req *ExportSubscriptionsRequest) (*ExportSubscriptionsResponse, error) {
	req.method = "POST"
	req.path = "/exports/subscriptions"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "subscriptions"

	return send[*ExportSubscriptionsResponse](req, s.config)
}

func (s *ExportService) Invoices(req *ExportInvoicesRequest) (*ExportInvoicesResponse, error) {
	req.method = "POST"
	req.path = "/exports/invoices"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "invoices"

	return send[*ExportInvoicesResponse](req, s.config)
}

func (s *ExportService) CreditNotes(req *ExportCreditNotesRequest) (*ExportCreditNotesResponse, error) {
	req.method = "POST"
	req.path = "/exports/credit_notes"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "creditNotes"

	return send[*ExportCreditNotesResponse](req, s.config)
}

func (s *ExportService) Transactions(req *ExportTransactionsRequest) (*ExportTransactionsResponse, error) {
	req.method = "POST"
	req.path = "/exports/transactions"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "transactions"

	return send[*ExportTransactionsResponse](req, s.config)
}

func (s *ExportService) Orders(req *ExportOrdersRequest) (*ExportOrdersResponse, error) {
	req.method = "POST"
	req.path = "/exports/orders"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "orders"

	return send[*ExportOrdersResponse](req, s.config)
}

func (s *ExportService) ItemFamilies(req *ExportItemFamiliesRequest) (*ExportItemFamiliesResponse, error) {
	req.method = "POST"
	req.path = "/exports/item_families"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "itemFamilies"

	return send[*ExportItemFamiliesResponse](req, s.config)
}

func (s *ExportService) Items(req *ExportItemsRequest) (*ExportItemsResponse, error) {
	req.method = "POST"
	req.path = "/exports/items"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "items"

	return send[*ExportItemsResponse](req, s.config)
}

func (s *ExportService) ItemPrices(req *ExportItemPricesRequest) (*ExportItemPricesResponse, error) {
	req.method = "POST"
	req.path = "/exports/item_prices"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "itemPrices"

	return send[*ExportItemPricesResponse](req, s.config)
}

func (s *ExportService) AttachedItems(req *ExportAttachedItemsRequest) (*ExportAttachedItemsResponse, error) {
	req.method = "POST"
	req.path = "/exports/attached_items"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "attachedItems"

	return send[*ExportAttachedItemsResponse](req, s.config)
}

func (s *ExportService) DifferentialPrices(req *ExportDifferentialPricesRequest) (*ExportDifferentialPricesResponse, error) {
	req.method = "POST"
	req.path = "/exports/differential_prices"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "differentialPrices"

	return send[*ExportDifferentialPricesResponse](req, s.config)
}

func (s *ExportService) PriceVariants(req *ExportPriceVariantsRequest) (*ExportPriceVariantsResponse, error) {
	req.method = "POST"
	req.path = "/exports/price_variants"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "priceVariants"

	return send[*ExportPriceVariantsResponse](req, s.config)
}

func (s *ExportService) Ramps(req *ExportRampsRequest) (*ExportRampsResponse, error) {
	req.method = "POST"
	req.path = "/exports/ramps"
	req.isIdempotent = true
	req.telemetryResource = "export"
	req.telemetryOperation = "ramps"

	return send[*ExportRampsResponse](req, s.config)
}

func (s *ExportService) WaitForExportCompletion(exp Export) (Export, error) {
	count := 0
	for exp.Status == ExportStatusInProcess {
		if count > 30 {
			return exp, errors.New("Export is taking too long")
		}
		count++
		time.Sleep(ConfigExportWaitInSecs)
		response, err := s.Retrieve(&ExportRetrieveRequest{Id: exp.Id})
		if err != nil {
			return exp, err
		}
		exp = *response.Export
	}

	return exp, nil
}
