// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type ExportMimeType string

const (
	ExportMimeTypePdf ExportMimeType = "pdf"
	ExportMimeTypeZip ExportMimeType = "zip"
)

type ExportStatus string

const (
	ExportStatusInProcess ExportStatus = "in_process"
	ExportStatusCompleted ExportStatus = "completed"
	ExportStatusFailed    ExportStatus = "failed"
)

type Export struct {
	Id            string          `json:"id"`
	OperationType string          `json:"operation_type"`
	MimeType      ExportMimeType  `json:"mime_type"`
	Status        ExportStatus    `json:"status"`
	CreatedAt     int64           `json:"created_at"`
	Download      *ExportDownload `json:"download"`
	Object        string          `json:"object"`
}

type ExportDownload struct {
	DownloadUrl string `json:"download_url"`
	ValidTill   int64  `json:"valid_till"`
	MimeType    string `json:"mime_type"`
	Object      string `json:"object"`
}

type ExportRevenueRecognitionRequest struct {
	Invoice          *ExportRevenueRecognitionInvoice      `json:"invoice,omitempty"`
	Subscription     *ExportRevenueRecognitionSubscription `json:"subscription,omitempty"`
	Customer         *ExportRevenueRecognitionCustomer     `json:"customer,omitempty"`
	Relationship     *ExportRevenueRecognitionRelationship `json:"relationship,omitempty"`
	ReportBy         ReportBy                              `json:"report_by"`
	CurrencyCode     string                                `json:"currency_code,omitempty"`
	ReportFromMonth  *int32                                `json:"report_from_month"`
	ReportFromYear   *int32                                `json:"report_from_year"`
	ReportToMonth    *int32                                `json:"report_to_month"`
	ReportToYear     *int32                                `json:"report_to_year"`
	IncludeDiscounts *bool                                 `json:"include_discounts,omitempty"`
	PaymentOwner     *StringFilter                         `json:"payment_owner,omitempty"`
	ItemId           *StringFilter                         `json:"item_id,omitempty"`
	ItemPriceId      *StringFilter                         `json:"item_price_id,omitempty"`
	CancelReasonCode *StringFilter                         `json:"cancel_reason_code,omitempty"`
	BusinessEntityId *StringFilter                         `json:"business_entity_id,omitempty"`
	apiRequest       `json:"-" form:"-"`
}

func (r *ExportRevenueRecognitionRequest) payload() any { return r }

type ExportRevenueRecognitionInvoice struct {
	Id             *StringFilter    `json:"id,omitempty"`
	Recurring      *BooleanFilter   `json:"recurring,omitempty"`
	Status         *EnumFilter      `json:"status,omitempty"`
	PriceType      *EnumFilter      `json:"price_type,omitempty"`
	Date           *TimestampFilter `json:"date,omitempty"`
	PaidAt         *TimestampFilter `json:"paid_at,omitempty"`
	Total          *NumberFilter    `json:"total,omitempty"`
	AmountPaid     *NumberFilter    `json:"amount_paid,omitempty"`
	AmountAdjusted *NumberFilter    `json:"amount_adjusted,omitempty"`
	CreditsApplied *NumberFilter    `json:"credits_applied,omitempty"`
	AmountDue      *NumberFilter    `json:"amount_due,omitempty"`
	DunningStatus  *EnumFilter      `json:"dunning_status,omitempty"`
	UpdatedAt      *TimestampFilter `json:"updated_at,omitempty"`
	Channel        *EnumFilter      `json:"channel,omitempty"`
}

type ExportRevenueRecognitionSubscription struct {
	Id                     *StringFilter    `json:"id,omitempty"`
	CustomerId             *StringFilter    `json:"customer_id,omitempty"`
	Status                 *EnumFilter      `json:"status,omitempty"`
	CancelReason           *EnumFilter      `json:"cancel_reason,omitempty"`
	RemainingBillingCycles *NumberFilter    `json:"remaining_billing_cycles,omitempty"`
	CreatedAt              *TimestampFilter `json:"created_at,omitempty"`
	ActivatedAt            *TimestampFilter `json:"activated_at,omitempty"`
	NextBillingAt          *TimestampFilter `json:"next_billing_at,omitempty"`
	CancelledAt            *TimestampFilter `json:"cancelled_at,omitempty"`
	HasScheduledChanges    *BooleanFilter   `json:"has_scheduled_changes,omitempty"`
	UpdatedAt              *TimestampFilter `json:"updated_at,omitempty"`
	OfflinePaymentMethod   *EnumFilter      `json:"offline_payment_method,omitempty"`
	AutoCloseInvoices      *BooleanFilter   `json:"auto_close_invoices,omitempty"`
	Channel                *EnumFilter      `json:"channel,omitempty"`
	PlanId                 *StringFilter    `json:"plan_id,omitempty"`
}

type ExportRevenueRecognitionCustomer struct {
	Id                   *StringFilter    `json:"id,omitempty"`
	FirstName            *StringFilter    `json:"first_name,omitempty"`
	LastName             *StringFilter    `json:"last_name,omitempty"`
	Email                *StringFilter    `json:"email,omitempty"`
	Company              *StringFilter    `json:"company,omitempty"`
	Phone                *StringFilter    `json:"phone,omitempty"`
	AutoCollection       *EnumFilter      `json:"auto_collection,omitempty"`
	Taxability           *EnumFilter      `json:"taxability,omitempty"`
	CreatedAt            *TimestampFilter `json:"created_at,omitempty"`
	UpdatedAt            *TimestampFilter `json:"updated_at,omitempty"`
	OfflinePaymentMethod *EnumFilter      `json:"offline_payment_method,omitempty"`
	AutoCloseInvoices    *BooleanFilter   `json:"auto_close_invoices,omitempty"`
	Channel              *EnumFilter      `json:"channel,omitempty"`
}

type ExportRevenueRecognitionRelationship struct {
	ParentId       *StringFilter `json:"parent_id,omitempty"`
	PaymentOwnerId *StringFilter `json:"payment_owner_id,omitempty"`
	InvoiceOwnerId *StringFilter `json:"invoice_owner_id,omitempty"`
}

type ExportDeferredRevenueRequest struct {
	Invoice          *ExportDeferredRevenueInvoice      `json:"invoice,omitempty"`
	Subscription     *ExportDeferredRevenueSubscription `json:"subscription,omitempty"`
	Customer         *ExportDeferredRevenueCustomer     `json:"customer,omitempty"`
	Relationship     *ExportDeferredRevenueRelationship `json:"relationship,omitempty"`
	ReportBy         ReportBy                           `json:"report_by"`
	CurrencyCode     string                             `json:"currency_code,omitempty"`
	ReportFromMonth  *int32                             `json:"report_from_month"`
	ReportFromYear   *int32                             `json:"report_from_year"`
	ReportToMonth    *int32                             `json:"report_to_month"`
	ReportToYear     *int32                             `json:"report_to_year"`
	IncludeDiscounts *bool                              `json:"include_discounts,omitempty"`
	PaymentOwner     *StringFilter                      `json:"payment_owner,omitempty"`
	ItemId           *StringFilter                      `json:"item_id,omitempty"`
	ItemPriceId      *StringFilter                      `json:"item_price_id,omitempty"`
	CancelReasonCode *StringFilter                      `json:"cancel_reason_code,omitempty"`
	BusinessEntityId *StringFilter                      `json:"business_entity_id,omitempty"`
	apiRequest       `json:"-" form:"-"`
}

func (r *ExportDeferredRevenueRequest) payload() any { return r }

type ExportDeferredRevenueInvoice struct {
	Id             *StringFilter    `json:"id,omitempty"`
	Recurring      *BooleanFilter   `json:"recurring,omitempty"`
	Status         *EnumFilter      `json:"status,omitempty"`
	PriceType      *EnumFilter      `json:"price_type,omitempty"`
	Date           *TimestampFilter `json:"date,omitempty"`
	PaidAt         *TimestampFilter `json:"paid_at,omitempty"`
	Total          *NumberFilter    `json:"total,omitempty"`
	AmountPaid     *NumberFilter    `json:"amount_paid,omitempty"`
	AmountAdjusted *NumberFilter    `json:"amount_adjusted,omitempty"`
	CreditsApplied *NumberFilter    `json:"credits_applied,omitempty"`
	AmountDue      *NumberFilter    `json:"amount_due,omitempty"`
	DunningStatus  *EnumFilter      `json:"dunning_status,omitempty"`
	UpdatedAt      *TimestampFilter `json:"updated_at,omitempty"`
	Channel        *EnumFilter      `json:"channel,omitempty"`
}

type ExportDeferredRevenueSubscription struct {
	Id                     *StringFilter    `json:"id,omitempty"`
	CustomerId             *StringFilter    `json:"customer_id,omitempty"`
	Status                 *EnumFilter      `json:"status,omitempty"`
	CancelReason           *EnumFilter      `json:"cancel_reason,omitempty"`
	RemainingBillingCycles *NumberFilter    `json:"remaining_billing_cycles,omitempty"`
	CreatedAt              *TimestampFilter `json:"created_at,omitempty"`
	ActivatedAt            *TimestampFilter `json:"activated_at,omitempty"`
	NextBillingAt          *TimestampFilter `json:"next_billing_at,omitempty"`
	CancelledAt            *TimestampFilter `json:"cancelled_at,omitempty"`
	HasScheduledChanges    *BooleanFilter   `json:"has_scheduled_changes,omitempty"`
	UpdatedAt              *TimestampFilter `json:"updated_at,omitempty"`
	OfflinePaymentMethod   *EnumFilter      `json:"offline_payment_method,omitempty"`
	AutoCloseInvoices      *BooleanFilter   `json:"auto_close_invoices,omitempty"`
	Channel                *EnumFilter      `json:"channel,omitempty"`
	PlanId                 *StringFilter    `json:"plan_id,omitempty"`
}

type ExportDeferredRevenueCustomer struct {
	Id                   *StringFilter    `json:"id,omitempty"`
	FirstName            *StringFilter    `json:"first_name,omitempty"`
	LastName             *StringFilter    `json:"last_name,omitempty"`
	Email                *StringFilter    `json:"email,omitempty"`
	Company              *StringFilter    `json:"company,omitempty"`
	Phone                *StringFilter    `json:"phone,omitempty"`
	AutoCollection       *EnumFilter      `json:"auto_collection,omitempty"`
	Taxability           *EnumFilter      `json:"taxability,omitempty"`
	CreatedAt            *TimestampFilter `json:"created_at,omitempty"`
	UpdatedAt            *TimestampFilter `json:"updated_at,omitempty"`
	OfflinePaymentMethod *EnumFilter      `json:"offline_payment_method,omitempty"`
	AutoCloseInvoices    *BooleanFilter   `json:"auto_close_invoices,omitempty"`
	Channel              *EnumFilter      `json:"channel,omitempty"`
}

type ExportDeferredRevenueRelationship struct {
	ParentId       *StringFilter `json:"parent_id,omitempty"`
	PaymentOwnerId *StringFilter `json:"payment_owner_id,omitempty"`
	InvoiceOwnerId *StringFilter `json:"invoice_owner_id,omitempty"`
}

type ExportPlansRequest struct {
	Plan         *ExportPlansPlan `json:"plan,omitempty"`
	CurrencyCode *StringFilter    `json:"currency_code,omitempty"`
	apiRequest   `json:"-" form:"-"`
}

func (r *ExportPlansRequest) payload() any { return r }

type ExportPlansPlan struct {
	Id                 *StringFilter    `json:"id,omitempty"`
	Name               *StringFilter    `json:"name,omitempty"`
	Price              *NumberFilter    `json:"price,omitempty"`
	Period             *NumberFilter    `json:"period,omitempty"`
	PeriodUnit         *EnumFilter      `json:"period_unit,omitempty"`
	TrialPeriod        *NumberFilter    `json:"trial_period,omitempty"`
	TrialPeriodUnit    *EnumFilter      `json:"trial_period_unit,omitempty"`
	AddonApplicability *EnumFilter      `json:"addon_applicability,omitempty"`
	Giftable           *BooleanFilter   `json:"giftable,omitempty"`
	Status             *EnumFilter      `json:"status,omitempty"`
	UpdatedAt          *TimestampFilter `json:"updated_at,omitempty"`
	Channel            *EnumFilter      `json:"channel,omitempty"`
}

type ExportAddonsRequest struct {
	Addon        *ExportAddonsAddon `json:"addon,omitempty"`
	CurrencyCode *StringFilter      `json:"currency_code,omitempty"`
	apiRequest   `json:"-" form:"-"`
}

func (r *ExportAddonsRequest) payload() any { return r }

type ExportAddonsAddon struct {
	Id         *StringFilter    `json:"id,omitempty"`
	Name       *StringFilter    `json:"name,omitempty"`
	ChargeType *EnumFilter      `json:"charge_type,omitempty"`
	Price      *NumberFilter    `json:"price,omitempty"`
	Period     *NumberFilter    `json:"period,omitempty"`
	PeriodUnit *EnumFilter      `json:"period_unit,omitempty"`
	Status     *EnumFilter      `json:"status,omitempty"`
	UpdatedAt  *TimestampFilter `json:"updated_at,omitempty"`
	Channel    *EnumFilter      `json:"channel,omitempty"`
}

type ExportCouponsRequest struct {
	Coupon       *ExportCouponsCoupon `json:"coupon,omitempty"`
	CurrencyCode *StringFilter        `json:"currency_code,omitempty"`
	apiRequest   `json:"-" form:"-"`
}

func (r *ExportCouponsRequest) payload() any { return r }

type ExportCouponsCoupon struct {
	Id           *StringFilter    `json:"id,omitempty"`
	Name         *StringFilter    `json:"name,omitempty"`
	DiscountType *EnumFilter      `json:"discount_type,omitempty"`
	DurationType *EnumFilter      `json:"duration_type,omitempty"`
	Status       *EnumFilter      `json:"status,omitempty"`
	ApplyOn      *EnumFilter      `json:"apply_on,omitempty"`
	CreatedAt    *TimestampFilter `json:"created_at,omitempty"`
	UpdatedAt    *TimestampFilter `json:"updated_at,omitempty"`
}

type ExportCustomersRequest struct {
	Customer         *ExportCustomersCustomer     `json:"customer,omitempty"`
	Relationship     *ExportCustomersRelationship `json:"relationship,omitempty"`
	ExportType       ExportType                   `json:"export_type,omitempty"`
	BusinessEntityId *StringFilter                `json:"business_entity_id,omitempty"`
	apiRequest       `json:"-" form:"-"`
}

func (r *ExportCustomersRequest) payload() any { return r }

type ExportCustomersCustomer struct {
	Id                   *StringFilter    `json:"id,omitempty"`
	FirstName            *StringFilter    `json:"first_name,omitempty"`
	LastName             *StringFilter    `json:"last_name,omitempty"`
	Email                *StringFilter    `json:"email,omitempty"`
	Company              *StringFilter    `json:"company,omitempty"`
	Phone                *StringFilter    `json:"phone,omitempty"`
	AutoCollection       *EnumFilter      `json:"auto_collection,omitempty"`
	Taxability           *EnumFilter      `json:"taxability,omitempty"`
	CreatedAt            *TimestampFilter `json:"created_at,omitempty"`
	UpdatedAt            *TimestampFilter `json:"updated_at,omitempty"`
	OfflinePaymentMethod *EnumFilter      `json:"offline_payment_method,omitempty"`
	AutoCloseInvoices    *BooleanFilter   `json:"auto_close_invoices,omitempty"`
	Channel              *EnumFilter      `json:"channel,omitempty"`
}

type ExportCustomersRelationship struct {
	ParentId       *StringFilter `json:"parent_id,omitempty"`
	PaymentOwnerId *StringFilter `json:"payment_owner_id,omitempty"`
	InvoiceOwnerId *StringFilter `json:"invoice_owner_id,omitempty"`
}

type ExportSubscriptionsRequest struct {
	Subscription     *ExportSubscriptionsSubscription `json:"subscription,omitempty"`
	ExportType       ExportType                       `json:"export_type,omitempty"`
	ItemId           *StringFilter                    `json:"item_id,omitempty"`
	ItemPriceId      *StringFilter                    `json:"item_price_id,omitempty"`
	CancelReasonCode *StringFilter                    `json:"cancel_reason_code,omitempty"`
	apiRequest       `json:"-" form:"-"`
}

func (r *ExportSubscriptionsRequest) payload() any { return r }

type ExportSubscriptionsSubscription struct {
	Id                     *StringFilter    `json:"id,omitempty"`
	CustomerId             *StringFilter    `json:"customer_id,omitempty"`
	Status                 *EnumFilter      `json:"status,omitempty"`
	CancelReason           *EnumFilter      `json:"cancel_reason,omitempty"`
	RemainingBillingCycles *NumberFilter    `json:"remaining_billing_cycles,omitempty"`
	CreatedAt              *TimestampFilter `json:"created_at,omitempty"`
	ActivatedAt            *TimestampFilter `json:"activated_at,omitempty"`
	NextBillingAt          *TimestampFilter `json:"next_billing_at,omitempty"`
	CancelledAt            *TimestampFilter `json:"cancelled_at,omitempty"`
	HasScheduledChanges    *BooleanFilter   `json:"has_scheduled_changes,omitempty"`
	UpdatedAt              *TimestampFilter `json:"updated_at,omitempty"`
	OfflinePaymentMethod   *EnumFilter      `json:"offline_payment_method,omitempty"`
	AutoCloseInvoices      *BooleanFilter   `json:"auto_close_invoices,omitempty"`
	Channel                *EnumFilter      `json:"channel,omitempty"`
	PlanId                 *StringFilter    `json:"plan_id,omitempty"`
}

type ExportInvoicesRequest struct {
	Invoice      *ExportInvoicesInvoice `json:"invoice,omitempty"`
	PaymentOwner *StringFilter          `json:"payment_owner,omitempty"`
	apiRequest   `json:"-" form:"-"`
}

func (r *ExportInvoicesRequest) payload() any { return r }

type ExportInvoicesInvoice struct {
	Id             *StringFilter    `json:"id,omitempty"`
	SubscriptionId *StringFilter    `json:"subscription_id,omitempty"`
	CustomerId     *StringFilter    `json:"customer_id,omitempty"`
	Recurring      *BooleanFilter   `json:"recurring,omitempty"`
	Status         *EnumFilter      `json:"status,omitempty"`
	PriceType      *EnumFilter      `json:"price_type,omitempty"`
	Date           *TimestampFilter `json:"date,omitempty"`
	PaidAt         *TimestampFilter `json:"paid_at,omitempty"`
	Total          *NumberFilter    `json:"total,omitempty"`
	AmountPaid     *NumberFilter    `json:"amount_paid,omitempty"`
	AmountAdjusted *NumberFilter    `json:"amount_adjusted,omitempty"`
	CreditsApplied *NumberFilter    `json:"credits_applied,omitempty"`
	AmountDue      *NumberFilter    `json:"amount_due,omitempty"`
	DunningStatus  *EnumFilter      `json:"dunning_status,omitempty"`
	UpdatedAt      *TimestampFilter `json:"updated_at,omitempty"`
	Channel        *EnumFilter      `json:"channel,omitempty"`
}

type ExportCreditNotesRequest struct {
	CreditNote *ExportCreditNotesCreditNote `json:"credit_note,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *ExportCreditNotesRequest) payload() any { return r }

type ExportCreditNotesCreditNote struct {
	Id                 *StringFilter    `json:"id,omitempty"`
	CustomerId         *StringFilter    `json:"customer_id,omitempty"`
	SubscriptionId     *StringFilter    `json:"subscription_id,omitempty"`
	ReferenceInvoiceId *StringFilter    `json:"reference_invoice_id,omitempty"`
	Type               *EnumFilter      `json:"type,omitempty"`
	ReasonCode         *EnumFilter      `json:"reason_code,omitempty"`
	CreateReasonCode   *StringFilter    `json:"create_reason_code,omitempty"`
	Status             *EnumFilter      `json:"status,omitempty"`
	Date               *TimestampFilter `json:"date,omitempty"`
	Total              *NumberFilter    `json:"total,omitempty"`
	PriceType          *EnumFilter      `json:"price_type,omitempty"`
	AmountAllocated    *NumberFilter    `json:"amount_allocated,omitempty"`
	AmountRefunded     *NumberFilter    `json:"amount_refunded,omitempty"`
	AmountAvailable    *NumberFilter    `json:"amount_available,omitempty"`
	VoidedAt           *TimestampFilter `json:"voided_at,omitempty"`
	UpdatedAt          *TimestampFilter `json:"updated_at,omitempty"`
	Channel            *EnumFilter      `json:"channel,omitempty"`
}

type ExportTransactionsRequest struct {
	Transaction *ExportTransactionsTransaction `json:"transaction,omitempty"`
	apiRequest  `json:"-" form:"-"`
}

func (r *ExportTransactionsRequest) payload() any { return r }

type ExportTransactionsTransaction struct {
	Id               *StringFilter    `json:"id,omitempty"`
	CustomerId       *StringFilter    `json:"customer_id,omitempty"`
	SubscriptionId   *StringFilter    `json:"subscription_id,omitempty"`
	PaymentSourceId  *StringFilter    `json:"payment_source_id,omitempty"`
	PaymentMethod    *EnumFilter      `json:"payment_method,omitempty"`
	Gateway          *EnumFilter      `json:"gateway,omitempty"`
	GatewayAccountId *StringFilter    `json:"gateway_account_id,omitempty"`
	IdAtGateway      *StringFilter    `json:"id_at_gateway,omitempty"`
	ReferenceNumber  *StringFilter    `json:"reference_number,omitempty"`
	Type             *EnumFilter      `json:"type,omitempty"`
	Date             *TimestampFilter `json:"date,omitempty"`
	Amount           *NumberFilter    `json:"amount,omitempty"`
	AmountCapturable *NumberFilter    `json:"amount_capturable,omitempty"`
	Status           *EnumFilter      `json:"status,omitempty"`
	UpdatedAt        *TimestampFilter `json:"updated_at,omitempty"`
}

type ExportOrdersRequest struct {
	Order      *ExportOrdersOrder `json:"order,omitempty"`
	Total      *NumberFilter      `json:"total,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *ExportOrdersRequest) payload() any { return r }

type ExportOrdersOrder struct {
	Id                      *StringFilter    `json:"id,omitempty"`
	SubscriptionId          *StringFilter    `json:"subscription_id,omitempty"`
	CustomerId              *StringFilter    `json:"customer_id,omitempty"`
	Status                  *EnumFilter      `json:"status,omitempty"`
	PriceType               *EnumFilter      `json:"price_type,omitempty"`
	OrderDate               *TimestampFilter `json:"order_date,omitempty"`
	ShippingDate            *TimestampFilter `json:"shipping_date,omitempty"`
	ShippedAt               *TimestampFilter `json:"shipped_at,omitempty"`
	DeliveredAt             *TimestampFilter `json:"delivered_at,omitempty"`
	CancelledAt             *TimestampFilter `json:"cancelled_at,omitempty"`
	AmountPaid              *NumberFilter    `json:"amount_paid,omitempty"`
	RefundableCredits       *NumberFilter    `json:"refundable_credits,omitempty"`
	RefundableCreditsIssued *NumberFilter    `json:"refundable_credits_issued,omitempty"`
	UpdatedAt               *TimestampFilter `json:"updated_at,omitempty"`
	ResentStatus            *EnumFilter      `json:"resent_status,omitempty"`
	IsResent                *BooleanFilter   `json:"is_resent,omitempty"`
	OriginalOrderId         *StringFilter    `json:"original_order_id,omitempty"`
}

type ExportItemFamiliesRequest struct {
	ItemFamily                *ExportItemFamiliesItemFamily `json:"item_family,omitempty"`
	BusinessEntityId          *StringFilter                 `json:"business_entity_id,omitempty"`
	IncludeSiteLevelResources *BooleanFilter                `json:"include_site_level_resources,omitempty"`
	apiRequest                `json:"-" form:"-"`
}

func (r *ExportItemFamiliesRequest) payload() any { return r }

type ExportItemFamiliesItemFamily struct {
	Id        *StringFilter    `json:"id,omitempty"`
	Name      *StringFilter    `json:"name,omitempty"`
	UpdatedAt *TimestampFilter `json:"updated_at,omitempty"`
}

type ExportItemsRequest struct {
	Item                      *ExportItemsItem `json:"item,omitempty"`
	BusinessEntityId          *StringFilter    `json:"business_entity_id,omitempty"`
	IncludeSiteLevelResources *BooleanFilter   `json:"include_site_level_resources,omitempty"`
	apiRequest                `json:"-" form:"-"`
}

func (r *ExportItemsRequest) payload() any { return r }

type ExportItemsItem struct {
	Id                 *StringFilter    `json:"id,omitempty"`
	ItemFamilyId       *StringFilter    `json:"item_family_id,omitempty"`
	Type               *EnumFilter      `json:"type,omitempty"`
	Name               *StringFilter    `json:"name,omitempty"`
	ItemApplicability  *EnumFilter      `json:"item_applicability,omitempty"`
	Status             *EnumFilter      `json:"status,omitempty"`
	IsGiftable         *BooleanFilter   `json:"is_giftable,omitempty"`
	UpdatedAt          *TimestampFilter `json:"updated_at,omitempty"`
	EnabledForCheckout *BooleanFilter   `json:"enabled_for_checkout,omitempty"`
	EnabledInPortal    *BooleanFilter   `json:"enabled_in_portal,omitempty"`
	Metered            *BooleanFilter   `json:"metered,omitempty"`
	UsageCalculation   *EnumFilter      `json:"usage_calculation,omitempty"`
	Channel            *EnumFilter      `json:"channel,omitempty"`
}

type ExportItemPricesRequest struct {
	ItemPrice                 *ExportItemPricesItemPrice `json:"item_price,omitempty"`
	ItemFamilyId              *StringFilter              `json:"item_family_id,omitempty"`
	ItemType                  *EnumFilter                `json:"item_type,omitempty"`
	CurrencyCode              *StringFilter              `json:"currency_code,omitempty"`
	BusinessEntityId          *StringFilter              `json:"business_entity_id,omitempty"`
	IncludeSiteLevelResources *BooleanFilter             `json:"include_site_level_resources,omitempty"`
	apiRequest                `json:"-" form:"-"`
}

func (r *ExportItemPricesRequest) payload() any { return r }

type ExportItemPricesItemPrice struct {
	Id              *StringFilter    `json:"id,omitempty"`
	Name            *StringFilter    `json:"name,omitempty"`
	PricingModel    *EnumFilter      `json:"pricing_model,omitempty"`
	ItemId          *StringFilter    `json:"item_id,omitempty"`
	PriceVariantId  *StringFilter    `json:"price_variant_id,omitempty"`
	TrialPeriod     *NumberFilter    `json:"trial_period,omitempty"`
	TrialPeriodUnit *EnumFilter      `json:"trial_period_unit,omitempty"`
	Status          *EnumFilter      `json:"status,omitempty"`
	UpdatedAt       *TimestampFilter `json:"updated_at,omitempty"`
	PeriodUnit      *EnumFilter      `json:"period_unit,omitempty"`
	Period          *NumberFilter    `json:"period,omitempty"`
	Channel         *EnumFilter      `json:"channel,omitempty"`
}

type ExportAttachedItemsRequest struct {
	AttachedItem *ExportAttachedItemsAttachedItem `json:"attached_item,omitempty"`
	ItemType     *EnumFilter                      `json:"item_type,omitempty"`
	apiRequest   `json:"-" form:"-"`
}

func (r *ExportAttachedItemsRequest) payload() any { return r }

type ExportAttachedItemsAttachedItem struct {
	Id            *StringFilter    `json:"id,omitempty"`
	ItemId        *StringFilter    `json:"item_id,omitempty"`
	Type          *EnumFilter      `json:"type,omitempty"`
	ChargeOnEvent *EnumFilter      `json:"charge_on_event,omitempty"`
	UpdatedAt     *TimestampFilter `json:"updated_at,omitempty"`
	ParentItemId  *StringFilter    `json:"parent_item_id,omitempty"`
}

type ExportDifferentialPricesRequest struct {
	DifferentialPrice *ExportDifferentialPricesDifferentialPrice `json:"differential_price,omitempty"`
	ItemId            *StringFilter                              `json:"item_id,omitempty"`
	apiRequest        `json:"-" form:"-"`
}

func (r *ExportDifferentialPricesRequest) payload() any { return r }

type ExportDifferentialPricesDifferentialPrice struct {
	ItemPriceId  *StringFilter `json:"item_price_id,omitempty"`
	Id           *StringFilter `json:"id,omitempty"`
	ParentItemId *StringFilter `json:"parent_item_id,omitempty"`
}

type ExportPriceVariantsRequest struct {
	PriceVariant              *ExportPriceVariantsPriceVariant `json:"price_variant,omitempty"`
	BusinessEntityId          *StringFilter                    `json:"business_entity_id,omitempty"`
	IncludeSiteLevelResources *BooleanFilter                   `json:"include_site_level_resources,omitempty"`
	apiRequest                `json:"-" form:"-"`
}

func (r *ExportPriceVariantsRequest) payload() any { return r }

type ExportPriceVariantsPriceVariant struct {
	Id        *StringFilter    `json:"id,omitempty"`
	Name      *StringFilter    `json:"name,omitempty"`
	Status    *EnumFilter      `json:"status,omitempty"`
	UpdatedAt *TimestampFilter `json:"updated_at,omitempty"`
	CreatedAt *TimestampFilter `json:"created_at,omitempty"`
}

type ExportRetrieveResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportRevenueRecognitionResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportDeferredRevenueResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportPlansResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportAddonsResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportCouponsResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportCustomersResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportSubscriptionsResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportInvoicesResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportCreditNotesResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportTransactionsResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportOrdersResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportItemFamiliesResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportItemsResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportItemPricesResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportAttachedItemsResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportDifferentialPricesResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}

type ExportPriceVariantsResponse struct {
	Export *Export `json:"export,omitempty"`
	apiResponse
}
