// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type FeatureStatus string

const (
	FeatureStatusActive   FeatureStatus = "active"
	FeatureStatusArchived FeatureStatus = "archived"
	FeatureStatusDraft    FeatureStatus = "draft"
)

type FeatureType string

const (
	FeatureTypeSwitch   FeatureType = "switch"
	FeatureTypeCustom   FeatureType = "custom"
	FeatureTypeQuantity FeatureType = "quantity"
	FeatureTypeRange    FeatureType = "range"
)

type Feature struct {
	Id              string          `json:"id"`
	Name            string          `json:"name"`
	Description     string          `json:"description"`
	Status          FeatureStatus   `json:"status"`
	Type            FeatureType     `json:"type"`
	Unit            string          `json:"unit"`
	ResourceVersion int64           `json:"resource_version"`
	UpdatedAt       int64           `json:"updated_at"`
	CreatedAt       int64           `json:"created_at"`
	Levels          []*FeatureLevel `json:"levels"`
	CustomFields    *customFields   `json:"-"`
	Object          string          `json:"object"`
}

func (r *Feature) setCustomFields(cf *customFields) { r.CustomFields = cf }

func (r *Feature) UnmarshalJSON(data []byte) error {
	type Alias Feature
	return unmarshalObjectWithCustomField(data, r, (*Alias)(r))
}

type FeatureLevel struct {
	Name        string `json:"name"`
	Value       string `json:"value"`
	Level       int32  `json:"level"`
	IsUnlimited bool   `json:"is_unlimited"`
	Object      string `json:"object"`
}

type FeatureListRequest struct {
	Limit      *int32        `json:"limit,omitempty"`
	Offset     string        `json:"offset,omitempty"`
	Name       *StringFilter `json:"name,omitempty"`
	Id         *StringFilter `json:"id,omitempty"`
	Status     *EnumFilter   `json:"status,omitempty"`
	Type       *EnumFilter   `json:"type,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *FeatureListRequest) payload() any { return r }

type FeatureCreateRequest struct {
	Id          string                `json:"id,omitempty"`
	Name        string                `json:"name"`
	Description string                `json:"description,omitempty"`
	Type        FeatureType           `json:"type,omitempty"`
	Unit        string                `json:"unit,omitempty"`
	Levels      []*FeatureCreateLevel `json:"levels,omitempty"`
	apiRequest  `json:"-" form:"-"`
}

func (r *FeatureCreateRequest) payload() any { return r }

type FeatureCreateLevel struct {
	Name        string `json:"name,omitempty"`
	Value       string `json:"value,omitempty"`
	IsUnlimited *bool  `json:"is_unlimited,omitempty"`
	Level       *int32 `json:"level,omitempty"`
}

type FeatureUpdateRequest struct {
	Name        string                `json:"name,omitempty"`
	Description string                `json:"description,omitempty"`
	Unit        string                `json:"unit,omitempty"`
	Levels      []*FeatureUpdateLevel `json:"levels,omitempty"`
	apiRequest  `json:"-" form:"-"`
}

func (r *FeatureUpdateRequest) payload() any { return r }

type FeatureUpdateLevel struct {
	Name        string `json:"name,omitempty"`
	Value       string `json:"value,omitempty"`
	IsUnlimited *bool  `json:"is_unlimited,omitempty"`
	Level       *int32 `json:"level,omitempty"`
}

type FeatureListFeatureResponse struct {
	Feature *Feature `json:"feature,omitempty"`
}

type FeatureListResponse struct {
	List       []*FeatureListFeatureResponse `json:"list,omitempty"`
	NextOffset string                        `json:"next_offset,omitempty"`
	apiResponse
}

type FeatureCreateResponse struct {
	Feature *Feature `json:"feature,omitempty"`
	apiResponse
}

type FeatureUpdateResponse struct {
	Feature *Feature `json:"feature,omitempty"`
	apiResponse
}

type FeatureRetrieveResponse struct {
	Feature *Feature `json:"feature,omitempty"`
	apiResponse
}

type FeatureDeleteResponse struct {
	Feature *Feature `json:"feature,omitempty"`
	apiResponse
}

type FeatureActivateResponse struct {
	Feature *Feature `json:"feature,omitempty"`
	apiResponse
}

type FeatureArchiveResponse struct {
	Feature *Feature `json:"feature,omitempty"`
	apiResponse
}

type FeatureReactivateResponse struct {
	Feature *Feature `json:"feature,omitempty"`
	apiResponse
}
