// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type FilterConditionField string

const (
	FilterConditionFieldPlanPriceId FilterConditionField = "plan_price_id"
)

type FilterConditionOperator string

const (
	FilterConditionOperatorEquals    FilterConditionOperator = "equals"
	FilterConditionOperatorNotEquals FilterConditionOperator = "not_equals"
)

type FilterCondition struct {
	Field    FilterConditionField    `json:"field"`
	Operator FilterConditionOperator `json:"operator"`
	Value    string                  `json:"value"`
	Object   string                  `json:"object"`
}
