// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type ImpactedCustomer struct {
	ActionType string                    `json:"action_type"`
	Download   *ImpactedCustomerDownload `json:"download"`
	Object     string                    `json:"object"`
}

type ImpactedCustomerDownload struct {
	DownloadUrl string `json:"download_url"`
	ValidTill   int64  `json:"valid_till"`
	MimeType    string `json:"mime_type"`
	Object      string `json:"object"`
}
