// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type ItemPriceService struct {
	config *ClientConfig
}

func (s *ItemPriceService) Create(req *ItemPriceCreateRequest) (*ItemPriceCreateResponse, error) {
	req.method = "POST"
	req.path = "/item_prices"
	req.isIdempotent = true
	req.telemetryResource = "itemPrice"
	req.telemetryOperation = "create"

	return send[*ItemPriceCreateResponse](req, s.config)
}

func (s *ItemPriceService) Retrieve(req *ItemPriceRetrieveRequest) (*ItemPriceRetrieveResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/item_prices/%v", url.PathEscape(req.Id))
	req.telemetryResource = "itemPrice"
	req.telemetryOperation = "retrieve"

	return send[*ItemPriceRetrieveResponse](req, s.config)
}

func (s *ItemPriceService) Update(id string, req *ItemPriceUpdateRequest) (*ItemPriceUpdateResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/item_prices/%v", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "itemPrice"
	req.telemetryOperation = "update"

	return send[*ItemPriceUpdateResponse](req, s.config)
}

func (s *ItemPriceService) List(req *ItemPriceListRequest) (*ItemPriceListResponse, error) {
	req.method = "GET"
	req.path = "/item_prices"
	req.isListRequest = true
	req.telemetryResource = "itemPrice"
	req.telemetryOperation = "list"

	return send[*ItemPriceListResponse](req, s.config)
}

func (s *ItemPriceService) Delete(req *ItemPriceDeleteRequest) (*ItemPriceDeleteResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/item_prices/%v/delete", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "itemPrice"
	req.telemetryOperation = "delete"

	return send[*ItemPriceDeleteResponse](req, s.config)
}

func (s *ItemPriceService) FindApplicableItems(id string, req *ItemPriceFindApplicableItemsRequest) (*ItemPriceFindApplicableItemsResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/item_prices/%v/applicable_items", url.PathEscape(id))
	req.isListRequest = true
	req.telemetryResource = "itemPrice"
	req.telemetryOperation = "findApplicableItems"

	return send[*ItemPriceFindApplicableItemsResponse](req, s.config)
}

func (s *ItemPriceService) FindApplicableItemPrices(id string, req *ItemPriceFindApplicableItemPricesRequest) (*ItemPriceFindApplicableItemPricesResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/item_prices/%v/applicable_item_prices", url.PathEscape(id))
	req.isListRequest = true
	req.telemetryResource = "itemPrice"
	req.telemetryOperation = "findApplicableItemPrices"

	return send[*ItemPriceFindApplicableItemPricesResponse](req, s.config)
}
