// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type ItemFamilyStatus string

const (
	ItemFamilyStatusActive  ItemFamilyStatus = "active"
	ItemFamilyStatusDeleted ItemFamilyStatus = "deleted"
)

type ItemFamily struct {
	Id               string           `json:"id"`
	Name             string           `json:"name"`
	Description      string           `json:"description"`
	Status           ItemFamilyStatus `json:"status"`
	ResourceVersion  int64            `json:"resource_version"`
	UpdatedAt        int64            `json:"updated_at"`
	Channel          Channel          `json:"channel"`
	BusinessEntityId string           `json:"business_entity_id"`
	Deleted          bool             `json:"deleted"`
	CustomField      CustomField      `json:"custom_field"`
	Object           string           `json:"object"`
}

type ItemFamilyCreateRequest struct {
	Id               string `json:"id"`
	Name             string `json:"name"`
	Description      string `json:"description,omitempty"`
	BusinessEntityId string `json:"business_entity_id,omitempty"`
	apiRequest       `json:"-" form:"-"`
}

func (r *ItemFamilyCreateRequest) payload() any { return r }

type ItemFamilyListRequest struct {
	Limit                     *int32           `json:"limit,omitempty"`
	Offset                    string           `json:"offset,omitempty"`
	Id                        *StringFilter    `json:"id,omitempty"`
	Name                      *StringFilter    `json:"name,omitempty"`
	UpdatedAt                 *TimestampFilter `json:"updated_at,omitempty"`
	BusinessEntityId          *StringFilter    `json:"business_entity_id,omitempty"`
	IncludeSiteLevelResources *BooleanFilter   `json:"include_site_level_resources,omitempty"`
	apiRequest                `json:"-" form:"-"`
}

func (r *ItemFamilyListRequest) payload() any { return r }

type ItemFamilyUpdateRequest struct {
	Name        string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	apiRequest  `json:"-" form:"-"`
}

func (r *ItemFamilyUpdateRequest) payload() any { return r }

type ItemFamilyCreateResponse struct {
	ItemFamily *ItemFamily `json:"item_family,omitempty"`
	apiResponse
}

type ItemFamilyRetrieveResponse struct {
	ItemFamily *ItemFamily `json:"item_family,omitempty"`
	apiResponse
}

type ItemFamilyListItemFamilyResponse struct {
	ItemFamily *ItemFamily `json:"item_family,omitempty"`
}

type ItemFamilyListResponse struct {
	List       []*ItemFamilyListItemFamilyResponse `json:"list,omitempty"`
	NextOffset string                              `json:"next_offset,omitempty"`
	apiResponse
}

type ItemFamilyUpdateResponse struct {
	ItemFamily *ItemFamily `json:"item_family,omitempty"`
	apiResponse
}

type ItemFamilyDeleteResponse struct {
	ItemFamily *ItemFamily `json:"item_family,omitempty"`
	apiResponse
}
