// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type LedgerAccountBalanceUnitType string

const (
	LedgerAccountBalanceUnitTypeCreditUnit LedgerAccountBalanceUnitType = "credit_unit"
)

type LedgerAccountBalance struct {
	SubscriptionId     string                                  `json:"subscription_id"`
	UnitId             string                                  `json:"unit_id"`
	UnitType           LedgerAccountBalanceUnitType            `json:"unit_type"`
	ModifiedAt         int64                                   `json:"modified_at"`
	ProvisionedBalance *LedgerAccountBalanceProvisionedBalance `json:"provisioned_balance"`
	OverdraftBalance   *LedgerAccountBalanceOverdraftBalance   `json:"overdraft_balance"`
	Object             string                                  `json:"object"`
}

type LedgerAccountBalanceProvisionedBalance struct {
	TotalBalance  string `json:"total_balance"`
	UsableBalance string `json:"usable_balance"`
	HoldAmount    string `json:"hold_amount"`
	Object        string `json:"object"`
}

type LedgerAccountBalanceOverdraftBalance struct {
	IsUnlimited   bool   `json:"is_unlimited"`
	Limit         string `json:"limit"`
	TotalBalance  string `json:"total_balance"`
	UsableBalance string `json:"usable_balance"`
	UsedAmount    string `json:"used_amount"`
	HoldAmount    string `json:"hold_amount"`
	Object        string `json:"object"`
}

type LedgerAccountBalanceListLedgerAccountBalancesRequest struct {
	Limit          *int32        `json:"limit,omitempty"`
	Offset         string        `json:"offset,omitempty"`
	SubscriptionId *StringFilter `json:"subscription_id"`
	UnitId         *StringFilter `json:"unit_id,omitempty"`
	apiRequest     `json:"-" form:"-"`
}

func (r *LedgerAccountBalanceListLedgerAccountBalancesRequest) payload() any { return r }

type LedgerAccountBalanceListLedgerAccountBalancesLedgerAccountBalanceResponse struct {
	LedgerAccountBalance *LedgerAccountBalance `json:"ledger_account_balance,omitempty"`
}

type LedgerAccountBalanceListLedgerAccountBalancesResponse struct {
	List       []*LedgerAccountBalanceListLedgerAccountBalancesLedgerAccountBalanceResponse `json:"list,omitempty"`
	NextOffset string                                                                       `json:"next_offset,omitempty"`
	apiResponse
}
