// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type LedgerOperationService struct {
	config *ClientConfig
}

func (s *LedgerOperationService) RetrieveLedgerOperation(req *LedgerOperationRetrieveLedgerOperationRequest) (*LedgerOperationRetrieveLedgerOperationResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/ledger_operations/%v", url.PathEscape(req.Id))
	req.telemetryResource = "ledgerOperation"
	req.telemetryOperation = "retrieveLedgerOperation"

	return send[*LedgerOperationRetrieveLedgerOperationResponse](req, s.config)
}

func (s *LedgerOperationService) ListLedgerOperations(req *LedgerOperationListLedgerOperationsRequest) (*LedgerOperationListLedgerOperationsResponse, error) {
	req.method = "GET"
	req.path = "/ledger_operations"
	req.isListRequest = true
	req.telemetryResource = "ledgerOperation"
	req.telemetryOperation = "listLedgerOperations"

	return send[*LedgerOperationListLedgerOperationsResponse](req, s.config)
}

func (s *LedgerOperationService) Capture(req *LedgerOperationCaptureRequest) (*LedgerOperationCaptureResponse, error) {
	req.method = "POST"
	req.path = "/ledger_operations/capture"
	req.isJsonRequest = true
	req.telemetryResource = "ledgerOperation"
	req.telemetryOperation = "capture"

	return send[*LedgerOperationCaptureResponse](req, s.config)
}

func (s *LedgerOperationService) Authorize(req *LedgerOperationAuthorizeRequest) (*LedgerOperationAuthorizeResponse, error) {
	req.method = "POST"
	req.path = "/ledger_operations/authorize"
	req.isJsonRequest = true
	req.telemetryResource = "ledgerOperation"
	req.telemetryOperation = "authorize"

	return send[*LedgerOperationAuthorizeResponse](req, s.config)
}

func (s *LedgerOperationService) CaptureAuthorization(req *LedgerOperationCaptureAuthorizationRequest) (*LedgerOperationCaptureAuthorizationResponse, error) {
	req.method = "POST"
	req.path = "/ledger_operations/capture_authorization"
	req.isJsonRequest = true
	req.telemetryResource = "ledgerOperation"
	req.telemetryOperation = "captureAuthorization"

	return send[*LedgerOperationCaptureAuthorizationResponse](req, s.config)
}

func (s *LedgerOperationService) ReleaseAuthorization(req *LedgerOperationReleaseAuthorizationRequest) (*LedgerOperationReleaseAuthorizationResponse, error) {
	req.method = "POST"
	req.path = "/ledger_operations/release_authorization"
	req.isJsonRequest = true
	req.telemetryResource = "ledgerOperation"
	req.telemetryOperation = "releaseAuthorization"

	return send[*LedgerOperationReleaseAuthorizationResponse](req, s.config)
}

func (s *LedgerOperationService) Allocate(req *LedgerOperationAllocateRequest) (*LedgerOperationAllocateResponse, error) {
	req.method = "POST"
	req.path = "/ledger_operations/allocate"
	req.isJsonRequest = true
	req.telemetryResource = "ledgerOperation"
	req.telemetryOperation = "allocate"

	return send[*LedgerOperationAllocateResponse](req, s.config)
}
