// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

import (
	"encoding/json"
)

type LedgerOperationUnitType string

const (
	LedgerOperationUnitTypeCreditUnit LedgerOperationUnitType = "credit_unit"
)

type LedgerOperationType string

const (
	LedgerOperationTypeAllocation           LedgerOperationType = "allocation"
	LedgerOperationTypeCapture              LedgerOperationType = "capture"
	LedgerOperationTypeAuthorize            LedgerOperationType = "authorize"
	LedgerOperationTypeReleaseAuthorization LedgerOperationType = "release_authorization"
	LedgerOperationTypeCaptureAuthorization LedgerOperationType = "capture_authorization"
	LedgerOperationTypeExpiry               LedgerOperationType = "expiry"
	LedgerOperationTypeVoid                 LedgerOperationType = "void"
	LedgerOperationTypeRollover             LedgerOperationType = "rollover"
	LedgerOperationTypeAdjustment           LedgerOperationType = "adjustment"
)

type LedgerOperation struct {
	Id                       string                  `json:"id"`
	SubscriptionId           string                  `json:"subscription_id"`
	UnitId                   string                  `json:"unit_id"`
	UnitType                 LedgerOperationUnitType `json:"unit_type"`
	Type                     LedgerOperationType     `json:"type"`
	Amount                   string                  `json:"amount"`
	ProvisionedStartBalance  string                  `json:"provisioned_start_balance"`
	ProvisionedEndBalance    string                  `json:"provisioned_end_balance"`
	OverdraftStartBalance    string                  `json:"overdraft_start_balance"`
	OverdraftEndBalance      string                  `json:"overdraft_end_balance"`
	ParentLedgerOperationId  string                  `json:"parent_ledger_operation_id"`
	LedgerOperationTimestamp int64                   `json:"ledger_operation_timestamp"`
	AutoReleaseTimestamp     int64                   `json:"auto_release_timestamp"`
	CreatedAt                int64                   `json:"created_at"`
	ModifiedAt               int64                   `json:"modified_at"`
	Metadata                 json.RawMessage         `json:"metadata"`
	Object                   string                  `json:"object"`
}

type LedgerOperationListLedgerOperationsRequest struct {
	Limit          *int32           `json:"limit,omitempty"`
	Offset         string           `json:"offset,omitempty"`
	SubscriptionId *StringFilter    `json:"subscription_id"`
	UnitId         *StringFilter    `json:"unit_id,omitempty"`
	CreatedAt      *TimestampFilter `json:"created_at,omitempty"`
	Type           *EnumFilter      `json:"type,omitempty"`
	SortBy         *SortFilter      `json:"sort_by,omitempty"`
	apiRequest     `json:"-" form:"-"`
}

func (r *LedgerOperationListLedgerOperationsRequest) payload() any { return r }

type LedgerOperationCaptureRequest struct {
	Id                       string                 `json:"id,omitempty"`
	SubscriptionId           string                 `json:"subscription_id"`
	UnitId                   string                 `json:"unit_id"`
	Amount                   string                 `json:"amount"`
	LedgerOperationTimestamp *int64                 `json:"ledger_operation_timestamp"`
	Metadata                 map[string]interface{} `json:"metadata,omitempty"`
	apiRequest               `json:"-" form:"-"`
}

func (r *LedgerOperationCaptureRequest) payload() any { return r }

type LedgerOperationAuthorizeRequest struct {
	Id                       string                 `json:"id,omitempty"`
	SubscriptionId           string                 `json:"subscription_id"`
	UnitId                   string                 `json:"unit_id"`
	Amount                   string                 `json:"amount"`
	LedgerOperationTimestamp *int64                 `json:"ledger_operation_timestamp"`
	AutoReleaseTimestamp     *int64                 `json:"auto_release_timestamp,omitempty"`
	Metadata                 map[string]interface{} `json:"metadata,omitempty"`
	apiRequest               `json:"-" form:"-"`
}

func (r *LedgerOperationAuthorizeRequest) payload() any { return r }

type LedgerOperationCaptureAuthorizationRequest struct {
	AuthorizationId          string                 `json:"authorization_id"`
	Id                       string                 `json:"id,omitempty"`
	Amount                   string                 `json:"amount"`
	LedgerOperationTimestamp *int64                 `json:"ledger_operation_timestamp"`
	Metadata                 map[string]interface{} `json:"metadata,omitempty"`
	apiRequest               `json:"-" form:"-"`
}

func (r *LedgerOperationCaptureAuthorizationRequest) payload() any { return r }

type LedgerOperationReleaseAuthorizationRequest struct {
	AuthorizationId          string                 `json:"authorization_id"`
	Id                       string                 `json:"id,omitempty"`
	LedgerOperationTimestamp *int64                 `json:"ledger_operation_timestamp"`
	Metadata                 map[string]interface{} `json:"metadata,omitempty"`
	apiRequest               `json:"-" form:"-"`
}

func (r *LedgerOperationReleaseAuthorizationRequest) payload() any { return r }

type LedgerOperationAllocateRequest struct {
	SubscriptionId string                 `json:"subscription_id"`
	UnitId         string                 `json:"unit_id"`
	Amount         string                 `json:"amount"`
	ExpiresAt      *int64                 `json:"expires_at"`
	Metadata       map[string]interface{} `json:"metadata,omitempty"`
	apiRequest     `json:"-" form:"-"`
}

func (r *LedgerOperationAllocateRequest) payload() any { return r }

type LedgerOperationRetrieveLedgerOperationResponse struct {
	LedgerOperation *LedgerOperation `json:"ledger_operation,omitempty"`
	apiResponse
}

type LedgerOperationListLedgerOperationsLedgerOperationResponse struct {
	LedgerOperation *LedgerOperation `json:"ledger_operation,omitempty"`
}

type LedgerOperationListLedgerOperationsResponse struct {
	List       []*LedgerOperationListLedgerOperationsLedgerOperationResponse `json:"list,omitempty"`
	NextOffset string                                                        `json:"next_offset,omitempty"`
	apiResponse
}

type LedgerOperationCaptureResponse struct {
	LedgerOperation      *LedgerOperation     `json:"ledger_operation,omitempty"`
	LedgerAccountBalance LedgerAccountBalance `json:"ledger_account_balance,omitempty"`
	GrantBlocks          []GrantBlock         `json:"grant_blocks,omitempty"`
	LedgerEntries        []LedgerEntry        `json:"ledger_entries,omitempty"`
	apiResponse
}

type LedgerOperationAuthorizeResponse struct {
	LedgerOperation      *LedgerOperation     `json:"ledger_operation,omitempty"`
	LedgerAccountBalance LedgerAccountBalance `json:"ledger_account_balance,omitempty"`
	GrantBlocks          []GrantBlock         `json:"grant_blocks,omitempty"`
	LedgerEntries        []LedgerEntry        `json:"ledger_entries,omitempty"`
	apiResponse
}

type LedgerOperationCaptureAuthorizationResponse struct {
	LedgerOperation      *LedgerOperation     `json:"ledger_operation,omitempty"`
	LedgerAccountBalance LedgerAccountBalance `json:"ledger_account_balance,omitempty"`
	GrantBlocks          []GrantBlock         `json:"grant_blocks,omitempty"`
	LedgerEntries        []LedgerEntry        `json:"ledger_entries,omitempty"`
	apiResponse
}

type LedgerOperationReleaseAuthorizationResponse struct {
	LedgerOperation      *LedgerOperation     `json:"ledger_operation,omitempty"`
	LedgerAccountBalance LedgerAccountBalance `json:"ledger_account_balance,omitempty"`
	GrantBlocks          []GrantBlock         `json:"grant_blocks,omitempty"`
	LedgerEntries        []LedgerEntry        `json:"ledger_entries,omitempty"`
	apiResponse
}

type LedgerOperationAllocateResponse struct {
	LedgerAccountBalance LedgerAccountBalance `json:"ledger_account_balance,omitempty"`
	LedgerOperations     []*LedgerOperation   `json:"ledger_operations,omitempty"`
	GrantBlocks          []GrantBlock         `json:"grant_blocks,omitempty"`
	LedgerEntries        []LedgerEntry        `json:"ledger_entries,omitempty"`
	apiResponse
}
