// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

type LedgerAccountBalanceService struct {
	config *ClientConfig
}

func (s *LedgerAccountBalanceService) ListLedgerAccountBalances(req *LedgerAccountBalanceListLedgerAccountBalancesRequest) (*LedgerAccountBalanceListLedgerAccountBalancesResponse, error) {
	req.method = "GET"
	req.path = "/ledger_account_balances"
	req.isListRequest = true
	req.telemetryResource = "ledgerAccountBalance"
	req.telemetryOperation = "listLedgerAccountBalances"

	return send[*LedgerAccountBalanceListLedgerAccountBalancesResponse](req, s.config)
}
