// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type LedgerEntryAccountType string

const (
	LedgerEntryAccountTypeProvisioned LedgerEntryAccountType = "provisioned"
	LedgerEntryAccountTypeOverdraft   LedgerEntryAccountType = "overdraft"
)

type LedgerEntryUnitType string

const (
	LedgerEntryUnitTypeCreditUnit LedgerEntryUnitType = "credit_unit"
)

type LedgerEntry struct {
	Id                     string                 `json:"id"`
	SubscriptionId         string                 `json:"subscription_id"`
	AccountType            LedgerEntryAccountType `json:"account_type"`
	UnitId                 string                 `json:"unit_id"`
	UnitType               LedgerEntryUnitType    `json:"unit_type"`
	Amount                 string                 `json:"amount"`
	GrantBlockStartBalance string                 `json:"grant_block_start_balance"`
	GrantBlockEndBalance   string                 `json:"grant_block_end_balance"`
	AccountStartBalance    string                 `json:"account_start_balance"`
	AccountEndBalance      string                 `json:"account_end_balance"`
	Type                   Type                   `json:"type"`
	LedgerOperationId      string                 `json:"ledger_operation_id"`
	GrantBlockId           string                 `json:"grant_block_id"`
	CreatedAt              int64                  `json:"created_at"`
	ModifiedAt             int64                  `json:"modified_at"`
	Object                 string                 `json:"object"`
}
