// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type LedgerOperationService struct {
	config *ClientConfig
}

func (s *LedgerOperationService) RetrieveLedgerOperation(id string) (*LedgerOperationRetrieveLedgerOperationResponse, error) {
	req := &BlankRequest{}
	req.method = "GET"
	req.path = fmt.Sprintf("/ledger_operations/%v", url.PathEscape(id))
	return send[*LedgerOperationRetrieveLedgerOperationResponse](req, s.config)
}

func (s *LedgerOperationService) ListLedgerOperations(req *LedgerOperationListLedgerOperationsRequest) (*LedgerOperationListLedgerOperationsResponse, error) {
	req.method = "GET"
	req.path = "/ledger_operations"
	req.isListRequest = true
	return send[*LedgerOperationListLedgerOperationsResponse](req, s.config)
}

func (s *LedgerOperationService) Capture(req *LedgerOperationCaptureRequest) (*LedgerOperationCaptureResponse, error) {
	req.method = "POST"
	req.path = "/ledger_operations/capture"
	req.isJsonRequest = true
	return send[*LedgerOperationCaptureResponse](req, s.config)
}

func (s *LedgerOperationService) Authorize(req *LedgerOperationAuthorizeRequest) (*LedgerOperationAuthorizeResponse, error) {
	req.method = "POST"
	req.path = "/ledger_operations/authorize"
	req.isJsonRequest = true
	return send[*LedgerOperationAuthorizeResponse](req, s.config)
}

func (s *LedgerOperationService) CaptureAuthorization(req *LedgerOperationCaptureAuthorizationRequest) (*LedgerOperationCaptureAuthorizationResponse, error) {
	req.method = "POST"
	req.path = "/ledger_operations/capture_authorization"
	req.isJsonRequest = true
	return send[*LedgerOperationCaptureAuthorizationResponse](req, s.config)
}

func (s *LedgerOperationService) ReleaseAuthorization(req *LedgerOperationReleaseAuthorizationRequest) (*LedgerOperationReleaseAuthorizationResponse, error) {
	req.method = "POST"
	req.path = "/ledger_operations/release_authorization"
	req.isJsonRequest = true
	return send[*LedgerOperationReleaseAuthorizationResponse](req, s.config)
}
