// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type MeterType string

const (
	MeterTypeSimple   MeterType = "simple"
	MeterTypeCompound MeterType = "compound"
)

type MeterStatus string

const (
	MeterStatusActive   MeterStatus = "active"
	MeterStatusArchived MeterStatus = "archived"
	MeterStatusDeleted  MeterStatus = "deleted"
)

type MeterColumnDefinitionDataType string

const (
	MeterColumnDefinitionDataTypeNumber MeterColumnDefinitionDataType = "number"
	MeterColumnDefinitionDataTypeString MeterColumnDefinitionDataType = "string"
)

type MeterFeatureStatus string

const (
	MeterFeatureStatusActive   MeterFeatureStatus = "active"
	MeterFeatureStatusArchived MeterFeatureStatus = "archived"
	MeterFeatureStatusDraft    MeterFeatureStatus = "draft"
)

type MeterFeatureType string

const (
	MeterFeatureTypeSwitch   MeterFeatureType = "switch"
	MeterFeatureTypeCustom   MeterFeatureType = "custom"
	MeterFeatureTypeQuantity MeterFeatureType = "quantity"
	MeterFeatureTypeRange    MeterFeatureType = "range"
)

type Meter struct {
	Id                string              `json:"id"`
	Name              string              `json:"name"`
	Description       string              `json:"description"`
	Type              MeterType           `json:"type"`
	Status            MeterStatus         `json:"status"`
	Query             string              `json:"query"`
	CreatedAt         int64               `json:"created_at"`
	UpdatedAt         int64               `json:"updated_at"`
	ColumnDefinitions []*ColumnDefinition `json:"column_definitions"`
	Features          []*Feature          `json:"features"`
	Object            string              `json:"object"`
}

type MeterListRequest struct {
	Limit      *int32        `json:"limit,omitempty"`
	Offset     string        `json:"offset,omitempty"`
	Name       *StringFilter `json:"name,omitempty"`
	SortBy     *SortFilter   `json:"sort_by,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *MeterListRequest) payload() any { return r }

type MeterListMeterResponse struct {
	Meter *Meter `json:"meter,omitempty"`
}

type MeterListResponse struct {
	List       []*MeterListMeterResponse `json:"list,omitempty"`
	NextOffset string                    `json:"next_offset,omitempty"`
	apiResponse
}
