// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type MeteredFeatureColumnDefinitionDataType string

const (
	MeteredFeatureColumnDefinitionDataTypeNumber MeteredFeatureColumnDefinitionDataType = "number"
	MeteredFeatureColumnDefinitionDataTypeString MeteredFeatureColumnDefinitionDataType = "string"
)

type MeteredFeatureFeatureStatus string

const (
	MeteredFeatureFeatureStatusActive   MeteredFeatureFeatureStatus = "active"
	MeteredFeatureFeatureStatusArchived MeteredFeatureFeatureStatus = "archived"
	MeteredFeatureFeatureStatusDraft    MeteredFeatureFeatureStatus = "draft"
)

type MeteredFeatureFeatureType string

const (
	MeteredFeatureFeatureTypeSwitch   MeteredFeatureFeatureType = "switch"
	MeteredFeatureFeatureTypeCustom   MeteredFeatureFeatureType = "custom"
	MeteredFeatureFeatureTypeQuantity MeteredFeatureFeatureType = "quantity"
	MeteredFeatureFeatureTypeRange    MeteredFeatureFeatureType = "range"
)

type MeteredFeature struct {
	Id                string              `json:"id"`
	Name              string              `json:"name"`
	Description       string              `json:"description"`
	Type              Type                `json:"type"`
	Status            GiftStatus          `json:"status"`
	Query             string              `json:"query"`
	ColumnDefinitions []*ColumnDefinition `json:"column_definitions"`
	Features          []*Feature          `json:"features"`
	Object            string              `json:"object"`
}

type MeteredFeatureCreateRequest struct {
	Name              string                                  `json:"name"`
	Description       string                                  `json:"description,omitempty"`
	FeatureUnit       string                                  `json:"feature_unit"`
	Query             string                                  `json:"query"`
	ColumnDefinitions []*MeteredFeatureCreateColumnDefinition `json:"column_definitions,omitempty"`
	apiRequest        `json:"-" form:"-"`
}

func (r *MeteredFeatureCreateRequest) payload() any { return r }

type MeteredFeatureCreateColumnDefinition struct {
	ColumnName string                   `json:"column_name"`
	DataType   ColumnDefinitionDataType `json:"data_type"`
}

type MeteredFeatureArchiveRequest struct {
	Id         string `json:"-" form:"-"`
	apiRequest `json:"-" form:"-"`
}

func (r *MeteredFeatureArchiveRequest) payload() any { return r }

type MeteredFeatureReactivateRequest struct {
	Id         string `json:"-" form:"-"`
	apiRequest `json:"-" form:"-"`
}

func (r *MeteredFeatureReactivateRequest) payload() any { return r }

type MeteredFeatureDeleteRequest struct {
	Id         string `json:"-" form:"-"`
	apiRequest `json:"-" form:"-"`
}

func (r *MeteredFeatureDeleteRequest) payload() any { return r }

type MeteredFeatureCreateResponse struct {
	Meter Meter `json:"meter,omitempty"`
	apiResponse
}

type MeteredFeatureArchiveResponse struct {
	Meter Meter `json:"meter,omitempty"`
	apiResponse
}

type MeteredFeatureReactivateResponse struct {
	Meter Meter `json:"meter,omitempty"`
	apiResponse
}

type MeteredFeatureDeleteResponse struct {
	Meter Meter `json:"meter,omitempty"`
	apiResponse
}
