// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type MeteredFeatureService struct {
	config *ClientConfig
}

func (s *MeteredFeatureService) Create(req *MeteredFeatureCreateRequest) (*MeteredFeatureCreateResponse, error) {
	req.method = "POST"
	req.path = "/metered_features"
	req.isIdempotent = true
	req.telemetryResource = "meteredFeature"
	req.telemetryOperation = "create"

	return send[*MeteredFeatureCreateResponse](req, s.config)
}

func (s *MeteredFeatureService) Archive(req *MeteredFeatureArchiveRequest) (*MeteredFeatureArchiveResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/metered_features/%v/archive_command", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "meteredFeature"
	req.telemetryOperation = "archive"

	return send[*MeteredFeatureArchiveResponse](req, s.config)
}

func (s *MeteredFeatureService) Reactivate(req *MeteredFeatureReactivateRequest) (*MeteredFeatureReactivateResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/metered_features/%v/reactivate_command", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "meteredFeature"
	req.telemetryOperation = "reactivate"

	return send[*MeteredFeatureReactivateResponse](req, s.config)
}

func (s *MeteredFeatureService) Delete(req *MeteredFeatureDeleteRequest) (*MeteredFeatureDeleteResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/metered_features/%v/delete", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "meteredFeature"
	req.telemetryOperation = "delete"

	return send[*MeteredFeatureDeleteResponse](req, s.config)
}
