// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type OfferEventType string

const (
	OfferEventTypeViewed    OfferEventType = "viewed"
	OfferEventTypeDismissed OfferEventType = "dismissed"
)

type OfferEvent struct {
	Object string `json:"object"`
}

type OfferEventOfferEventsRequest struct {
	PersonalizedOfferId string         `json:"personalized_offer_id"`
	Type                OfferEventType `json:"type"`
	apiRequest          `json:"-" form:"-"`
}

func (r *OfferEventOfferEventsRequest) payload() any { return r }

type OfferEventOfferEventsResponse struct {
	apiResponse
}
