// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

type OfferEventService struct {
	config *ClientConfig
}

func (s *OfferEventService) OfferEvents(req *OfferEventOfferEventsRequest) (*OfferEventOfferEventsResponse, error) {
	req.method = "POST"
	req.path = "/offer_events"
	req.isJsonRequest = true
	req.telemetryResource = "offerEvent"
	req.telemetryOperation = "offerEvents"

	return send[*OfferEventOfferEventsResponse](req, s.config)
}
