// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type OmnichannelSubscriptionService struct {
	config *ClientConfig
}

func (s *OmnichannelSubscriptionService) Retrieve(req *OmnichannelSubscriptionRetrieveRequest) (*OmnichannelSubscriptionRetrieveResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/omnichannel_subscriptions/%v", url.PathEscape(req.Id))
	req.telemetryResource = "omnichannelSubscription"
	req.telemetryOperation = "retrieve"

	return send[*OmnichannelSubscriptionRetrieveResponse](req, s.config)
}

func (s *OmnichannelSubscriptionService) List(req *OmnichannelSubscriptionListRequest) (*OmnichannelSubscriptionListResponse, error) {
	req.method = "GET"
	req.path = "/omnichannel_subscriptions"
	req.isListRequest = true
	req.telemetryResource = "omnichannelSubscription"
	req.telemetryOperation = "list"

	return send[*OmnichannelSubscriptionListResponse](req, s.config)
}

func (s *OmnichannelSubscriptionService) OmnichannelTransactionsForOmnichannelSubscription(id string, req *OmnichannelSubscriptionOmnichannelTransactionsForOmnichannelSubscriptionRequest) (*OmnichannelSubscriptionOmnichannelTransactionsForOmnichannelSubscriptionResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/omnichannel_subscriptions/%v/omnichannel_transactions", url.PathEscape(id))
	req.isListRequest = true
	req.telemetryResource = "omnichannelSubscription"
	req.telemetryOperation = "omnichannelTransactionsForOmnichannelSubscription"

	return send[*OmnichannelSubscriptionOmnichannelTransactionsForOmnichannelSubscriptionResponse](req, s.config)
}

func (s *OmnichannelSubscriptionService) Move(id string, req *OmnichannelSubscriptionMoveRequest) (*OmnichannelSubscriptionMoveResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/omnichannel_subscriptions/%v/move", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "omnichannelSubscription"
	req.telemetryOperation = "move"

	return send[*OmnichannelSubscriptionMoveResponse](req, s.config)
}
