// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type PaymentVoucherService struct {
	config *ClientConfig
}

func (s *PaymentVoucherService) Create(req *PaymentVoucherCreateRequest) (*PaymentVoucherCreateResponse, error) {
	req.method = "POST"
	req.path = "/payment_vouchers"
	req.isIdempotent = true
	return send[*PaymentVoucherCreateResponse](req, s.config)
}

func (s *PaymentVoucherService) Retrieve(id string) (*PaymentVoucherRetrieveResponse, error) {
	req := &BlankRequest{}
	req.method = "GET"
	req.path = fmt.Sprintf("/payment_vouchers/%v", url.PathEscape(id))
	return send[*PaymentVoucherRetrieveResponse](req, s.config)
}

func (s *PaymentVoucherService) PaymentVouchersForInvoice(id string, req *PaymentVoucherPaymentVouchersForInvoiceRequest) (*PaymentVoucherPaymentVouchersForInvoiceResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/invoices/%v/payment_vouchers", url.PathEscape(id))
	req.isListRequest = true
	return send[*PaymentVoucherPaymentVouchersForInvoiceResponse](req, s.config)
}

func (s *PaymentVoucherService) PaymentVouchersForCustomer(id string, req *PaymentVoucherPaymentVouchersForCustomerRequest) (*PaymentVoucherPaymentVouchersForCustomerResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/customers/%v/payment_vouchers", url.PathEscape(id))
	req.isListRequest = true
	return send[*PaymentVoucherPaymentVouchersForCustomerResponse](req, s.config)
}
