// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type PaymentScheduleEstimateEntityType string

const (
	PaymentScheduleEstimateEntityTypeInvoice PaymentScheduleEstimateEntityType = "invoice"
)

type PaymentScheduleEstimateScheduleEntryStatus string

const (
	PaymentScheduleEstimateScheduleEntryStatusPosted     PaymentScheduleEstimateScheduleEntryStatus = "posted"
	PaymentScheduleEstimateScheduleEntryStatusPaymentDue PaymentScheduleEstimateScheduleEntryStatus = "payment_due"
	PaymentScheduleEstimateScheduleEntryStatusPaid       PaymentScheduleEstimateScheduleEntryStatus = "paid"
)

type PaymentScheduleEstimate struct {
	Id              string                                  `json:"id"`
	SchemeId        string                                  `json:"scheme_id"`
	EntityType      PaymentScheduleEstimateEntityType       `json:"entity_type"`
	EntityId        string                                  `json:"entity_id"`
	Amount          int64                                   `json:"amount"`
	CurrencyCode    string                                  `json:"currency_code"`
	ScheduleEntries []*PaymentScheduleEstimateScheduleEntry `json:"schedule_entries"`
	Object          string                                  `json:"object"`
}

type PaymentScheduleEstimateScheduleEntry struct {
	Id     string                                     `json:"id"`
	Date   int64                                      `json:"date"`
	Amount int64                                      `json:"amount"`
	Status PaymentScheduleEstimateScheduleEntryStatus `json:"status"`
	Object string                                     `json:"object"`
}
