// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type PaymentVoucherStatus string

const (
	PaymentVoucherStatusActive   PaymentVoucherStatus = "active"
	PaymentVoucherStatusConsumed PaymentVoucherStatus = "consumed"
	PaymentVoucherStatusExpired  PaymentVoucherStatus = "expired"
	PaymentVoucherStatusFailure  PaymentVoucherStatus = "failure"
)

type PaymentVoucher struct {
	Id                 string                         `json:"id"`
	IdAtGateway        string                         `json:"id_at_gateway"`
	PaymentVoucherType PaymentVoucherType             `json:"payment_voucher_type"`
	ExpiresAt          int64                          `json:"expires_at"`
	Status             PaymentVoucherStatus           `json:"status"`
	SubscriptionId     string                         `json:"subscription_id"`
	CurrencyCode       string                         `json:"currency_code"`
	Amount             int64                          `json:"amount"`
	GatewayAccountId   string                         `json:"gateway_account_id"`
	PaymentSourceId    string                         `json:"payment_source_id"`
	Gateway            Gateway                        `json:"gateway"`
	Payload            string                         `json:"payload"`
	ErrorCode          string                         `json:"error_code"`
	ErrorText          string                         `json:"error_text"`
	Url                string                         `json:"url"`
	Date               int64                          `json:"date"`
	ResourceVersion    int64                          `json:"resource_version"`
	UpdatedAt          int64                          `json:"updated_at"`
	CustomerId         string                         `json:"customer_id"`
	LinkedInvoices     []*PaymentVoucherLinkedInvoice `json:"linked_invoices"`
	Object             string                         `json:"object"`
}

type PaymentVoucherLinkedInvoice struct {
	InvoiceId string `json:"invoice_id"`
	TxnId     string `json:"txn_id"`
	AppliedAt int64  `json:"applied_at"`
	Object    string `json:"object"`
}

type PaymentVoucherCreateRequest struct {
	CustomerId           string                                    `json:"customer_id"`
	VoucherPaymentSource *PaymentVoucherCreateVoucherPaymentSource `json:"voucher_payment_source,omitempty"`
	InvoiceAllocations   []*PaymentVoucherCreateInvoiceAllocation  `json:"invoice_allocations,omitempty"`
	PaymentSourceId      string                                    `json:"payment_source_id,omitempty"`
	apiRequest           `json:"-" form:"-"`
}

func (r *PaymentVoucherCreateRequest) payload() any { return r }

type PaymentVoucherCreateVoucherPaymentSource struct {
	VoucherType VoucherType `json:"voucher_type"`
}

type PaymentVoucherCreateInvoiceAllocation struct {
	InvoiceId string `json:"invoice_id"`
}

type PaymentVoucherPaymentVouchersForInvoiceRequest struct {
	Limit      *int32      `json:"limit,omitempty"`
	Offset     string      `json:"offset,omitempty"`
	Status     *EnumFilter `json:"status,omitempty"`
	SortBy     *SortFilter `json:"sort_by,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *PaymentVoucherPaymentVouchersForInvoiceRequest) payload() any { return r }

type PaymentVoucherPaymentVouchersForCustomerRequest struct {
	Limit      *int32      `json:"limit,omitempty"`
	Offset     string      `json:"offset,omitempty"`
	Status     *EnumFilter `json:"status,omitempty"`
	SortBy     *SortFilter `json:"sort_by,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *PaymentVoucherPaymentVouchersForCustomerRequest) payload() any { return r }

type PaymentVoucherCreateResponse struct {
	PaymentVoucher *PaymentVoucher `json:"payment_voucher,omitempty"`
	apiResponse
}

type PaymentVoucherRetrieveResponse struct {
	PaymentVoucher *PaymentVoucher `json:"payment_voucher,omitempty"`
	apiResponse
}

type PaymentVoucherPaymentVouchersForInvoicePaymentVoucherResponse struct {
	PaymentVoucher *PaymentVoucher `json:"payment_voucher,omitempty"`
}

type PaymentVoucherPaymentVouchersForInvoiceResponse struct {
	List       []*PaymentVoucherPaymentVouchersForInvoicePaymentVoucherResponse `json:"list,omitempty"`
	NextOffset string                                                           `json:"next_offset,omitempty"`
	apiResponse
}

type PaymentVoucherPaymentVouchersForCustomerPaymentVoucherResponse struct {
	PaymentVoucher *PaymentVoucher `json:"payment_voucher,omitempty"`
}

type PaymentVoucherPaymentVouchersForCustomerResponse struct {
	List       []*PaymentVoucherPaymentVouchersForCustomerPaymentVoucherResponse `json:"list,omitempty"`
	NextOffset string                                                            `json:"next_offset,omitempty"`
	apiResponse
}
