// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type PaymentScheduleSchemeService struct {
	config *ClientConfig
}

func (s *PaymentScheduleSchemeService) Create(req *PaymentScheduleSchemeCreateRequest) (*PaymentScheduleSchemeCreateResponse, error) {
	req.method = "POST"
	req.path = "/payment_schedule_schemes"
	req.isIdempotent = true
	req.telemetryResource = "paymentScheduleScheme"
	req.telemetryOperation = "create"

	return send[*PaymentScheduleSchemeCreateResponse](req, s.config)
}

func (s *PaymentScheduleSchemeService) Retrieve(req *PaymentScheduleSchemeRetrieveRequest) (*PaymentScheduleSchemeRetrieveResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/payment_schedule_schemes/%v", url.PathEscape(req.Id))
	req.telemetryResource = "paymentScheduleScheme"
	req.telemetryOperation = "retrieve"

	return send[*PaymentScheduleSchemeRetrieveResponse](req, s.config)
}

func (s *PaymentScheduleSchemeService) Delete(req *PaymentScheduleSchemeDeleteRequest) (*PaymentScheduleSchemeDeleteResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/payment_schedule_schemes/%v/delete", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "paymentScheduleScheme"
	req.telemetryOperation = "delete"

	return send[*PaymentScheduleSchemeDeleteResponse](req, s.config)
}
