// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

type PersonalizedOfferService struct {
	config *ClientConfig
}

func (s *PersonalizedOfferService) PersonalizedOffers(req *PersonalizedOfferPersonalizedOffersRequest) (*PersonalizedOfferPersonalizedOffersResponse, error) {
	req.method = "POST"
	req.path = "/personalized_offers"
	req.isJsonRequest = true
	req.telemetryResource = "personalizedOffer"
	req.telemetryOperation = "personalizedOffers"

	return send[*PersonalizedOfferPersonalizedOffersResponse](req, s.config)
}
