// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type PlanService struct {
	config *ClientConfig
}

func (s *PlanService) Create(req *PlanCreateRequest) (*PlanCreateResponse, error) {
	req.method = "POST"
	req.path = "/plans"
	req.isIdempotent = true
	return send[*PlanCreateResponse](req, s.config)
}

func (s *PlanService) Update(id string, req *PlanUpdateRequest) (*PlanUpdateResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/plans/%v", url.PathEscape(id))
	req.isIdempotent = true
	return send[*PlanUpdateResponse](req, s.config)
}

func (s *PlanService) List(req *PlanListRequest) (*PlanListResponse, error) {
	req.method = "GET"
	req.path = "/plans"
	req.isListRequest = true
	return send[*PlanListResponse](req, s.config)
}

func (s *PlanService) Retrieve(id string) (*PlanRetrieveResponse, error) {
	req := &BlankRequest{}
	req.method = "GET"
	req.path = fmt.Sprintf("/plans/%v", url.PathEscape(id))
	return send[*PlanRetrieveResponse](req, s.config)
}

func (s *PlanService) Delete(id string) (*PlanDeleteResponse, error) {
	req := &BlankRequest{}
	req.method = "POST"
	req.path = fmt.Sprintf("/plans/%v/delete", url.PathEscape(id))
	req.isIdempotent = true
	return send[*PlanDeleteResponse](req, s.config)
}

func (s *PlanService) Copy(req *PlanCopyRequest) (*PlanCopyResponse, error) {
	req.method = "POST"
	req.path = "/plans/copy"
	req.isIdempotent = true
	return send[*PlanCopyResponse](req, s.config)
}

func (s *PlanService) Unarchive(id string) (*PlanUnarchiveResponse, error) {
	req := &BlankRequest{}
	req.method = "POST"
	req.path = fmt.Sprintf("/plans/%v/unarchive", url.PathEscape(id))
	req.isIdempotent = true
	return send[*PlanUnarchiveResponse](req, s.config)
}
