// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type PriceVariantService struct {
	config *ClientConfig
}

func (s *PriceVariantService) Create(req *PriceVariantCreateRequest) (*PriceVariantCreateResponse, error) {
	req.method = "POST"
	req.path = "/price_variants"
	req.isIdempotent = true
	req.telemetryResource = "priceVariant"
	req.telemetryOperation = "create"

	return send[*PriceVariantCreateResponse](req, s.config)
}

func (s *PriceVariantService) Retrieve(req *PriceVariantRetrieveRequest) (*PriceVariantRetrieveResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/price_variants/%v", url.PathEscape(req.Id))
	req.telemetryResource = "priceVariant"
	req.telemetryOperation = "retrieve"

	return send[*PriceVariantRetrieveResponse](req, s.config)
}

func (s *PriceVariantService) Update(id string, req *PriceVariantUpdateRequest) (*PriceVariantUpdateResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/price_variants/%v", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "priceVariant"
	req.telemetryOperation = "update"

	return send[*PriceVariantUpdateResponse](req, s.config)
}

func (s *PriceVariantService) Delete(req *PriceVariantDeleteRequest) (*PriceVariantDeleteResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/price_variants/%v/delete", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "priceVariant"
	req.telemetryOperation = "delete"

	return send[*PriceVariantDeleteResponse](req, s.config)
}

func (s *PriceVariantService) List(req *PriceVariantListRequest) (*PriceVariantListResponse, error) {
	req.method = "GET"
	req.path = "/price_variants"
	req.isListRequest = true
	req.telemetryResource = "priceVariant"
	req.telemetryOperation = "list"

	return send[*PriceVariantListResponse](req, s.config)
}
