// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type PromotionalGrant struct {
	SubscriptionId string `json:"subscription_id"`
	UnitId         string `json:"unit_id"`
	Amount         string `json:"amount"`
	ExpiresAt      int64  `json:"expires_at"`
	Metadata       string `json:"metadata"`
	Object         string `json:"object"`
}

type PromotionalGrantPromotionalGrantsRequest struct {
	SubscriptionId string                 `json:"subscription_id"`
	UnitId         string                 `json:"unit_id"`
	Amount         string                 `json:"amount"`
	ExpiresAt      *int64                 `json:"expires_at"`
	Metadata       map[string]interface{} `json:"metadata,omitempty"`
	apiRequest     `json:"-" form:"-"`
}

func (r *PromotionalGrantPromotionalGrantsRequest) payload() any { return r }

type PromotionalGrantPromotionalGrantsResponse struct {
	LedgerOperations []LedgerOperation `json:"ledger_operations,omitempty"`
	GrantBlocks      []GrantBlock      `json:"grant_blocks,omitempty"`
	apiResponse
}
