// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

import (
	"encoding/json"
)

type PromotionalGrant struct {
	SubscriptionId string          `json:"subscription_id"`
	UnitId         string          `json:"unit_id"`
	Amount         string          `json:"amount"`
	ExpiresAt      int64           `json:"expires_at"`
	Metadata       json.RawMessage `json:"metadata"`
	Object         string          `json:"object"`
}

type PromotionalGrantPromotionalGrantsRequest struct {
	SubscriptionId string                 `json:"subscription_id"`
	UnitId         string                 `json:"unit_id"`
	Id             string                 `json:"id,omitempty"`
	Amount         string                 `json:"amount"`
	EffectiveFrom  *int64                 `json:"effective_from,omitempty"`
	ExpiresAt      *int64                 `json:"expires_at"`
	Metadata       map[string]interface{} `json:"metadata,omitempty"`
	apiRequest     `json:"-" form:"-"`
}

func (r *PromotionalGrantPromotionalGrantsRequest) payload() any { return r }

type PromotionalGrantPromotionalGrantsResponse struct {
	LedgerOperations []LedgerOperation `json:"ledger_operations,omitempty"`
	GrantBlocks      []GrantBlock      `json:"grant_blocks,omitempty"`
	apiResponse
}
