// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type PromotionalCreditService struct {
	config *ClientConfig
}

func (s *PromotionalCreditService) Add(req *PromotionalCreditAddRequest) (*PromotionalCreditAddResponse, error) {
	req.method = "POST"
	req.path = "/promotional_credits/add"
	req.isIdempotent = true
	return send[*PromotionalCreditAddResponse](req, s.config)
}

func (s *PromotionalCreditService) Deduct(req *PromotionalCreditDeductRequest) (*PromotionalCreditDeductResponse, error) {
	req.method = "POST"
	req.path = "/promotional_credits/deduct"
	req.isIdempotent = true
	return send[*PromotionalCreditDeductResponse](req, s.config)
}

func (s *PromotionalCreditService) Set(req *PromotionalCreditSetRequest) (*PromotionalCreditSetResponse, error) {
	req.method = "POST"
	req.path = "/promotional_credits/set"
	req.isIdempotent = true
	return send[*PromotionalCreditSetResponse](req, s.config)
}

func (s *PromotionalCreditService) List(req *PromotionalCreditListRequest) (*PromotionalCreditListResponse, error) {
	req.method = "GET"
	req.path = "/promotional_credits"
	req.isListRequest = true
	return send[*PromotionalCreditListResponse](req, s.config)
}

func (s *PromotionalCreditService) Retrieve(id string) (*PromotionalCreditRetrieveResponse, error) {
	req := &BlankRequest{}
	req.method = "GET"
	req.path = fmt.Sprintf("/promotional_credits/%v", url.PathEscape(id))
	return send[*PromotionalCreditRetrieveResponse](req, s.config)
}
