// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type PurchaseContractTermActionAtTermEnd string

const (
	PurchaseContractTermActionAtTermEndRenew     PurchaseContractTermActionAtTermEnd = "renew"
	PurchaseContractTermActionAtTermEndEvergreen PurchaseContractTermActionAtTermEnd = "evergreen"
	PurchaseContractTermActionAtTermEndCancel    PurchaseContractTermActionAtTermEnd = "cancel"
	PurchaseContractTermActionAtTermEndRenewOnce PurchaseContractTermActionAtTermEnd = "renew_once"
)

type Purchase struct {
	Id              string   `json:"id"`
	CustomerId      string   `json:"customer_id"`
	CreatedAt       int64    `json:"created_at"`
	ModifiedAt      int64    `json:"modified_at"`
	SubscriptionIds []string `json:"subscription_ids"`
	InvoiceIds      []string `json:"invoice_ids"`
	Object          string   `json:"object"`
}

type PurchaseCreateRequest struct {
	PurchaseItems               []*PurchaseCreatePurchaseItem      `json:"purchase_items,omitempty"`
	ItemTiers                   []*PurchaseCreateItemTier          `json:"item_tiers,omitempty"`
	ShippingAddresses           []*PurchaseCreateShippingAddress   `json:"shipping_addresses,omitempty"`
	Discounts                   []*PurchaseCreateDiscount          `json:"discounts,omitempty"`
	SubscriptionInfo            []*PurchaseCreateSubscriptionInfo  `json:"subscription_info,omitempty"`
	ContractTerms               []*PurchaseCreateContractTerm      `json:"contract_terms,omitempty"`
	InvoiceInfo                 *PurchaseCreateInvoiceInfo         `json:"invoice_info,omitempty"`
	PaymentSchedule             *PurchaseCreatePaymentSchedule     `json:"payment_schedule,omitempty"`
	StatementDescriptor         *PurchaseCreateStatementDescriptor `json:"statement_descriptor,omitempty"`
	CustomerId                  string                             `json:"customer_id"`
	PaymentSourceId             string                             `json:"payment_source_id,omitempty"`
	PaymentIntent               *PurchaseCreatePaymentIntent       `json:"payment_intent,omitempty"`
	ReplacePrimaryPaymentSource *bool                              `json:"replace_primary_payment_source,omitempty"`
	apiRequest                  `json:"-" form:"-"`
}

func (r *PurchaseCreateRequest) payload() any { return r }

type PurchaseCreatePurchaseItem struct {
	Index               *int32 `json:"index"`
	ItemPriceId         string `json:"item_price_id"`
	Quantity            *int32 `json:"quantity,omitempty"`
	UnitAmount          *int64 `json:"unit_amount,omitempty"`
	UnitAmountInDecimal string `json:"unit_amount_in_decimal,omitempty"`
	QuantityInDecimal   string `json:"quantity_in_decimal,omitempty"`
}

type PurchaseCreateItemTier struct {
	Index                 *int32 `json:"index"`
	ItemPriceId           string `json:"item_price_id,omitempty"`
	StartingUnit          *int32 `json:"starting_unit,omitempty"`
	EndingUnit            *int32 `json:"ending_unit,omitempty"`
	Price                 *int64 `json:"price,omitempty"`
	StartingUnitInDecimal string `json:"starting_unit_in_decimal,omitempty"`
	EndingUnitInDecimal   string `json:"ending_unit_in_decimal,omitempty"`
	PriceInDecimal        string `json:"price_in_decimal,omitempty"`
}

type PurchaseCreateShippingAddress struct {
	FirstName        string           `json:"first_name,omitempty"`
	LastName         string           `json:"last_name,omitempty"`
	Email            string           `json:"email,omitempty"`
	Company          string           `json:"company,omitempty"`
	Phone            string           `json:"phone,omitempty"`
	Line1            string           `json:"line1,omitempty"`
	Line2            string           `json:"line2,omitempty"`
	Line3            string           `json:"line3,omitempty"`
	City             string           `json:"city,omitempty"`
	State            string           `json:"state,omitempty"`
	StateCode        string           `json:"state_code,omitempty"`
	Country          string           `json:"country,omitempty"`
	Zip              string           `json:"zip,omitempty"`
	ValidationStatus ValidationStatus `json:"validation_status,omitempty"`
}

type PurchaseCreateDiscount struct {
	Index         *int32   `json:"index,omitempty"`
	CouponId      string   `json:"coupon_id,omitempty"`
	Percentage    *float64 `json:"percentage,omitempty"`
	Quantity      *int32   `json:"quantity,omitempty"`
	Amount        *int64   `json:"amount,omitempty"`
	IncludedInMrr *bool    `json:"included_in_mrr,omitempty"`
}

type PurchaseCreateSubscriptionInfo struct {
	Index                             *int32                 `json:"index"`
	SubscriptionId                    string                 `json:"subscription_id,omitempty"`
	BillingCycles                     *int32                 `json:"billing_cycles,omitempty"`
	ContractTermBillingCycleOnRenewal *int32                 `json:"contract_term_billing_cycle_on_renewal,omitempty"`
	MetaData                          map[string]interface{} `json:"meta_data,omitempty"`
}

type PurchaseCreateContractTerm struct {
	Index                    *int32                      `json:"index"`
	ActionAtTermEnd          ContractTermActionAtTermEnd `json:"action_at_term_end,omitempty"`
	CancellationCutoffPeriod *int32                      `json:"cancellation_cutoff_period,omitempty"`
}

type PurchaseCreateInvoiceInfo struct {
	PoNumber string `json:"po_number,omitempty"`
	Notes    string `json:"notes,omitempty"`
}

type PurchaseCreatePaymentSchedule struct {
	SchemeId string `json:"scheme_id,omitempty"`
	Amount   *int64 `json:"amount,omitempty"`
}

type PurchaseCreateStatementDescriptor struct {
	Descriptor string `json:"descriptor,omitempty"`
}

type PurchaseCreatePaymentIntent struct {
	Id                    string                         `json:"id,omitempty"`
	GatewayAccountId      string                         `json:"gateway_account_id,omitempty"`
	GwToken               string                         `json:"gw_token,omitempty"`
	PaymentMethodType     PaymentIntentPaymentMethodType `json:"payment_method_type,omitempty"`
	ReferenceId           string                         `json:"reference_id,omitempty"`
	GwPaymentMethodId     string                         `json:"gw_payment_method_id,omitempty"`
	AdditionalInformation map[string]interface{}         `json:"additional_information,omitempty"`
}

type PurchaseEstimateRequest struct {
	PurchaseItems     []*PurchaseEstimatePurchaseItem     `json:"purchase_items,omitempty"`
	ItemTiers         []*PurchaseEstimateItemTier         `json:"item_tiers,omitempty"`
	ShippingAddresses []*PurchaseEstimateShippingAddress  `json:"shipping_addresses,omitempty"`
	Discounts         []*PurchaseEstimateDiscount         `json:"discounts,omitempty"`
	SubscriptionInfo  []*PurchaseEstimateSubscriptionInfo `json:"subscription_info,omitempty"`
	ContractTerms     []*PurchaseEstimateContractTerm     `json:"contract_terms,omitempty"`
	Customer          *PurchaseEstimateCustomer           `json:"customer,omitempty"`
	BillingAddress    *PurchaseEstimateBillingAddress     `json:"billing_address,omitempty"`
	ClientProfileId   string                              `json:"client_profile_id,omitempty"`
	CustomerId        string                              `json:"customer_id,omitempty"`
	apiRequest        `json:"-" form:"-"`
}

func (r *PurchaseEstimateRequest) payload() any { return r }

type PurchaseEstimatePurchaseItem struct {
	Index               *int32 `json:"index"`
	ItemPriceId         string `json:"item_price_id"`
	Quantity            *int32 `json:"quantity,omitempty"`
	UnitAmount          *int64 `json:"unit_amount,omitempty"`
	UnitAmountInDecimal string `json:"unit_amount_in_decimal,omitempty"`
	QuantityInDecimal   string `json:"quantity_in_decimal,omitempty"`
}

type PurchaseEstimateItemTier struct {
	Index                 *int32 `json:"index"`
	ItemPriceId           string `json:"item_price_id,omitempty"`
	StartingUnit          *int32 `json:"starting_unit,omitempty"`
	EndingUnit            *int32 `json:"ending_unit,omitempty"`
	Price                 *int64 `json:"price,omitempty"`
	StartingUnitInDecimal string `json:"starting_unit_in_decimal,omitempty"`
	EndingUnitInDecimal   string `json:"ending_unit_in_decimal,omitempty"`
	PriceInDecimal        string `json:"price_in_decimal,omitempty"`
}

type PurchaseEstimateShippingAddress struct {
	FirstName        string           `json:"first_name,omitempty"`
	LastName         string           `json:"last_name,omitempty"`
	Email            string           `json:"email,omitempty"`
	Company          string           `json:"company,omitempty"`
	Phone            string           `json:"phone,omitempty"`
	Line1            string           `json:"line1,omitempty"`
	Line2            string           `json:"line2,omitempty"`
	Line3            string           `json:"line3,omitempty"`
	City             string           `json:"city,omitempty"`
	State            string           `json:"state,omitempty"`
	StateCode        string           `json:"state_code,omitempty"`
	Country          string           `json:"country,omitempty"`
	Zip              string           `json:"zip,omitempty"`
	ValidationStatus ValidationStatus `json:"validation_status,omitempty"`
}

type PurchaseEstimateDiscount struct {
	Index         *int32   `json:"index,omitempty"`
	CouponId      string   `json:"coupon_id,omitempty"`
	Percentage    *float64 `json:"percentage,omitempty"`
	Quantity      *int32   `json:"quantity,omitempty"`
	Amount        *int64   `json:"amount,omitempty"`
	IncludedInMrr *bool    `json:"included_in_mrr,omitempty"`
}

type PurchaseEstimateSubscriptionInfo struct {
	Index                             *int32 `json:"index"`
	SubscriptionId                    string `json:"subscription_id,omitempty"`
	BillingCycles                     *int32 `json:"billing_cycles,omitempty"`
	ContractTermBillingCycleOnRenewal *int32 `json:"contract_term_billing_cycle_on_renewal,omitempty"`
}

type PurchaseEstimateContractTerm struct {
	Index                    *int32                      `json:"index"`
	ActionAtTermEnd          ContractTermActionAtTermEnd `json:"action_at_term_end,omitempty"`
	CancellationCutoffPeriod *int32                      `json:"cancellation_cutoff_period,omitempty"`
}

type PurchaseEstimateCustomer struct {
	VatNumber        string                   `json:"vat_number,omitempty"`
	VatNumberPrefix  string                   `json:"vat_number_prefix,omitempty"`
	RegisteredForGst *bool                    `json:"registered_for_gst,omitempty"`
	Taxability       Taxability               `json:"taxability,omitempty"`
	EntityCode       EntityCode               `json:"entity_code,omitempty"`
	ExemptNumber     string                   `json:"exempt_number,omitempty"`
	ExemptionDetails []map[string]interface{} `json:"exemption_details,omitempty"`
	CustomerType     CustomerType             `json:"customer_type,omitempty"`
}

type PurchaseEstimateBillingAddress struct {
	Line1            string           `json:"line1,omitempty"`
	Line2            string           `json:"line2,omitempty"`
	Line3            string           `json:"line3,omitempty"`
	City             string           `json:"city,omitempty"`
	StateCode        string           `json:"state_code,omitempty"`
	Zip              string           `json:"zip,omitempty"`
	Country          string           `json:"country,omitempty"`
	ValidationStatus ValidationStatus `json:"validation_status,omitempty"`
}

type PurchaseCreateResponse struct {
	Purchase *Purchase `json:"purchase,omitempty"`
	apiResponse
}

type PurchaseEstimateResponse struct {
	Estimate Estimate `json:"estimate,omitempty"`
	apiResponse
}
