// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type QuoteEntitlementService struct {
	config *ClientConfig
}

func (s *QuoteEntitlementService) ListQuoteEntitlements(id string, req *QuoteEntitlementListQuoteEntitlementsRequest) (*QuoteEntitlementListQuoteEntitlementsResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/quotes/%v/quote_entitlements", url.PathEscape(id))
	req.isListRequest = true
	req.telemetryResource = "quoteEntitlement"
	req.telemetryOperation = "listQuoteEntitlements"

	return send[*QuoteEntitlementListQuoteEntitlementsResponse](req, s.config)
}
