// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type QuoteService struct {
	config *ClientConfig
}

func (s *QuoteService) Retrieve(req *QuoteRetrieveRequest) (*QuoteRetrieveResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/quotes/%v", url.PathEscape(req.Id))
	req.telemetryResource = "quote"
	req.telemetryOperation = "retrieve"

	return send[*QuoteRetrieveResponse](req, s.config)
}

func (s *QuoteService) CreateSubForCustomerQuote(id string, req *QuoteCreateSubForCustomerQuoteRequest) (*QuoteCreateSubForCustomerQuoteResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/customers/%v/create_subscription_quote", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "createSubForCustomerQuote"

	return send[*QuoteCreateSubForCustomerQuoteResponse](req, s.config)
}

func (s *QuoteService) EditCreateSubForCustomerQuote(id string, req *QuoteEditCreateSubForCustomerQuoteRequest) (*QuoteEditCreateSubForCustomerQuoteResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/quotes/%v/edit_create_subscription_quote", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "editCreateSubForCustomerQuote"

	return send[*QuoteEditCreateSubForCustomerQuoteResponse](req, s.config)
}

func (s *QuoteService) UpdateSubscriptionQuote(req *QuoteUpdateSubscriptionQuoteRequest) (*QuoteUpdateSubscriptionQuoteResponse, error) {
	req.method = "POST"
	req.path = "/quotes/update_subscription_quote"
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "updateSubscriptionQuote"

	return send[*QuoteUpdateSubscriptionQuoteResponse](req, s.config)
}

func (s *QuoteService) EditUpdateSubscriptionQuote(id string, req *QuoteEditUpdateSubscriptionQuoteRequest) (*QuoteEditUpdateSubscriptionQuoteResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/quotes/%v/edit_update_subscription_quote", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "editUpdateSubscriptionQuote"

	return send[*QuoteEditUpdateSubscriptionQuoteResponse](req, s.config)
}

func (s *QuoteService) CreateForOnetimeCharges(req *QuoteCreateForOnetimeChargesRequest) (*QuoteCreateForOnetimeChargesResponse, error) {
	req.method = "POST"
	req.path = "/quotes/create_for_onetime_charges"
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "createForOnetimeCharges"

	return send[*QuoteCreateForOnetimeChargesResponse](req, s.config)
}

func (s *QuoteService) EditOneTimeQuote(id string, req *QuoteEditOneTimeQuoteRequest) (*QuoteEditOneTimeQuoteResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/quotes/%v/edit_one_time_quote", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "editOneTimeQuote"

	return send[*QuoteEditOneTimeQuoteResponse](req, s.config)
}

func (s *QuoteService) CreateSubItemsForCustomerQuote(id string, req *QuoteCreateSubItemsForCustomerQuoteRequest) (*QuoteCreateSubItemsForCustomerQuoteResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/customers/%v/create_subscription_quote_for_items", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "createSubItemsForCustomerQuote"

	return send[*QuoteCreateSubItemsForCustomerQuoteResponse](req, s.config)
}

func (s *QuoteService) EditCreateSubCustomerQuoteForItems(id string, req *QuoteEditCreateSubCustomerQuoteForItemsRequest) (*QuoteEditCreateSubCustomerQuoteForItemsResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/quotes/%v/edit_create_subscription_quote_for_items", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "editCreateSubCustomerQuoteForItems"

	return send[*QuoteEditCreateSubCustomerQuoteForItemsResponse](req, s.config)
}

func (s *QuoteService) UpdateSubscriptionQuoteForItems(req *QuoteUpdateSubscriptionQuoteForItemsRequest) (*QuoteUpdateSubscriptionQuoteForItemsResponse, error) {
	req.method = "POST"
	req.path = "/quotes/update_subscription_quote_for_items"
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "updateSubscriptionQuoteForItems"

	return send[*QuoteUpdateSubscriptionQuoteForItemsResponse](req, s.config)
}

func (s *QuoteService) EditUpdateSubscriptionQuoteForItems(id string, req *QuoteEditUpdateSubscriptionQuoteForItemsRequest) (*QuoteEditUpdateSubscriptionQuoteForItemsResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/quotes/%v/edit_update_subscription_quote_for_items", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "editUpdateSubscriptionQuoteForItems"

	return send[*QuoteEditUpdateSubscriptionQuoteForItemsResponse](req, s.config)
}

func (s *QuoteService) CreateForChargeItemsAndCharges(req *QuoteCreateForChargeItemsAndChargesRequest) (*QuoteCreateForChargeItemsAndChargesResponse, error) {
	req.method = "POST"
	req.path = "/quotes/create_for_charge_items_and_charges"
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "createForChargeItemsAndCharges"

	return send[*QuoteCreateForChargeItemsAndChargesResponse](req, s.config)
}

func (s *QuoteService) EditForChargeItemsAndCharges(id string, req *QuoteEditForChargeItemsAndChargesRequest) (*QuoteEditForChargeItemsAndChargesResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/quotes/%v/edit_for_charge_items_and_charges", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "editForChargeItemsAndCharges"

	return send[*QuoteEditForChargeItemsAndChargesResponse](req, s.config)
}

func (s *QuoteService) List(req *QuoteListRequest) (*QuoteListResponse, error) {
	req.method = "GET"
	req.path = "/quotes"
	req.isListRequest = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "list"

	return send[*QuoteListResponse](req, s.config)
}

func (s *QuoteService) QuoteLineGroupsForQuote(id string, req *QuoteQuoteLineGroupsForQuoteRequest) (*QuoteQuoteLineGroupsForQuoteResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/quotes/%v/quote_line_groups", url.PathEscape(id))
	req.isListRequest = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "quoteLineGroupsForQuote"

	return send[*QuoteQuoteLineGroupsForQuoteResponse](req, s.config)
}

func (s *QuoteService) Convert(id string, req *QuoteConvertRequest) (*QuoteConvertResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/quotes/%v/convert", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "convert"

	return send[*QuoteConvertResponse](req, s.config)
}

func (s *QuoteService) UpdateStatus(id string, req *QuoteUpdateStatusRequest) (*QuoteUpdateStatusResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/quotes/%v/update_status", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "updateStatus"

	return send[*QuoteUpdateStatusResponse](req, s.config)
}

func (s *QuoteService) ExtendExpiryDate(id string, req *QuoteExtendExpiryDateRequest) (*QuoteExtendExpiryDateResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/quotes/%v/extend_expiry_date", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "extendExpiryDate"

	return send[*QuoteExtendExpiryDateResponse](req, s.config)
}

func (s *QuoteService) Delete(id string, req *QuoteDeleteRequest) (*QuoteDeleteResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/quotes/%v/delete", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "delete"

	return send[*QuoteDeleteResponse](req, s.config)
}

func (s *QuoteService) Pdf(id string, req *QuotePdfRequest) (*QuotePdfResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/quotes/%v/pdf", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "pdf"

	return send[*QuotePdfResponse](req, s.config)
}

// Deprecated: This function is deprecated.
func (s *QuoteService) RetrieveSignature(req *QuoteRetrieveSignatureRequest) (*QuoteRetrieveSignatureResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/quotes/%v/retrieve_signature", url.PathEscape(req.Id))
	req.telemetryResource = "quote"
	req.telemetryOperation = "retrieveSignature"

	return send[*QuoteRetrieveSignatureResponse](req, s.config)
}

// Deprecated: This function is deprecated.
func (s *QuoteService) RetrieveSignedPdf(req *QuoteRetrieveSignedPdfRequest) (*QuoteRetrieveSignedPdfResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/quotes/%v/retrieve_signed_pdf", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "retrieveSignedPdf"

	return send[*QuoteRetrieveSignedPdfResponse](req, s.config)
}

// Deprecated: This function is deprecated.
func (s *QuoteService) CreateSignature(req *QuoteCreateSignatureRequest) (*QuoteCreateSignatureResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/quotes/%v/create_signature", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "createSignature"

	return send[*QuoteCreateSignatureResponse](req, s.config)
}

// Deprecated: This function is deprecated.
func (s *QuoteService) UpdateSignature(req *QuoteUpdateSignatureRequest) (*QuoteUpdateSignatureResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/quotes/%v/update_signature", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "updateSignature"

	return send[*QuoteUpdateSignatureResponse](req, s.config)
}

// Deprecated: This function is deprecated.
func (s *QuoteService) UpdateSignatureStatus(id string, req *QuoteUpdateSignatureStatusRequest) (*QuoteUpdateSignatureStatusResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/quotes/%v/update_signature_status", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "updateSignatureStatus"

	return send[*QuoteUpdateSignatureStatusResponse](req, s.config)
}

// Deprecated: This function is deprecated.
func (s *QuoteService) RefreshSignatureLink(req *QuoteRefreshSignatureLinkRequest) (*QuoteRefreshSignatureLinkResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/quotes/%v/refresh_signature_link", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "quote"
	req.telemetryOperation = "refreshSignatureLink"

	return send[*QuoteRefreshSignatureLinkResponse](req, s.config)
}
