// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type QuotedDeltaRamp struct {
	LineItems []*QuotedDeltaRampLineItem `json:"line_items"`
	Object    string                     `json:"object"`
}

type QuotedDeltaRampLineItem struct {
	ItemLevelDiscountPerBillingCycleInDecimal string `json:"item_level_discount_per_billing_cycle_in_decimal"`
	Object                                    string `json:"object"`
}
