// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type RampService struct {
	config *ClientConfig
}

func (s *RampService) CreateForSubscription(id string, req *RampCreateForSubscriptionRequest) (*RampCreateForSubscriptionResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/subscriptions/%v/create_ramp", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "ramp"
	req.telemetryOperation = "createForSubscription"

	return send[*RampCreateForSubscriptionResponse](req, s.config)
}

func (s *RampService) Update(id string, req *RampUpdateRequest) (*RampUpdateResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/ramps/%v/update", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "ramp"
	req.telemetryOperation = "update"

	return send[*RampUpdateResponse](req, s.config)
}

func (s *RampService) Retrieve(id string) (*RampRetrieveResponse, error) {
	req := &BlankRequest{}
	req.method = "GET"
	req.path = fmt.Sprintf("/ramps/%v", url.PathEscape(id))
	req.telemetryResource = "ramp"
	req.telemetryOperation = "retrieve"

	return send[*RampRetrieveResponse](req, s.config)
}

func (s *RampService) Delete(id string) (*RampDeleteResponse, error) {
	req := &BlankRequest{}
	req.method = "POST"
	req.path = fmt.Sprintf("/ramps/%v/delete", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "ramp"
	req.telemetryOperation = "delete"

	return send[*RampDeleteResponse](req, s.config)
}

func (s *RampService) List(req *RampListRequest) (*RampListResponse, error) {
	req.method = "GET"
	req.path = "/ramps"
	req.isListRequest = true
	req.telemetryResource = "ramp"
	req.telemetryOperation = "list"

	return send[*RampListResponse](req, s.config)
}
