// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

type ResourceMigrationService struct {
	config *ClientConfig
}

func (s *ResourceMigrationService) RetrieveLatest(req *ResourceMigrationRetrieveLatestRequest) (*ResourceMigrationRetrieveLatestResponse, error) {
	req.method = "GET"
	req.path = "/resource_migrations/retrieve_latest"
	return send[*ResourceMigrationRetrieveLatestResponse](req, s.config)
}
