// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type RuleService struct {
	config *ClientConfig
}

func (s *RuleService) Retrieve(req *RuleRetrieveRequest) (*RuleRetrieveResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/rules/%v", url.PathEscape(req.Id))
	req.telemetryResource = "rule"
	req.telemetryOperation = "retrieve"

	return send[*RuleRetrieveResponse](req, s.config)
}
