// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

type SiteMigrationDetailService struct {
	config *ClientConfig
}

func (s *SiteMigrationDetailService) List(req *SiteMigrationDetailListRequest) (*SiteMigrationDetailListResponse, error) {
	req.method = "GET"
	req.path = "/site_migration_details"
	req.isListRequest = true
	req.telemetryResource = "siteMigrationDetail"
	req.telemetryOperation = "list"

	return send[*SiteMigrationDetailListResponse](req, s.config)
}
