// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type TaxWithheldType string

const (
	TaxWithheldTypePayment TaxWithheldType = "payment"
	TaxWithheldTypeRefund  TaxWithheldType = "refund"
)

type TaxWithheldPaymentMethod string

const (
	TaxWithheldPaymentMethodCash         TaxWithheldPaymentMethod = "cash"
	TaxWithheldPaymentMethodCheck        TaxWithheldPaymentMethod = "check"
	TaxWithheldPaymentMethodChargeback   TaxWithheldPaymentMethod = "chargeback"
	TaxWithheldPaymentMethodBankTransfer TaxWithheldPaymentMethod = "bank_transfer"
	TaxWithheldPaymentMethodOther        TaxWithheldPaymentMethod = "other"
)

type TaxWithheld struct {
	Id              string `json:"id"`
	ReferenceNumber string `json:"reference_number"`
	Description     string `json:"description"`
	Date            int64  `json:"date"`
	Amount          int64  `json:"amount"`
	ResourceVersion int64  `json:"resource_version"`
	UpdatedAt       int64  `json:"updated_at"`
	Object          string `json:"object"`
}
