// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

import (
	"encoding/json"
)

type ThirdPartyPaymentMethod struct {
	Type                        Type            `json:"type"`
	Gateway                     Gateway         `json:"gateway"`
	GatewayAccountId            string          `json:"gateway_account_id"`
	ReferenceId                 string          `json:"reference_id"`
	NetworkTransactionReference json.RawMessage `json:"network_transaction_reference"`
	Object                      string          `json:"object"`
}
