// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type TimeMachineTimeTravelStatus string

const (
	TimeMachineTimeTravelStatusNotEnabled TimeMachineTimeTravelStatus = "not_enabled"
	TimeMachineTimeTravelStatusInProgress TimeMachineTimeTravelStatus = "in_progress"
	TimeMachineTimeTravelStatusSucceeded  TimeMachineTimeTravelStatus = "succeeded"
	TimeMachineTimeTravelStatusFailed     TimeMachineTimeTravelStatus = "failed"
)

type TimeMachine struct {
	Name             string                      `json:"name"`
	TimeTravelStatus TimeMachineTimeTravelStatus `json:"time_travel_status"`
	GenesisTime      int64                       `json:"genesis_time"`
	DestinationTime  int64                       `json:"destination_time"`
	FailureCode      string                      `json:"failure_code"`
	FailureReason    string                      `json:"failure_reason"`
	ErrorJson        string                      `json:"error_json"`
	Object           string                      `json:"object"`
}

type TimeMachineStartAfreshRequest struct {
	GenesisTime *int64 `json:"genesis_time,omitempty"`
	apiRequest  `json:"-" form:"-"`
}

func (r *TimeMachineStartAfreshRequest) payload() any { return r }

type TimeMachineTravelForwardRequest struct {
	DestinationTime *int64 `json:"destination_time,omitempty"`
	apiRequest      `json:"-" form:"-"`
}

func (r *TimeMachineTravelForwardRequest) payload() any { return r }

type TimeMachineRetrieveResponse struct {
	TimeMachine *TimeMachine `json:"time_machine,omitempty"`
	apiResponse
}

type TimeMachineStartAfreshResponse struct {
	TimeMachine *TimeMachine `json:"time_machine,omitempty"`
	apiResponse
}

type TimeMachineTravelForwardResponse struct {
	TimeMachine *TimeMachine `json:"time_machine,omitempty"`
	apiResponse
}
