// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type TransactionService struct {
	config *ClientConfig
}

func (s *TransactionService) CreateAuthorization(req *TransactionCreateAuthorizationRequest) (*TransactionCreateAuthorizationResponse, error) {
	req.method = "POST"
	req.path = "/transactions/create_authorization"
	req.isIdempotent = true
	req.telemetryResource = "transaction"
	req.telemetryOperation = "createAuthorization"

	return send[*TransactionCreateAuthorizationResponse](req, s.config)
}

func (s *TransactionService) VoidTransaction(req *TransactionVoidTransactionRequest) (*TransactionVoidTransactionResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/transactions/%v/void", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "transaction"
	req.telemetryOperation = "voidTransaction"

	return send[*TransactionVoidTransactionResponse](req, s.config)
}

func (s *TransactionService) RecordRefund(id string, req *TransactionRecordRefundRequest) (*TransactionRecordRefundResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/transactions/%v/record_refund", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "transaction"
	req.telemetryOperation = "recordRefund"

	return send[*TransactionRecordRefundResponse](req, s.config)
}

func (s *TransactionService) Reconcile(id string, req *TransactionReconcileRequest) (*TransactionReconcileResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/transactions/%v/reconcile", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "transaction"
	req.telemetryOperation = "reconcile"

	return send[*TransactionReconcileResponse](req, s.config)
}

func (s *TransactionService) Refund(id string, req *TransactionRefundRequest) (*TransactionRefundResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/transactions/%v/refund", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "transaction"
	req.telemetryOperation = "refund"

	return send[*TransactionRefundResponse](req, s.config)
}

func (s *TransactionService) List(req *TransactionListRequest) (*TransactionListResponse, error) {
	req.method = "GET"
	req.path = "/transactions"
	req.isListRequest = true
	req.telemetryResource = "transaction"
	req.telemetryOperation = "list"

	return send[*TransactionListResponse](req, s.config)
}

// Deprecated: This function is deprecated.
func (s *TransactionService) TransactionsForCustomer(id string, req *TransactionTransactionsForCustomerRequest) (*TransactionTransactionsForCustomerResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/customers/%v/transactions", url.PathEscape(id))
	req.isListRequest = true
	req.telemetryResource = "transaction"
	req.telemetryOperation = "transactionsForCustomer"

	return send[*TransactionTransactionsForCustomerResponse](req, s.config)
}

// Deprecated: This function is deprecated.
func (s *TransactionService) TransactionsForSubscription(id string, req *TransactionTransactionsForSubscriptionRequest) (*TransactionTransactionsForSubscriptionResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/subscriptions/%v/transactions", url.PathEscape(id))
	req.isListRequest = true
	req.telemetryResource = "transaction"
	req.telemetryOperation = "transactionsForSubscription"

	return send[*TransactionTransactionsForSubscriptionResponse](req, s.config)
}

func (s *TransactionService) PaymentsForInvoice(id string, req *TransactionPaymentsForInvoiceRequest) (*TransactionPaymentsForInvoiceResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/invoices/%v/payments", url.PathEscape(id))
	req.isListRequest = true
	req.telemetryResource = "transaction"
	req.telemetryOperation = "paymentsForInvoice"

	return send[*TransactionPaymentsForInvoiceResponse](req, s.config)
}

func (s *TransactionService) Retrieve(req *TransactionRetrieveRequest) (*TransactionRetrieveResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/transactions/%v", url.PathEscape(req.Id))
	req.telemetryResource = "transaction"
	req.telemetryOperation = "retrieve"

	return send[*TransactionRetrieveResponse](req, s.config)
}

func (s *TransactionService) DeleteOfflineTransaction(id string, req *TransactionDeleteOfflineTransactionRequest) (*TransactionDeleteOfflineTransactionResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/transactions/%v/delete_offline_transaction", url.PathEscape(id))
	req.isIdempotent = true
	req.telemetryResource = "transaction"
	req.telemetryOperation = "deleteOfflineTransaction"

	return send[*TransactionDeleteOfflineTransactionResponse](req, s.config)
}
