// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type UnbilledChargeEntityType string

const (
	UnbilledChargeEntityTypeAdhoc           UnbilledChargeEntityType = "adhoc"
	UnbilledChargeEntityTypePlanItemPrice   UnbilledChargeEntityType = "plan_item_price"
	UnbilledChargeEntityTypeAddonItemPrice  UnbilledChargeEntityType = "addon_item_price"
	UnbilledChargeEntityTypeChargeItemPrice UnbilledChargeEntityType = "charge_item_price"
	UnbilledChargeEntityTypePlanSetup       UnbilledChargeEntityType = "plan_setup"
	UnbilledChargeEntityTypePlan            UnbilledChargeEntityType = "plan"
	UnbilledChargeEntityTypeAddon           UnbilledChargeEntityType = "addon"
)

type UnbilledCharge struct {
	Id                  string                   `json:"id"`
	CustomerId          string                   `json:"customer_id"`
	SubscriptionId      string                   `json:"subscription_id"`
	DateFrom            int64                    `json:"date_from"`
	DateTo              int64                    `json:"date_to"`
	UnitAmount          int64                    `json:"unit_amount"`
	PricingModel        PricingModel             `json:"pricing_model"`
	Quantity            int32                    `json:"quantity"`
	Amount              int64                    `json:"amount"`
	CurrencyCode        string                   `json:"currency_code"`
	DiscountAmount      int64                    `json:"discount_amount"`
	Description         string                   `json:"description"`
	EntityType          UnbilledChargeEntityType `json:"entity_type"`
	EntityId            string                   `json:"entity_id"`
	IsVoided            bool                     `json:"is_voided"`
	VoidedAt            int64                    `json:"voided_at"`
	UnitAmountInDecimal string                   `json:"unit_amount_in_decimal"`
	QuantityInDecimal   string                   `json:"quantity_in_decimal"`
	AmountInDecimal     string                   `json:"amount_in_decimal"`
	UpdatedAt           int64                    `json:"updated_at"`
	Tiers               []*UnbilledChargeTier    `json:"tiers"`
	IsAdvanceCharge     bool                     `json:"is_advance_charge"`
	BusinessEntityId    string                   `json:"business_entity_id"`
	Deleted             bool                     `json:"deleted"`
	Object              string                   `json:"object"`
}

type UnbilledChargeTier struct {
	StartingUnit          int32       `json:"starting_unit"`
	EndingUnit            int32       `json:"ending_unit"`
	QuantityUsed          int32       `json:"quantity_used"`
	UnitAmount            int64       `json:"unit_amount"`
	StartingUnitInDecimal string      `json:"starting_unit_in_decimal"`
	EndingUnitInDecimal   string      `json:"ending_unit_in_decimal"`
	QuantityUsedInDecimal string      `json:"quantity_used_in_decimal"`
	UnitAmountInDecimal   string      `json:"unit_amount_in_decimal"`
	PricingType           PricingType `json:"pricing_type"`
	PackageSize           int32       `json:"package_size"`
	Object                string      `json:"object"`
}

type UnbilledChargeCreateUnbilledChargeRequest struct {
	SubscriptionId     string                                                 `json:"subscription_id"`
	CurrencyCode       string                                                 `json:"currency_code,omitempty"`
	Addons             []*UnbilledChargeCreateUnbilledChargeAddon             `json:"addons,omitempty"`
	Charges            []*UnbilledChargeCreateUnbilledChargeCharge            `json:"charges,omitempty"`
	TaxProvidersFields []*UnbilledChargeCreateUnbilledChargeTaxProvidersField `json:"tax_providers_fields,omitempty"`
	apiRequest         `json:"-" form:"-"`
}

func (r *UnbilledChargeCreateUnbilledChargeRequest) payload() any { return r }

type UnbilledChargeCreateUnbilledChargeAddon struct {
	Id                 string `json:"id,omitempty"`
	Quantity           *int32 `json:"quantity,omitempty"`
	UnitPrice          *int64 `json:"unit_price,omitempty"`
	QuantityInDecimal  string `json:"quantity_in_decimal,omitempty"`
	UnitPriceInDecimal string `json:"unit_price_in_decimal,omitempty"`
	DateFrom           *int64 `json:"date_from,omitempty"`
	DateTo             *int64 `json:"date_to,omitempty"`
}

type UnbilledChargeCreateUnbilledChargeCharge struct {
	Amount                 *int64          `json:"amount,omitempty"`
	AmountInDecimal        string          `json:"amount_in_decimal,omitempty"`
	Description            string          `json:"description,omitempty"`
	Taxable                *bool           `json:"taxable,omitempty"`
	TaxProfileId           string          `json:"tax_profile_id,omitempty"`
	AvalaraTaxCode         string          `json:"avalara_tax_code,omitempty"`
	HsnCode                string          `json:"hsn_code,omitempty"`
	TaxjarProductCode      string          `json:"taxjar_product_code,omitempty"`
	AvalaraSaleType        AvalaraSaleType `json:"avalara_sale_type,omitempty"`
	AvalaraTransactionType *int32          `json:"avalara_transaction_type,omitempty"`
	AvalaraServiceType     *int32          `json:"avalara_service_type,omitempty"`
	DateFrom               *int64          `json:"date_from,omitempty"`
	DateTo                 *int64          `json:"date_to,omitempty"`
}

type UnbilledChargeCreateUnbilledChargeTaxProvidersField struct {
	ProviderName string `json:"provider_name,omitempty"`
	FieldId      string `json:"field_id,omitempty"`
	FieldValue   string `json:"field_value,omitempty"`
}

type UnbilledChargeCreateRequest struct {
	SubscriptionId     string                                   `json:"subscription_id"`
	CurrencyCode       string                                   `json:"currency_code,omitempty"`
	ItemPrices         []*UnbilledChargeCreateItemPrice         `json:"item_prices,omitempty"`
	ItemTiers          []*UnbilledChargeCreateItemTier          `json:"item_tiers,omitempty"`
	Charges            []*UnbilledChargeCreateCharge            `json:"charges,omitempty"`
	TaxProvidersFields []*UnbilledChargeCreateTaxProvidersField `json:"tax_providers_fields,omitempty"`
	apiRequest         `json:"-" form:"-"`
}

func (r *UnbilledChargeCreateRequest) payload() any { return r }

type UnbilledChargeCreateItemPrice struct {
	ItemPriceId        string `json:"item_price_id,omitempty"`
	Quantity           *int32 `json:"quantity,omitempty"`
	QuantityInDecimal  string `json:"quantity_in_decimal,omitempty"`
	UnitPrice          *int64 `json:"unit_price,omitempty"`
	UnitPriceInDecimal string `json:"unit_price_in_decimal,omitempty"`
	DateFrom           *int64 `json:"date_from,omitempty"`
	DateTo             *int64 `json:"date_to,omitempty"`
}

type UnbilledChargeCreateItemTier struct {
	ItemPriceId           string      `json:"item_price_id,omitempty"`
	StartingUnit          *int32      `json:"starting_unit,omitempty"`
	EndingUnit            *int32      `json:"ending_unit,omitempty"`
	Price                 *int64      `json:"price,omitempty"`
	StartingUnitInDecimal string      `json:"starting_unit_in_decimal,omitempty"`
	EndingUnitInDecimal   string      `json:"ending_unit_in_decimal,omitempty"`
	PriceInDecimal        string      `json:"price_in_decimal,omitempty"`
	PricingType           PricingType `json:"pricing_type,omitempty"`
	PackageSize           *int32      `json:"package_size,omitempty"`
}

type UnbilledChargeCreateCharge struct {
	Amount                 *int64          `json:"amount,omitempty"`
	AmountInDecimal        string          `json:"amount_in_decimal,omitempty"`
	Description            string          `json:"description,omitempty"`
	Taxable                *bool           `json:"taxable,omitempty"`
	TaxProfileId           string          `json:"tax_profile_id,omitempty"`
	AvalaraTaxCode         string          `json:"avalara_tax_code,omitempty"`
	HsnCode                string          `json:"hsn_code,omitempty"`
	TaxjarProductCode      string          `json:"taxjar_product_code,omitempty"`
	AvalaraSaleType        AvalaraSaleType `json:"avalara_sale_type,omitempty"`
	AvalaraTransactionType *int32          `json:"avalara_transaction_type,omitempty"`
	AvalaraServiceType     *int32          `json:"avalara_service_type,omitempty"`
	DateFrom               *int64          `json:"date_from,omitempty"`
	DateTo                 *int64          `json:"date_to,omitempty"`
}

type UnbilledChargeCreateTaxProvidersField struct {
	ProviderName string `json:"provider_name,omitempty"`
	FieldId      string `json:"field_id,omitempty"`
	FieldValue   string `json:"field_value,omitempty"`
}

type UnbilledChargeInvoiceUnbilledChargesRequest struct {
	SubscriptionId string `json:"subscription_id,omitempty"`
	CustomerId     string `json:"customer_id,omitempty"`
	apiRequest     `json:"-" form:"-"`
}

func (r *UnbilledChargeInvoiceUnbilledChargesRequest) payload() any { return r }

type UnbilledChargeListRequest struct {
	Limit          *int32        `json:"limit,omitempty"`
	Offset         string        `json:"offset,omitempty"`
	IncludeDeleted *bool         `json:"include_deleted,omitempty"`
	IsVoided       *bool         `json:"is_voided,omitempty"`
	SubscriptionId *StringFilter `json:"subscription_id,omitempty"`
	CustomerId     *StringFilter `json:"customer_id,omitempty"`
	apiRequest     `json:"-" form:"-"`
}

func (r *UnbilledChargeListRequest) payload() any { return r }

type UnbilledChargeInvoiceNowEstimateRequest struct {
	SubscriptionId string `json:"subscription_id,omitempty"`
	CustomerId     string `json:"customer_id,omitempty"`
	apiRequest     `json:"-" form:"-"`
}

func (r *UnbilledChargeInvoiceNowEstimateRequest) payload() any { return r }

type UnbilledChargeCreateUnbilledChargeResponse struct {
	UnbilledCharges []*UnbilledCharge `json:"unbilled_charges,omitempty"`
	apiResponse
}

type UnbilledChargeCreateResponse struct {
	UnbilledCharges []*UnbilledCharge `json:"unbilled_charges,omitempty"`
	apiResponse
}

type UnbilledChargeInvoiceUnbilledChargesResponse struct {
	Invoices []Invoice `json:"invoices,omitempty"`
	apiResponse
}

type UnbilledChargeDeleteResponse struct {
	UnbilledCharge *UnbilledCharge `json:"unbilled_charge,omitempty"`
	apiResponse
}

type UnbilledChargeListUnbilledChargeResponse struct {
	UnbilledCharge *UnbilledCharge `json:"unbilled_charge,omitempty"`
}

type UnbilledChargeListResponse struct {
	List       []*UnbilledChargeListUnbilledChargeResponse `json:"list,omitempty"`
	NextOffset string                                      `json:"next_offset,omitempty"`
	apiResponse
}

type UnbilledChargeInvoiceNowEstimateResponse struct {
	Estimate Estimate `json:"estimate,omitempty"`
	apiResponse
}
