// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type UsageCharge struct {
	SubscriptionId     string `json:"subscription_id"`
	FeatureId          string `json:"feature_id"`
	IncludedUsage      string `json:"included_usage"`
	TotalUsage         string `json:"total_usage"`
	OnDemandUsage      string `json:"on_demand_usage"`
	MeteredItemPriceId string `json:"metered_item_price_id"`
	Amount             string `json:"amount"`
	CurrencyCode       string `json:"currency_code"`
	UsageFrom          int64  `json:"usage_from"`
	UsageTo            int64  `json:"usage_to"`
	Object             string `json:"object"`
}

type UsageChargeRetrieveUsageChargesForSubscriptionRequest struct {
	Limit      *int32        `json:"limit,omitempty"`
	Offset     string        `json:"offset,omitempty"`
	FeatureId  *StringFilter `json:"feature_id,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *UsageChargeRetrieveUsageChargesForSubscriptionRequest) payload() any { return r }

type UsageChargeRetrieveUsageChargesForSubscriptionUsageChargeResponse struct {
	UsageCharge *UsageCharge `json:"usage_charge,omitempty"`
}

type UsageChargeRetrieveUsageChargesForSubscriptionResponse struct {
	List       []*UsageChargeRetrieveUsageChargesForSubscriptionUsageChargeResponse `json:"list,omitempty"`
	NextOffset string                                                               `json:"next_offset,omitempty"`
	apiResponse
}
