// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type UsageSummaryService struct {
	config *ClientConfig
}

// Deprecated: This function is deprecated.
func (s *UsageSummaryService) RetrieveUsageSummaryForSubscription(id string, req *UsageSummaryRetrieveUsageSummaryForSubscriptionRequest) (*UsageSummaryRetrieveUsageSummaryForSubscriptionResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/subscriptions/%v/usage_summary", url.PathEscape(id))
	req.isListRequest = true
	return send[*UsageSummaryRetrieveUsageSummaryForSubscriptionResponse](req, s.config)
}
