// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

type UsageEventService struct {
	config *ClientConfig
}

func (s *UsageEventService) Create(req *UsageEventCreateRequest) (*UsageEventCreateResponse, error) {
	req.method = "POST"
	req.path = "/usage_events"
	req.isJsonRequest = true
	return send[*UsageEventCreateResponse](req, s.config)
}

func (s *UsageEventService) BatchIngest(req *UsageEventBatchIngestRequest) (*UsageEventBatchIngestResponse, error) {
	req.method = "POST"
	req.path = "/batch/usage_events"
	req.isJsonRequest = true
	return send[*UsageEventBatchIngestResponse](req, s.config)
}
