// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type VaultedPaymentMethodService struct {
	config *ClientConfig
}

func (s *VaultedPaymentMethodService) Retrieve(id string) (*VaultedPaymentMethodRetrieveResponse, error) {
	req := &BlankRequest{}
	req.method = "GET"
	req.path = fmt.Sprintf("/vaulted_payment_methods/%v", url.PathEscape(id))
	req.telemetryResource = "vaultedPaymentMethod"
	req.telemetryOperation = "retrieve"

	return send[*VaultedPaymentMethodRetrieveResponse](req, s.config)
}
