// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type VaultedPaymentMethod struct {
	Id           string `json:"id"`
	CustomerId   string `json:"customer_id"`
	CreditCardId string `json:"credit_card_id"`
	CreatedAt    int64  `json:"created_at"`
	ModifiedAt   int64  `json:"modified_at"`
	Object       string `json:"object"`
}

type VaultedPaymentMethodRetrieveRequest struct {
	Id         string `json:"-" form:"-"`
	apiRequest `json:"-" form:"-"`
}

func (r *VaultedPaymentMethodRetrieveRequest) payload() any { return r }

type VaultedPaymentMethodRetrieveResponse struct {
	VaultedPaymentMethod *VaultedPaymentMethod `json:"vaulted_payment_method,omitempty"`
	apiResponse
}
