// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type VirtualBankAccountService struct {
	config *ClientConfig
}

func (s *VirtualBankAccountService) CreateUsingPermanentToken(req *VirtualBankAccountCreateUsingPermanentTokenRequest) (*VirtualBankAccountCreateUsingPermanentTokenResponse, error) {
	req.method = "POST"
	req.path = "/virtual_bank_accounts/create_using_permanent_token"
	req.isIdempotent = true
	req.telemetryResource = "virtualBankAccount"
	req.telemetryOperation = "createUsingPermanentToken"

	return send[*VirtualBankAccountCreateUsingPermanentTokenResponse](req, s.config)
}

func (s *VirtualBankAccountService) Create(req *VirtualBankAccountCreateRequest) (*VirtualBankAccountCreateResponse, error) {
	req.method = "POST"
	req.path = "/virtual_bank_accounts"
	req.isIdempotent = true
	req.telemetryResource = "virtualBankAccount"
	req.telemetryOperation = "create"

	return send[*VirtualBankAccountCreateResponse](req, s.config)
}

func (s *VirtualBankAccountService) Retrieve(req *VirtualBankAccountRetrieveRequest) (*VirtualBankAccountRetrieveResponse, error) {
	req.method = "GET"
	req.path = fmt.Sprintf("/virtual_bank_accounts/%v", url.PathEscape(req.Id))
	req.telemetryResource = "virtualBankAccount"
	req.telemetryOperation = "retrieve"

	return send[*VirtualBankAccountRetrieveResponse](req, s.config)
}

func (s *VirtualBankAccountService) List(req *VirtualBankAccountListRequest) (*VirtualBankAccountListResponse, error) {
	req.method = "GET"
	req.path = "/virtual_bank_accounts"
	req.isListRequest = true
	req.telemetryResource = "virtualBankAccount"
	req.telemetryOperation = "list"

	return send[*VirtualBankAccountListResponse](req, s.config)
}

func (s *VirtualBankAccountService) Delete(req *VirtualBankAccountDeleteRequest) (*VirtualBankAccountDeleteResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/virtual_bank_accounts/%v/delete", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "virtualBankAccount"
	req.telemetryOperation = "delete"

	return send[*VirtualBankAccountDeleteResponse](req, s.config)
}

func (s *VirtualBankAccountService) DeleteLocal(req *VirtualBankAccountDeleteLocalRequest) (*VirtualBankAccountDeleteLocalResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/virtual_bank_accounts/%v/delete_local", url.PathEscape(req.Id))
	req.isIdempotent = true
	req.telemetryResource = "virtualBankAccount"
	req.telemetryOperation = "deleteLocal"

	return send[*VirtualBankAccountDeleteLocalResponse](req, s.config)
}
