// Code generated by sdk-generator. DO NOT EDIT.

package chargebee

import (
	"fmt"
	"net/url"
)

type WebhookEndpointService struct {
	config *ClientConfig
}

func (s *WebhookEndpointService) Create(req *WebhookEndpointCreateRequest) (*WebhookEndpointCreateResponse, error) {
	req.method = "POST"
	req.path = "/webhook_endpoints"
	req.isIdempotent = true
	return send[*WebhookEndpointCreateResponse](req, s.config)
}

func (s *WebhookEndpointService) Update(id string, req *WebhookEndpointUpdateRequest) (*WebhookEndpointUpdateResponse, error) {
	req.method = "POST"
	req.path = fmt.Sprintf("/webhook_endpoints/%v", url.PathEscape(id))
	req.isIdempotent = true
	return send[*WebhookEndpointUpdateResponse](req, s.config)
}

func (s *WebhookEndpointService) Retrieve(id string) (*WebhookEndpointRetrieveResponse, error) {
	req := &BlankRequest{}
	req.method = "GET"
	req.path = fmt.Sprintf("/webhook_endpoints/%v", url.PathEscape(id))
	return send[*WebhookEndpointRetrieveResponse](req, s.config)
}

func (s *WebhookEndpointService) Delete(id string) (*WebhookEndpointDeleteResponse, error) {
	req := &BlankRequest{}
	req.method = "POST"
	req.path = fmt.Sprintf("/webhook_endpoints/%v/delete", url.PathEscape(id))
	req.isIdempotent = true
	return send[*WebhookEndpointDeleteResponse](req, s.config)
}

func (s *WebhookEndpointService) List(req *WebhookEndpointListRequest) (*WebhookEndpointListResponse, error) {
	req.method = "GET"
	req.path = "/webhook_endpoints"
	req.isListRequest = true
	return send[*WebhookEndpointListResponse](req, s.config)
}
