// Code generated by sdk-generator; DO NOT EDIT.
package chargebee

type WebhookEndpointApiVersion string

const (
	WebhookEndpointApiVersionV1 WebhookEndpointApiVersion = "v1"
	WebhookEndpointApiVersionV2 WebhookEndpointApiVersion = "v2"
)

type WebhookEndpoint struct {
	Id                          string                      `json:"id"`
	Name                        string                      `json:"name"`
	Url                         string                      `json:"url"`
	SendCardResource            bool                        `json:"send_card_resource"`
	Disabled                    bool                        `json:"disabled"`
	PrimaryUrl                  bool                        `json:"primary_url"`
	ApiVersion                  WebhookEndpointApiVersion   `json:"api_version"`
	ChargebeeResponseSchemaType ChargebeeResponseSchemaType `json:"chargebee_response_schema_type"`
	EnabledEvents               []EventType                 `json:"enabled_events"`
	Object                      string                      `json:"object"`
}

type WebhookEndpointCreateRequest struct {
	Name                        string                      `json:"name"`
	ApiVersion                  WebhookEndpointApiVersion   `json:"api_version,omitempty"`
	Url                         string                      `json:"url"`
	PrimaryUrl                  *bool                       `json:"primary_url,omitempty"`
	Disabled                    *bool                       `json:"disabled,omitempty"`
	BasicAuthPassword           string                      `json:"basic_auth_password,omitempty"`
	BasicAuthUsername           string                      `json:"basic_auth_username,omitempty"`
	SendCardResource            *bool                       `json:"send_card_resource,omitempty"`
	ChargebeeResponseSchemaType ChargebeeResponseSchemaType `json:"chargebee_response_schema_type,omitempty"`
	EnabledEvents               EventType                   `json:"enabled_events,omitempty"`
	apiRequest                  `json:"-" form:"-"`
}

func (r *WebhookEndpointCreateRequest) payload() any { return r }

type WebhookEndpointUpdateRequest struct {
	Name              string                    `json:"name,omitempty"`
	ApiVersion        WebhookEndpointApiVersion `json:"api_version,omitempty"`
	Url               string                    `json:"url,omitempty"`
	PrimaryUrl        *bool                     `json:"primary_url,omitempty"`
	SendCardResource  *bool                     `json:"send_card_resource,omitempty"`
	BasicAuthPassword string                    `json:"basic_auth_password,omitempty"`
	BasicAuthUsername string                    `json:"basic_auth_username,omitempty"`
	Disabled          *bool                     `json:"disabled,omitempty"`
	EnabledEvents     EventType                 `json:"enabled_events,omitempty"`
	apiRequest        `json:"-" form:"-"`
}

func (r *WebhookEndpointUpdateRequest) payload() any { return r }

type WebhookEndpointListRequest struct {
	Limit      *int32 `json:"limit,omitempty"`
	Offset     string `json:"offset,omitempty"`
	apiRequest `json:"-" form:"-"`
}

func (r *WebhookEndpointListRequest) payload() any { return r }

type WebhookEndpointCreateResponse struct {
	WebhookEndpoint *WebhookEndpoint `json:"webhook_endpoint,omitempty"`
	apiResponse
}

type WebhookEndpointUpdateResponse struct {
	WebhookEndpoint *WebhookEndpoint `json:"webhook_endpoint,omitempty"`
	apiResponse
}

type WebhookEndpointRetrieveResponse struct {
	WebhookEndpoint *WebhookEndpoint `json:"webhook_endpoint,omitempty"`
	apiResponse
}

type WebhookEndpointDeleteResponse struct {
	WebhookEndpoint *WebhookEndpoint `json:"webhook_endpoint,omitempty"`
	apiResponse
}

type WebhookEndpointListWebhookEndpointResponse struct {
	WebhookEndpoint *WebhookEndpoint `json:"webhook_endpoint,omitempty"`
}

type WebhookEndpointListResponse struct {
	List       []*WebhookEndpointListWebhookEndpointResponse `json:"list,omitempty"`
	NextOffset string                                        `json:"next_offset,omitempty"`
	apiResponse
}
