// This file is auto-generated by Chargebee.
// For more information on how to make changes to this file, please see the README.
// Reach out to dx@chargebee.com for any questions.
// Copyright 2026 Chargebee Inc.

package telemetry

// RequestTelemetryContext is context passed to TelemetryAdapter.OnRequestStart.
type RequestTelemetryContext struct {
	SpanName            string
	Resource            string
	Operation           string
	HTTPMethod          string
	HTTPURL             string
	ServerAddress       string
	ChargebeeSite       string
	ChargebeeAPIVersion string
	SDKName             string
	SDKVersion          string
	// StartAttributes are prebuilt span attributes — pass these to your tracer.
	StartAttributes map[string]string
}
