// This file is auto-generated by Chargebee.
// For more information on how to make changes to this file, please see the README.
// Reach out to dx@chargebee.com for any questions.
// Copyright 2026 Chargebee Inc.

package telemetry

// Helpers for building standardized Chargebee telemetry context and results.

// BuildSpanName returns the standardized Chargebee span name.
func BuildSpanName(resource, operation string) string {
	return TelemetrySpanNamePrefix + "." + resource + "." + operation
}

// ResolveChargebeeAPIVersion maps an API path to a version label.
func ResolveChargebeeAPIVersion(apiPath string) string {
	if apiPath == "/api/v1" {
		return "v1"
	}
	return "v2"
}

// BuildRequestStartSpanAttributes builds standardized start span attributes.
func BuildRequestStartSpanAttributes(
	resource, operation, httpMethod, httpURL, serverAddress, chargebeeSite, chargebeeAPIVersion, sdkVersion string,
) map[string]string {
	return map[string]string{
		URLFull:             httpURL,
		HTTPRequestMethod:   httpMethod,
		ServerAddress:       serverAddress,
		ChargebeeSite:       chargebeeSite,
		ChargebeeAPIVersion: chargebeeAPIVersion,
		ChargebeeResource:   resource,
		ChargebeeOperation:  operation,
		ChargebeeSDKName:    SDKName,
		ChargebeeSDKVersion: sdkVersion,
	}
}

// BuildRequestEndSpanAttributes builds standardized end span attributes.
func BuildRequestEndSpanAttributes(httpStatusCode int, err *RequestTelemetryError) map[string]interface{} {
	attributes := map[string]interface{}{
		HTTPResponseStatusCode: httpStatusCode,
	}
	if err != nil {
		attributes[ErrorType] = httpStatusCode
		if err.ChargebeeErrorCode != "" {
			attributes[ChargebeeErrorCode] = err.ChargebeeErrorCode
		}
		if err.ChargebeeAPIErrorType != "" {
			attributes[ChargebeeErrorType] = err.ChargebeeAPIErrorType
		}
		if err.ChargebeeErrorParam != "" {
			attributes[ChargebeeErrorParam] = err.ChargebeeErrorParam
		}
	}
	return attributes
}

// BuildRequestTelemetryContext builds a RequestTelemetryContext.
func BuildRequestTelemetryContext(
	resource, operation, httpMethod, httpURL, serverAddress, chargebeeSite, chargebeeAPIVersion, sdkVersion string,
) RequestTelemetryContext {
	return RequestTelemetryContext{
		SpanName:            BuildSpanName(resource, operation),
		Resource:            resource,
		Operation:           operation,
		HTTPMethod:          httpMethod,
		HTTPURL:             httpURL,
		ServerAddress:       serverAddress,
		ChargebeeSite:       chargebeeSite,
		ChargebeeAPIVersion: chargebeeAPIVersion,
		SDKName:             SDKName,
		SDKVersion:          sdkVersion,
		StartAttributes: BuildRequestStartSpanAttributes(
			resource, operation, httpMethod, httpURL, serverAddress, chargebeeSite, chargebeeAPIVersion, sdkVersion,
		),
	}
}

// BuildRequestTelemetryResult builds a RequestTelemetryResult.
func BuildRequestTelemetryResult(httpStatusCode int, durationMs int64, err *RequestTelemetryError) RequestTelemetryResult {
	return RequestTelemetryResult{
		HTTPStatusCode: httpStatusCode,
		DurationMs:     durationMs,
		Error:          err,
		EndAttributes:  BuildRequestEndSpanAttributes(httpStatusCode, err),
	}
}
