// This file is auto-generated by Chargebee.
// For more information on how to make changes to this file, please see the README.
// Reach out to dx@chargebee.com for any questions.
// Copyright 2026 Chargebee Inc.

package telemetry

// TelemetryAdapter is an optional telemetry adapter for observability integrations (e.g. OpenTelemetry).
//
// When not configured, the SDK skips all telemetry work — zero overhead. The SDK stores the
// adapter by reference and never clones or deep-copies it.
//
// Implementations may inject W3C trace context headers (traceparent, tracestate) into
// requestHeaders during OnRequestStart.
type TelemetryAdapter interface {
	// OnRequestStart is called once per SDK API call before the request is sent (including before retries).
	//
	// context contains prebuilt start attributes. requestHeaders is a mutable map for trace propagation.
	// Returns an opaque handle passed back to OnRequestEnd, or nil if span creation was skipped.
	OnRequestStart(context RequestTelemetryContext, requestHeaders map[string]string) any

	// OnRequestEnd is called once per SDK API call after the final response or terminal failure.
	//
	// handle is the value returned from OnRequestStart and may be nil. result contains prebuilt end attributes.
	OnRequestEnd(handle any, result RequestTelemetryResult)
}
