package enum

type GatewayName string

const (
	GatewayNameChargebee             GatewayName = "chargebee"
	GatewayNameChargebeePayments     GatewayName = "chargebee_payments"
	GatewayNameAdyen                 GatewayName = "adyen"
	GatewayNameStripe                GatewayName = "stripe"
	GatewayNameWepay                 GatewayName = "wepay"
	GatewayNameBraintree             GatewayName = "braintree"
	GatewayNameAuthorizeNet          GatewayName = "authorize_net"
	GatewayNamePaypalPro             GatewayName = "paypal_pro"
	GatewayNamePin                   GatewayName = "pin"
	GatewayNameEway                  GatewayName = "eway"
	GatewayNameEwayRapid             GatewayName = "eway_rapid"
	GatewayNameWorldpay              GatewayName = "worldpay"
	GatewayNameBalancedPayments      GatewayName = "balanced_payments"
	GatewayNameBeanstream            GatewayName = "beanstream"
	GatewayNameBluepay               GatewayName = "bluepay"
	GatewayNameElavon                GatewayName = "elavon"
	GatewayNameFirstDataGlobal       GatewayName = "first_data_global"
	GatewayNameHdfc                  GatewayName = "hdfc"
	GatewayNameMigs                  GatewayName = "migs"
	GatewayNameNmi                   GatewayName = "nmi"
	GatewayNameOgone                 GatewayName = "ogone"
	GatewayNamePaymill               GatewayName = "paymill"
	GatewayNamePaypalPayflowPro      GatewayName = "paypal_payflow_pro"
	GatewayNameSagePay               GatewayName = "sage_pay"
	GatewayNameTco                   GatewayName = "tco"
	GatewayNameWirecard              GatewayName = "wirecard"
	GatewayNameAmazonPayments        GatewayName = "amazon_payments"
	GatewayNamePaypalExpressCheckout GatewayName = "paypal_express_checkout"
	GatewayNameGocardless            GatewayName = "gocardless"
	GatewayNameOrbital               GatewayName = "orbital"
	GatewayNameMonerisUs             GatewayName = "moneris_us"
	GatewayNameMoneris               GatewayName = "moneris"
	GatewayNameBluesnap              GatewayName = "bluesnap"
	GatewayNameCybersource           GatewayName = "cybersource"
	GatewayNameVantiv                GatewayName = "vantiv"
	GatewayNameCheckoutCom           GatewayName = "checkout_com"
	GatewayNamePaypal                GatewayName = "paypal"
	GatewayNameIngenicoDirect        GatewayName = "ingenico_direct"
	GatewayNameExact                 GatewayName = "exact"
	GatewayNameMollie                GatewayName = "mollie"
	GatewayNameQuickbooks            GatewayName = "quickbooks"
	GatewayNameRazorpay              GatewayName = "razorpay"
	GatewayNameGlobalPayments        GatewayName = "global_payments"
	GatewayNameBankOfAmerica         GatewayName = "bank_of_america"
	GatewayNameEcentric              GatewayName = "ecentric"
	GatewayNameMetricsGlobal         GatewayName = "metrics_global"
	GatewayNameWindcave              GatewayName = "windcave"
	GatewayNamePayCom                GatewayName = "pay_com"
	GatewayNameEbanx                 GatewayName = "ebanx"
	GatewayNameDlocal                GatewayName = "dlocal"
	GatewayNameNuvei                 GatewayName = "nuvei"
	GatewayNameSolidgate             GatewayName = "solidgate"
	GatewayNamePaystack              GatewayName = "paystack"
	GatewayNameJpMorgan              GatewayName = "jp_morgan"
	GatewayNameDeutscheBank          GatewayName = "deutsche_bank"
	GatewayNameEzidebit              GatewayName = "ezidebit"
	GatewayNameTwikey                GatewayName = "twikey"
	GatewayNameTempus                GatewayName = "tempus"
	GatewayNameMoyasar               GatewayName = "moyasar"
	GatewayNamePayway                GatewayName = "payway"
	GatewayNameNotApplicable         GatewayName = "not_applicable"
)
