package enum

type PaymentMethod string

const (
	PaymentMethodCash                  PaymentMethod = "cash"
	PaymentMethodCheck                 PaymentMethod = "check"
	PaymentMethodBankTransfer          PaymentMethod = "bank_transfer"
	PaymentMethodOther                 PaymentMethod = "other"
	PaymentMethodCustom                PaymentMethod = "custom"
	PaymentMethodChargeback            PaymentMethod = "chargeback"
	PaymentMethodCard                  PaymentMethod = "card"
	PaymentMethodAmazonPayments        PaymentMethod = "amazon_payments"
	PaymentMethodPaypalExpressCheckout PaymentMethod = "paypal_express_checkout"
	PaymentMethodDirectDebit           PaymentMethod = "direct_debit"
	PaymentMethodAlipay                PaymentMethod = "alipay"
	PaymentMethodUnionpay              PaymentMethod = "unionpay"
	PaymentMethodApplePay              PaymentMethod = "apple_pay"
	PaymentMethodWechatPay             PaymentMethod = "wechat_pay"
	PaymentMethodAchCredit             PaymentMethod = "ach_credit"
	PaymentMethodSepaCredit            PaymentMethod = "sepa_credit"
	PaymentMethodIdeal                 PaymentMethod = "ideal"
	PaymentMethodGooglePay             PaymentMethod = "google_pay"
	PaymentMethodSofort                PaymentMethod = "sofort"
	PaymentMethodBancontact            PaymentMethod = "bancontact"
	PaymentMethodGiropay               PaymentMethod = "giropay"
	PaymentMethodDotpay                PaymentMethod = "dotpay"
	PaymentMethodUpi                   PaymentMethod = "upi"
	PaymentMethodNetbankingEmandates   PaymentMethod = "netbanking_emandates"
	PaymentMethodBoleto                PaymentMethod = "boleto"
	PaymentMethodVenmo                 PaymentMethod = "venmo"
	PaymentMethodPayTo                 PaymentMethod = "pay_to"
	PaymentMethodFasterPayments        PaymentMethod = "faster_payments"
	PaymentMethodSepaInstantTransfer   PaymentMethod = "sepa_instant_transfer"
	PaymentMethodAutomatedBankTransfer PaymentMethod = "automated_bank_transfer"
	PaymentMethodKlarnaPayNow          PaymentMethod = "klarna_pay_now"
	PaymentMethodOnlineBankingPoland   PaymentMethod = "online_banking_poland"
)
