package enum

type Type string

const (
	TypeCard                      Type = "card"
	TypePaypalExpressCheckout     Type = "paypal_express_checkout"
	TypeAmazonPayments            Type = "amazon_payments"
	TypeDirectDebit               Type = "direct_debit"
	TypeGeneric                   Type = "generic"
	TypeAlipay                    Type = "alipay"
	TypeUnionpay                  Type = "unionpay"
	TypeApplePay                  Type = "apple_pay"
	TypeWechatPay                 Type = "wechat_pay"
	TypeIdeal                     Type = "ideal"
	TypeGooglePay                 Type = "google_pay"
	TypeSofort                    Type = "sofort"
	TypeBancontact                Type = "bancontact"
	TypeGiropay                   Type = "giropay"
	TypeDotpay                    Type = "dotpay"
	TypeUpi                       Type = "upi"
	TypeNetbankingEmandates       Type = "netbanking_emandates"
	TypeVenmo                     Type = "venmo"
	TypePayTo                     Type = "pay_to"
	TypeFasterPayments            Type = "faster_payments"
	TypeSepaInstantTransfer       Type = "sepa_instant_transfer"
	TypeAutomatedBankTransfer     Type = "automated_bank_transfer"
	TypeKlarnaPayNow              Type = "klarna_pay_now"
	TypeOnlineBankingPoland       Type = "online_banking_poland"
	TypePayconiqByBancontact      Type = "payconiq_by_bancontact"
	TypeElectronicPaymentStandard Type = "electronic_payment_standard"
	TypeKbcPaymentButton          Type = "kbc_payment_button"
	TypePayByBank                 Type = "pay_by_bank"
	TypeTrustly                   Type = "trustly"
	TypeStablecoin                Type = "stablecoin"
	TypeKakaoPay                  Type = "kakao_pay"
	TypeNaverPay                  Type = "naver_pay"
	TypeRevolutPay                Type = "revolut_pay"
	TypeCashAppPay                Type = "cash_app_pay"
	TypePix                       Type = "pix"
	TypeTwint                     Type = "twint"
	TypeGoPay                     Type = "go_pay"
	TypeGrabPay                   Type = "grab_pay"
	TypePayCo                     Type = "pay_co"
	TypeAfterPay                  Type = "after_pay"
	TypeSwish                     Type = "swish"
	TypePayme                     Type = "payme"
	TypeFreeTrial                 Type = "free_trial"
	TypePayUpFront                Type = "pay_up_front"
	TypePayAsYouGo                Type = "pay_as_you_go"
	TypeUsageExceeded             Type = "usage_exceeded"
)
